### ISSUE TITLE
Data returned by mcrouter is not recognised in order to be unserialized

### ISSUE THREAD

**Issue by huannh** [facebook/mcrouter#10]
I have a php code that use php-memcache extension, but somehow the php-memcache doesn't unserialize the data. Do you have any idea if there is something missing? If I connect to a normal memcached client with the same code, it is able to unserialize the data.

**Comment by alikhtarov** [comment]
@huannh : please reopen if you have more information. Unfortunately we can't really debug this without any details.

**Comment by huannh** [comment]
thanks @alikhtarov sorry, I missed the previous notification and didn't work on the issue since then. I will reopen it if I encounter it again.
