### ISSUE TITLE
Significance of certain mcrouter stats for monitoring and alerting

### ISSUE THREAD

**Issue by jkchin** [facebook/mcrouter#100]
What's the significance of the following stats in the context of monitoring and alerting:
- destination_batch_size
- mc_msg_num_outstanding
- mcc_txbuf_reqs
- mcc_waiting_replies
- proxy_request_num_outstanding vs proxy_reqs_waiting

Also what other stats do you recommend for tracking for monitoring and alerting

I've the following:
- duration_us
- num_clients
- fibers_allocated # feel of concurrent requests and memory consumption

**Comment by andreazevedo** [comment]
Hello @jkchin,

Here are the description of the stats you asked for:
 - `destination_batch_size`: Mcrouter has to ability to group requests and send them together in a single write loop. This number is the fraction `<requests_sent>` / `<batches_count>`.
 - `mc_msg_num_outstanding`: This stat is not used anymore. It was used to keep track of the number of instances of messages mcrouter had at any given point time.
 - `mcc_txbuf_reqs`: This is number of pending requests - requests that have not been not sent to the network yet.
 - `mcc_waiting_replies`: Number of requests that are inflight - that is, requests that were sent to the network but their corresponding replies haven't been received yet.
 - `proxy_request_num_outstanding`: is the replacement for `mc_msg_num_outstanding` mentioned above. Represents the total number of request instances currently living in mcrouter.
 - `proxy_reqs_waiting`: This is somehow similar to `mcc_waiting_replies`. The main difference is that `proxy_reqs_waiting` also counts requests queued but not yet sent to the network.

About what to monitor, it depends a lot on your config and environment. Here are some other stats that you might consider monitoring:
 - `result_error`: total number of requests that resulted in error.
 - `cmd_[operation]` (e.g. `cmd_get`): good to see how many requests you are processing.
 - `asynclog_requests `: if you spool deletes, that's a good metric to keep track of.

**Comment by jkchin** [comment]
Thanks for the info!
