### ISSUE TITLE
Unrecognized option: --cluster-pools-timeout

### ISSUE THREAD

**Issue by AlexKapustin** [facebook/mcrouter#101]
Greetings!
After updating mcrouter we noticed error:
`Unrecognized option: --cluster-pools-timeout`
in help output we can see:
`-t, --server-timeout server timeout in ms (DEPRECATED try to use cluster-pools-timeout and regional-pools-timeout) [default: 1000]`
But there is no `cluster-pools-timeout` option available
By investigation deeper I found that option was removed in commit: `7d37c46fecae8ed2ea58a31ea5ecb9767638a833`
And message is not related to this option. Also there is no new option added.
Could you please suggest with option should we use instead ?
Thank you in advance!
Have a great day!

Have a Merry Christmas and a Happy New year!

**Comment by andreazevedo** [comment]
Hello @AlexKapustin,

Thanks for the report and investigation!
In fact, `server-timeout-ms` is not deprecated and you can use it safely! I will fix the message.
Now, if you do want a more fine-grained timeout config, you can use `cross-region-timeout-ms`, `cross-cluster-timeout-ms`, `within-cluster-timeout-ms` and `waiting-request-timeout-ms`.

Thank you again and happy holidays!
