### ISSUE TITLE
Release archive missing FOLLY_RELEASE file

### ISSUE THREAD

**Issue by samveen** [facebook/mcrouter#102]
Please create the release tags from the respective release branch instead of from the `master` branch i.e. `release-16-0` etc. If not, the solution described in #98 doesn't work, especially with regards to automation for package building.

```
[samveen@buildhost ~]# tar tz < <(wget -O - -q https://github.com/facebook/mcrouter/archive/v0.16.0.tar.gz)  |grep -i folly
mcrouter-0.16.0/mcrouter/scripts/order_ubuntu-12.04/30_folly
mcrouter-0.16.0/mcrouter/scripts/order_ubuntu-14.04/10_folly
mcrouter-0.16.0/mcrouter/scripts/order_ubuntu-15.04/10_folly
mcrouter-0.16.0/mcrouter/scripts/recipes/folly.sh
```

**Comment by jmswen** [comment]
Hi @samveen, you could instead use the release branch archive (not the release tag archive), e.g., https://github.com/facebook/mcrouter/archive/release-16-0.tar.gz.  Does this solve your issue?

**Comment by samveen** [comment]
@jmswen The problem is that the release branch name doesn't match the version of the release in a manner that is amenable to automation. Giving an example is out of my spec file:
```
Version: 1.17.0
Source0: https://github.com/%{git_owner}/%{git_project}/archive/v%{version}/%{git_project}-%{version}.tar.gz
```
Now let's take the example of mcrouter:
```
%define version_major 0
%define version_minor 16
%define version_release 0
Version: %{version_major}.%{version_minor}.%{version_release}
Source0: https://github.com/%{git_owner}/%{git_project}/archive/release-%{version_minor}-%{version_release}/%{git_project}-%{version}.tar.gz
```
What happens when mcrouter hit's major_version 1? The source URL structure changes, and there breaks my automated system of releases.

Another point is, that as per my understanding of the git release process, a particular `release` archive should contain everything for building the software of that version. Thus my request to create a release from the correct release branch instead of the `master` branch, as the master branch is always missing the *_RELEASE files.

**Comment by samveen** [comment]
@jmswen My point, Jon, is that the release should be cut from the release branch, which includes all the dependency information, instead of the master branch, which contains no dependency information. 

Please take a look at https://github.com/kubernetes/kubernetes/releases/tag/v1.1.8 for an example of a release created from a release branch rather than a master branch.

**Comment by samveen** [comment]
Closing, as:
-  Packaged  mcrouter releases are now available from upstream repositories.
- Centos is dead, Long live Centos.
- Install scripts recipe for folly works around the missing dependency, and that can be used for packaging (mcrouter/scripts/recipes/folly.sh).
