### ISSUE TITLE
Dependency information for fbthrift

### ISSUE THREAD

**Issue by samveen** [facebook/mcrouter#103]
Please add a FBTHRIFT_COMMIT file to the release branches, in the same spirit as the FOLLY_COMMIT files, as the [facebook/fbthrift]( http://www.github.com/facebook/fbthrift) project has no release synchronization with mcrouter.

**Comment by jmswen** [comment]
Hi @samveen, we should have a FBTHRIFT_COMMIT file within the next couple releases.  I'll keep you posted in this issue.

**Comment by samveen** [comment]
Thank you for making my packaging life easier. If I could get the same kind of information between [fbthrift](https://github.com/facebook/fbthrift) and [wangle](https://github.com/facebook/wangle), I could completely automate my builts.

**Comment by jmswen** [comment]
@samveen, do you use wangle for something besides mcrouter?  wangle isn't needed at all to build mcrouter -- the `mcrouter/scripts/install_ubuntu_1X.04.sh` build scripts do some magic to avoid the wangle dependency in fbthrift.  I can provide more detail if needed.

**Comment by samveen** [comment]
@jmswen That would be awesome, Jon. A caveat is that my target infrastructure is RH7 / Centos 7, and I'm got the job of packaging all those facebook open source projects that we use (plus dependencies like folly/fbthift/wangle) into RPMs in my company. Everytime any of the your projects issues a new release, I face the same nightmare again :sob: .

However, I cannot realistically expect anyone to do my job for me (that's open source for you), just hoping for a little help to make my own task a slightly easier :smirk: .

**Comment by jmswen** [comment]
`FBTHRIFT_COMMIT` file will be present in next release branch.  See 28725327c7fa6606bb6a2f33af9e856afda18827.

**Comment by jmswen** [comment]
@samveen, regarding some further details of the mcrouter build process: mcrouter depends on only the parts of fbthrift responsible for C++ generation from Thrift structure definitions and the protocol/serialization/deserialization logic that mcrouter needs to understand Thrift-encoded data that comes in on the wire.  In particular, mcrouter does not depend on the client/server logic in fbthrift, so mcrouter avoids depending on wangle.  There are a few code snippets that are useful in seeing how to avoid the dependency on wangle (one of them is quite hacky at the moment).  

Unfortunately, I have never built mcrouter on Centos 7 from source, but you'll probably want to copy the steps we take to build mcrouter on Ubuntu.  This script for Ubuntu 14.04 https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/install_ubuntu_14.04.sh installs some `apt-get` dependencies, then builds/installs folly, fbthrift, and mcrouter.

Here is how we install fbthrift: https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/recipes/fbthrift.sh.  Importantly, we pass the `--without-cpp` flag to fbthrift's configure script.  This allows us to avoid the client/server portion of fbthrift as I mentioned (as well as the wangle dependency).

Later, when we install mcrouter (https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/recipes/mcrouter.sh), we need to set `THRIFT2_COMP_DIR` (the directory containing the Thrift compiler) and pass that to mcrouter's configure script.  The value of this variable should be set to the directory containing this file: https://github.com/facebook/fbthrift/blob/master/thrift/compiler/py/main.py

Finally, there is one `sed` hack that modifies Thrift-generated code in mcrouter's `Makefile`: https://github.com/facebook/mcrouter/blob/master/mcrouter/lib/Makefile.am#L9  If you are able to use mcrouter's `Makefile` mostly as-is, then you shouldn't need to worry about modifying this target.  

Hope this extra information about dealing with the fbthrift dependency helps.

**Comment by samveen** [comment]
@jmswen Thank you for this information, Jon. This does makes my work a lot easier.
