### ISSUE TITLE
mcrouter and libmemcached compatibility

### ISSUE THREAD

**Issue by AlexKapustin** [facebook/mcrouter#104]
Hello guys!

Please advice with version of libmemcached is most compatible with mcrouter ?
We are trying to update mcrouter to latest version (v0.16.0), but get response code 47 from mcrouter which mean:`47 = MEMCACHED_SERVER_TEMPORARILY_DISABLED`
Did you meet that error ? How did you resolve it ?

Thank you!
Have a great day!

**Comment by jmswen** [comment]
@AlexKapustin, could you provide more detail about your exact memcached + mcrouter configuration and the commands you're running?  That would help me to try to reproduce it.  Also, do you mean that the exact same setup works with mcrouter v0.15.0 but not v0.16.0?  And are you able to send commands successfully through mcrouter manually, e.g., by running 
 
    printf "get mykey\r\n" | nc localhost <mcrouter-port>

?

**Comment by AlexKapustin** [comment]
@jmswen Hello!
I found the problem, and probably it's not related to libmemcached, sorry for confusing.

I found in strace that `stats` command has being sending with space:

php code:
```
<?php
$mc = new Memcached();
$mc->addServer('localhost', 2314);
$mc->getStats();
```
strace:
`sendto(4, "stats \r\n", 8, MSG_NOSIGNAL, NULL, 0) = 8`

```
$ /local/bin/mcrouter -V
mcrouter 16.0.0
$ echo -e "stats \r\n" | nc localhost 2314
CLIENT_ERROR malformed request
```

In the same time:
```
$ /local/bin/mcrouter -V
mcrouter 2.0.0

$ echo -e "stats \r\n" | nc localhost 2314
STAT version mcrouter 2.0.0
....
```

Thanks.

**Comment by andreazevedo** [comment]
Hello @AlexKapustin,

Thanks for reporting this issue.
The new version of mcrouter does not support spaces after the `stats` command (i.e. `stats \r\n` is invalid), but don't worry, we are working on fix, it should be out soon!
I'll let you know as soon as the fix is available.

Thank you

**Comment by AlexKapustin** [comment]
Thank you for your effort!
