### ISSUE TITLE
Spymemcached: asyncGet causes java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by adityamarella** [facebook/mcrouter#108]
This exception DOES NOT happen with memached which indicates that there is something wrong with the way mcrouter is handling asyncget. 

And, curiously this is happening only with asyncget. Asynchronous set DOES NOT cause this issue.

> **Version Information**
> mcrouter: 0.17.0
> memcached: 1.4.25
> spymemcached: 2.11.7
```
<dependency>
	<groupId>net.spy</groupId>
	<artifactId>spymemcached</artifactId>
	<version>2.11.7</version>
</dependency>
```

The following steps will reproduce this Exception -

- Start mcrouter with PoolRoute setup to two memcached nodes. For ex:

`mcrouter --config-str='{\"pools\":{\"main\":{\"servers\":[\"memcached1:11211\",\"memcached2:11211\"]}},\"route\":\"PoolRoute|main\"}' -p 11211`

- Change HOSTNAME in the code below to point to your mcrouter hostname and run the code as a junit test

```
package org.foo.test;

import java.io.IOException;
import java.nio.channels.UnresolvedAddressException;

import net.spy.memcached.AddrUtil;
import net.spy.memcached.ConnectionFactoryBuilder;
import net.spy.memcached.ConnectionFactoryBuilder.Protocol;
import net.spy.memcached.FailureMode;
import net.spy.memcached.MemcachedClient;
import net.spy.memcached.MemcachedClientIF;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

public class AsyncSpymemcachedTest {
	
	public static final String SERVERS = "HOSTNAME:11211";
	
	public static final String KEY = "_async_test_key_";
	
	public MemcachedClientIF client;
	
	@Before
	public void init() {
		try {
			client = createClient(SERVERS);
			client.add(KEY, 200, 100);
		} catch (UnresolvedAddressException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	@After
	public void close() {
		if (client != null)
			client.shutdown();
	}
	
	protected MemcachedClientIF createClient(String servers)
			throws IOException, UnresolvedAddressException {
		final ConnectionFactoryBuilder cfb = new ConnectionFactoryBuilder();
		cfb.setProtocol(Protocol.TEXT);
		cfb.setOpTimeout(5000);
		cfb.setFailureMode(FailureMode.Retry);
		cfb.setOpQueueMaxBlockTime(250);
		cfb.setTimeoutExceptionThreshold(100);
		cfb.setMaxReconnectDelay(10);
		return new MemcachedClient(cfb.build(), AddrUtil.getAddresses(SERVERS));
	}
	
	/**
	 * Throws java.io.IOException: Broken pipe with mcrouter
	 * Works fine with memcached - no broken pipe.
	 * 
	 * NOTE: purposefully running an infinite loop to reproduce this Exception. 
	 */
	@Test
	public void testAsyncGet() {
		do {
			try {
				client.asyncGet(KEY);
			} catch (Exception e) {
				System.out.println(e);
			}
		} while(true);
	}
	
	/**
	 * Works fine with both memcached and mcrouter
	 */
	@Ignore
	@Test
	public void testGet() {
		do {
			try {
				client.get(KEY);
			} catch (Exception e) {
				System.out.println(e);
			}
		} while(true);
	}
	
	/**
	 * Works fine with both memcached and mcrouter
	 */
	@Ignore
	@Test
	public void testSet() {
		do {
			try {
				client.set(KEY, 100, 1);
			} catch (Exception e) {
				System.out.println(e);
			}
		} while(true);
	}

}
```

**Comment by andreazevedo** [comment]
Hello @adityamarella,

First of all, thank you for reporting this issue.
We'll be happy to help you, but first I need some information to understand what is going on:

1) For long (seconds and number of operations) does the loop run before you get the exception?
2) Can you provide us mcrouter's output?

Thank you,
Andre

**Comment by adityamarella** [comment]
Thanks for the quick response!

Loops runs for about 10s before this exception occurs.

> **Mcrouter logs**
> I0210 18:09:13.551785     1 main.cpp:390] mcrouter --config-str={"pools":{"main":{"servers":["memcached1:11211","memcached2:11211"]}},"route":"PoolRoute|main"} -p 11211 
> I0210 18:09:13.551933     1 main.cpp:491] mcrouter 17.0.0-master startup (1)
> I0210 18:09:13.552022     1 server.cpp:110] Spawning AsyncMcServer
> W0210 18:09:13.552160     1 McrouterInstance.cpp:159] Error while checking spooldir (/var/spool/mcrouter): No such file or directory [2]
> I0210 18:09:13.565188     1 McrouterInstance.cpp:546] started reconfiguring
> I0210 18:09:13.565635     1 McrouterInstance.cpp:569] reconfigured 1 proxies with 1 pools, 2 clients f818b1842758a1d99da0bb88607ce1f1)
> I0210 18:09:24.978390    14 ProxyDestination.cpp:370] server memcached1:11211:ascii:plain-1000 up (1 of 2)
> 

> **Client logs**
> 2016-02-10 10:09:24.964 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/10.0.0.100:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
> java.lang.IllegalStateException: Timed out waiting to add Cmd: get Keys: _async_test_key_Exp: 0(max wait=250ms)
> 2016-02-10 10:09:33.859 WARN net.spy.memcached.MemcachedConnection:  Exception handling write
> java.io.IOException: Broken pipe
> 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
> 	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
> 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
> 	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
> 	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
> 	at net.spy.memcached.protocol.TCPMemcachedNodeImpl.writeSome(TCPMemcachedNodeImpl.java:569)
> 	at net.spy.memcached.MemcachedConnection.handleWrites(MemcachedConnection.java:798)
> 	at net.spy.memcached.MemcachedConnection.handleInputQueue(MemcachedConnection.java:582)
> 	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:409)
> 	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1446)
> 2016-02-10 10:09:33.861 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=/10.0.0.100:11211, #Rops=8791, #Wops=524627, #iq=2397, topRop=Cmd: get Keys: _async_test_key_Exp: 0, topWop=Cmd: get Keys: _async_test_key_Exp: 0, toWrite=16384, interested=5}, attempt 0.
> 2016-02-10 10:09:33.862 WARN net.spy.memcached.protocol.ascii.AsciiMemcachedNodeImpl:  Discarding partially completed op: Cmd: get Keys: _async_test_key_Exp: 0
>

**Comment by andreazevedo** [comment]
Hello @adityamarella,

Sorry for the delay.
What your test is doing is sending a huge amount of `GET` requests in a loop without even waiting for the replies. I looked into Spymemcached code and realized that they use a bounded queue (`java.util.concurrent.BlockingQueue`), and that queue is getting full (see [here](https://github.com/dustin/java-memcached-client/blob/953c322ad254bf6f544bac6738114176040a9c6f/src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java#L361-L364)). Spymemcached throws an exception when that occurs instead of returning an error.

That is not a mcrouter issue. Basically you are sending requests until you client cannot queue up requests to send to mcrouter.
When way you can give more "power" to mcrouter, is to start mcrouter with more than one proxy thread (`--proxy-threads=4`) and use more than one client (in your case `MemcachedClientIF`) to send requests in a round robin manner. In that way, mcrouter will process requests in parallel.

If you want to know what is going on under the hood, you can always start [mcpiper](https://github.com/facebook/mcrouter/wiki/Mcpiper).

Let me know if that helped or if you have more questions.

**Comment by adityamarella** [comment]
No worries. Thanks for looking into this.

I understand that this is a fringe scenario where the input queue is getting full because of the huge amount of asyncGet requests. I did look at spymemcached code before posting this issue. Basically, when the input queue (`java.util.concurrent.BlockingQueue`) fills up, new requests wait for OpQueueMaxBlockTime before timing out. The `IllegalStateException` below suggests that a request has waited for OpQueueMaxBlockTime(`=250ms`) to enter the queue before timing out. This is Spymemcached's way of throttling outgoing requests. It is all fair game until this point. Infact when I directly hit memcached without mcrouter, I only see these `IllegalStateException`(s).

> **Client logs against memcached**
> 2016-02-12 14:37:21.650 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/10.0.0.100:11215, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
> java.lang.IllegalStateException: Timed out waiting to add Cmd: get Keys: _async_test_key_Exp: 0(max wait=250ms)
> java.lang.IllegalStateException: Timed out waiting to add Cmd: get Keys: _async_test_key_Exp: 0(max wait=250ms)

> **Client logs against mcrouter**
> 2016-02-12 14:35:31.351 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/10.0.0.100:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
> java.lang.IllegalStateException: Timed out waiting to add Cmd: get Keys: _async_test_key_Exp: 0(max wait=250ms)
> 2016-02-12 14:35:41.034 WARN net.spy.memcached.MemcachedConnection:  Exception handling write
> java.io.IOException: Broken pipe
> 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
> 	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
> 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
> 	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
> 	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
> 	at net.spy.memcached.protocol.TCPMemcachedNodeImpl.writeSome(TCPMemcachedNodeImpl.java:569)
> 	at net.spy.memcached.MemcachedConnection.handleWrites(MemcachedConnection.java:798)
> 	at net.spy.memcached.MemcachedConnection.handleInputQueue(MemcachedConnection.java:582)
> 	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:409)
> 	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1446)
> 2016-02-12 14:35:41.037 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=/10.0.0.100:11211, #Rops=21598, #Wops=502619, #iq=2874, topRop=Cmd: get Keys: _async_test_key_Exp: 0, topWop=Cmd: get Keys: _async_test_key_Exp: 0, toWrite=16384, interested=5}, attempt 0

It is unclear why mcrouter decides to close the client socket resulting in IOException: Broken pipe. You could be right in that this could be a feature rather than an issue. May be --max-client-outstanding-reqs limit is hit and this is closing client socket? I could not prove this though. It would be helpful if there is a log statement when these thresholds are hit. 

Thanks,
Aditya

**Comment by andreazevedo** [comment]
Oh I see. You are asking specifically about the Broken Pipe error. Sorry about the misunderstanding.
So, the best way to see what is going in this case on is too increase mcrouter's verbose level (`-v 5` will do it).

Can you please do that and post the error message here?
Thank you

**Comment by adityamarella** [comment]
Here are the verbose logs around when Broken pipe occurred -
> I0213 02:11:21.849897    14 AsyncSocket.cpp:1892] AsyncSocket(this=0x7fcd74af3080, fd=25, state=2 host=10.0.0.1:54978): failed while writing in timeoutExpired(): write timed out
> I0213 02:11:21.867573    14 AsyncSocket.cpp:249] AsyncSocket::destroy(this=0x7fcd74af3080, evb=0x7fcd74815f08, fd=-1, state=4
> I0213 02:11:21.867637    14 AsyncSocket.cpp:811] AsyncSocket::closeNow(): this=0x7fcd74af3080, fd_=-1, state=4, shutdownFlags=6
> I0213 02:11:21.867688    14 EventBase.cpp:424] EventBase(): Done with loop.
> I0213 02:11:21.867709    14 EventBase.cpp:295] EventBase(): Starting loop.
> I0213 02:11:26.585525    14 EventBase.cpp:424] EventBase(): Done with loop.
> I0213 02:11:26.585602    14 EventBase.cpp:295] EventBase(): Starting loop.
> I0213 02:11:26.585672    14 AsyncSocket.cpp:215] new AsyncSocket(0x7fcd74af3080, evb=0x7fcd74815f08, fd=25

Here is the output of `stats all` after multiple Broken Pipes:

> 
> stats all
> STAT version mcrouter 17.0.0-master
> STAT commandargs --config-str={"pools":{"main":{"servers":["memcached1:11211","memcached2:11211"]}},"route":"PoolRoute|main"} -p 11211
> STAT pid 1
> STAT parent_pid 0
> STAT time 1455336744
> STAT uptime 150
> STAT num_servers 2
> STAT num_servers_new 1
> STAT num_servers_up 1
> STAT num_servers_down 0
> STAT num_servers_closed 0
> STAT num_clients 1
> STAT num_suspect_servers 0
> STAT mcc_txbuf_reqs 0
> STAT mcc_waiting_replies 0
> STAT destination_batch_size 371.402
> STAT asynclog_requests 0
> STAT proxy_reqs_processing 1
> STAT proxy_reqs_waiting 0
> STAT client_queue_notify_period 0
> STAT rusage_system 6.57
> STAT rusage_user 10.67
> STAT ps_num_minor_faults 263540
> STAT ps_num_major_faults 0
> STAT ps_user_time_sec 10.67
> STAT ps_system_time_sec 6.57
> STAT ps_vsize 331399168
> STAT ps_rss 47898624
> STAT fibers_allocated 1007
> STAT fibers_pool_size 1007
> STAT fibers_stack_high_watermark 4180
> STAT successful_client_connections 12
> STAT cycles_avg 0
> STAT cycles_min 0
> STAT cycles_max 0
> STAT cycles_p01 0
> STAT cycles_p05 0
> STAT cycles_p50 0
> STAT cycles_p95 0
> STAT cycles_p99 0
> STAT cycles_num 0
> STAT duration_us 1722.19
> STAT rate_limited_log_count 0
> STAT cmd_cas_count 0
> STAT cmd_delete_count 0
> STAT cmd_get_count 2242715
> STAT cmd_gets_count 0
> STAT cmd_set_count 0
> STAT cmd_cas_outlier_count 0
> STAT cmd_cas_outlier_all_count 0
> STAT cmd_delete_outlier_count 0
> STAT cmd_delete_outlier_all_count 0
> STAT cmd_get_outlier_count 0
> STAT cmd_get_outlier_all_count 0
> STAT cmd_gets_outlier_count 0
> STAT cmd_gets_outlier_all_count 0
> STAT cmd_set_outlier_count 0
> STAT cmd_set_outlier_all_count 0
> STAT cmd_other_outlier_count 0
> STAT cmd_other_outlier_all_count 0
> STAT cmd_cas 0
> STAT cmd_delete 0
> STAT cmd_get 14951.4
> STAT cmd_gets 0
> STAT cmd_set 0
> STAT cmd_cas_outlier 0
> STAT cmd_cas_outlier_all 0
> STAT cmd_delete_outlier 0
> STAT cmd_delete_outlier_all 0
> STAT cmd_get_outlier 0
> STAT cmd_get_outlier_all 0
> STAT cmd_gets_outlier 0
> STAT cmd_gets_outlier_all 0
> STAT cmd_set_outlier 0
> STAT cmd_set_outlier_all 0
> STAT cmd_other_outlier 0
> STAT cmd_other_outlier_all 0
> STAT cmd_add_count 1
> STAT cmd_decr_count 0
> STAT cmd_incr_count 0
> STAT cmd_lease_get_count 0
> STAT cmd_lease_set_count 0
> STAT cmd_meta_count 0
> STAT cmd_other_count 0
> STAT cmd_replace_count 0
> STAT cmd_stats_count 1
> STAT redirected_lease_set_count 0
> STAT cmd_add 0.00666667
> STAT cmd_decr 0
> STAT cmd_incr 0
> STAT cmd_lease_get 0
> STAT cmd_lease_set 0
> STAT cmd_meta 0
> STAT cmd_other 0
> STAT cmd_replace 0
> STAT cmd_stats 0
> STAT cmd_cas_out_count 0
> STAT cmd_cas_out_all_count 0
> STAT cmd_delete_out_count 0
> STAT cmd_delete_out_all_count 0
> STAT cmd_get_out_count 2242715
> STAT cmd_get_out_all_count 2242715
> STAT cmd_gets_out_count 0
> STAT cmd_gets_out_all_count 0
> STAT cmd_set_out_count 0
> STAT cmd_set_out_all_count 0
> STAT cmd_add_out_count 1
> STAT cmd_add_out_all_count 1
> STAT cmd_decr_out_count 0
> STAT cmd_decr_out_all_count 0
> STAT cmd_incr_out_count 0
> STAT cmd_incr_out_all_count 0
> STAT cmd_lease_get_out_count 0
> STAT cmd_lease_get_out_all_count 0
> STAT cmd_lease_set_out_count 0
> STAT cmd_lease_set_out_all_count 0
> STAT cmd_meta_out_count 0
> STAT cmd_meta_out_all_count 0
> STAT cmd_other_out_count 0
> STAT cmd_other_out_all_count 0
> STAT cmd_replace_out_count 0
> STAT cmd_replace_out_all_count 0
> STAT cmd_cas_out 0
> STAT cmd_cas_out_all 0
> STAT cmd_delete_out 0
> STAT cmd_delete_out_all 0
> STAT cmd_get_out 14951.4
> STAT cmd_get_out_all 14951.4
> STAT cmd_gets_out 0
> STAT cmd_gets_out_all 0
> STAT cmd_set_out 0
> STAT cmd_set_out_all 0
> STAT cmd_add_out 0.00666667
> STAT cmd_add_out_all 0.00666667
> STAT cmd_decr_out 0
> STAT cmd_decr_out_all 0
> STAT cmd_incr_out 0
> STAT cmd_incr_out_all 0
> STAT cmd_lease_get_out 0
> STAT cmd_lease_get_out_all 0
> STAT cmd_lease_set_out 0
> STAT cmd_lease_set_out_all 0
> STAT cmd_meta_out 0
> STAT cmd_meta_out_all 0
> STAT cmd_other_out 0
> STAT cmd_other_out_all 0
> STAT cmd_replace_out 0
> STAT cmd_replace_out_all 0
> STAT config_age 150
> STAT config_last_attempt 1455336594
> STAT config_last_success 1455336594
> STAT config_failures 0
> STAT start_time 1455336594
> STAT dev_null_requests 0
> STAT request_sent_count 2242716
> STAT request_error_count 0
> STAT request_success_count 2242716
> STAT request_replied_count 2242716
> STAT request_sent 14951.4
> STAT request_error 0
> STAT request_success 14951.4
> STAT request_replied 14951.4
> STAT client_queue_notifications 0
> STAT failover_all 0
> STAT failover_all_failed 0
> STAT failover_rate_limited 0
> STAT result_error_count 0
> STAT result_error_all_count 0
> STAT result_connect_error_count 0
> STAT result_connect_error_all_count 0
> STAT result_connect_timeout_count 0
> STAT result_connect_timeout_all_count 0
> STAT result_data_timeout_count 0
> STAT result_data_timeout_all_count 0
> STAT result_busy_count 0
> STAT result_busy_all_count 0
> STAT result_tko_count 0
> STAT result_tko_all_count 0
> STAT result_local_error_count 0
> STAT result_local_error_all_count 0
> STAT result_error 0
> STAT result_error_all 0
> STAT result_connect_error 0
> STAT result_connect_error_all 0
> STAT result_connect_timeout 0
> STAT result_connect_timeout_all 0
> STAT result_data_timeout 0
> STAT result_data_timeout_all 0
> STAT result_busy 0
> STAT result_busy_all 0
> STAT result_tko 0
> STAT result_tko_all 0
> STAT result_local_error 0
> STAT result_local_error_all 0
> STAT mc_msg_num_outstanding 0
> STAT proxy_request_num_outstanding 1
> END

In looking at the stack trace, one particular line jumped out: `failed while writing in timeoutExpired(): write timed out`. After a bit of digging, we had a feeling it was related to `--server-timeout`.

After bumping the `server-timeout` from the default of 1000ms to a higher value like 10000ms, we weren't able to reproduce the Broken Pipe.

The peculiar thing is, when the value is at 1000ms, and Broken Pipes are occurring, there is nothing in the response of `stats all` that indicates anything is going wrong. So even if this behavior is to be expected with our value for `--server-timeout` when mcrouter is under high load, there should probably be a metric that counts these types of socket write failures, no?

Given the behavior above, we've lost confidence that we understand what `--server-timeout` is actually governing.

Would you mind going into detail on what  `--server-timeout` governs? Does it govern:

1. The time from when the request is received on mcrouter to the time it's sent back to the client
2. The time from when mcrouter sent the request to memcached until the time it's sent back to mcrouter
3. The time from when mcrouter sent the request to memcached until the time it's sent back to the client
4. None of the above

**Comment by andreazevedo** [comment]
Hello @adityamarella,

`--server-timeout` is used for 2 different things in mcrouter. One is what you described in number 2, and the other one is yet another thing: The time from when a reply is received from memcached (memcached->mcrouter) to the it is sent back to the client (mcrouter->client).

We don't have a separate config for those two things because in production we use a more granular [timeout setting for the mcrouter<->memcached communication](https://github.com/facebook/mcrouter/wiki/Command-line-options#timeouts)).

Nevertheless, this is a good opportunity for us to separate that in two distinct settings. I can send a patch to address this.

Thank you and let me know if you need anything else.

**Comment by adityamarella** [comment]
I think it make sense to separate out client-mcrouter and mcrouter-memcached timeouts. Although, I am not sure if you actually need client-mcrouter timeout? Memcached does not expose any such timeout.
Also, if you can tell us the timeout values you use in production that will be very helpful.

Thanks again for looking into this.

**Comment by andreazevedo** [comment]
I sent a patch to separate those two timeouts.
If you want to have the same behavior as memcached, you can set `--client-timeout` to 0 (memcached probably doesn't use timeout for this case).

As I said, we use very different timeouts for different scenarios. If mcrouter is talking to a memcached host inside the same cluster, we use very low timeout - the reason being we want to detect bad hosts/network as soon as possible to start failing over to healthy ones.
To talk cross region, we use a larger timeout - specially for when one region is geographically far from the other.

**Comment by adityamarella** [comment]
https://github.com/facebook/mcrouter/commit/7d7ab5ef7dbadf639fb33430074f44dde314acce
That was lightning fast! 

Thanks.

**Comment by andreazevedo** [comment]
No problem!
I'll close this task, but feel free to reopen if you need anything else!
