### ISSUE TITLE
error: 'TimeoutHandler' in 'class folly::fibers::Baton' does not name a type

### ISSUE THREAD

**Issue by jay7x** [facebook/mcrouter#110]
I'm trying to build mcrouter rpm for CentOS 6 and getting stuck with following error.
mcrouter-0.18.0, folly-0.57.0, fbthrift-0.31.0, boost-1.55.0. All built with gcc-4.8.2 (from devtoolset-2) and python2.6.

Actual error message I have is below. Any ideas what is wrong?

g++ -DHAVE_CONFIG_H   -I../..   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -std=gnu++1y -MT network/libmcrouter_a-AsyncMcClientImpl.o -MD -MP -MF network/.deps/libmcrouter_a-AsyncMcClientImpl.Tpo -c -o network/libmcrouter_a-AsyncMcClientImpl.o `test -f 'network/AsyncMcClientImpl.cpp' || echo './'`network/AsyncMcClientImpl.cpp
In file included from network/AsyncMcClientImpl.h:23:0,
                 from network/AsyncMcClientImpl.cpp:10:
../../mcrouter/lib/network/McClientRequestContext.h:107:3: error: 'TimeoutHandler' in 'class folly::fibers::Baton' does not name a type
   folly::fibers::Baton::TimeoutHandler batonTimeoutHandler_;
   ^
In file included from ../../mcrouter/lib/network/McClientRequestContext.h:326:0,
                 from network/AsyncMcClientImpl.h:23,
                 from network/AsyncMcClientImpl.cpp:10:
../../mcrouter/lib/network/McClientRequestContext-inl.h: In member function 'facebook::memcache::McClientRequestContext<Request>::Reply facebook::memcache::McClientRequestContext<Request>::waitForReply(std::chrono::milliseconds)':
../../mcrouter/lib/network/McClientRequestContext-inl.h:94:15: error: 'batonTimeoutHandler_' was not declared in this scope
   baton_.wait(batonTimeoutHandler_);
               ^
In file included from /usr/local/boost/1.55.0/include/boost/filesystem/path_traits.hpp:23:0,
                 from /usr/local/boost/1.55.0/include/boost/filesystem/path.hpp:25,
                 from /usr/local/boost/1.55.0/include/boost/filesystem.hpp:16,
                 from ../../mcrouter/lib/debug/FifoManager.h:17,
                 from network/AsyncMcClientImpl.cpp:16:
/usr/local/boost/1.55.0/include/boost/system/error_code.hpp: At global scope:
/usr/local/boost/1.55.0/include/boost/system/error_code.hpp:222:36: warning: 'boost::system::posix_category' defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
/usr/local/boost/1.55.0/include/boost/system/error_code.hpp:223:36: warning: 'boost::system::errno_ecat' defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
/usr/local/boost/1.55.0/include/boost/system/error_code.hpp:224:36: warning: 'boost::system::native_ecat' defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^
make[4]: *** [network/libmcrouter_a-AsyncMcClientImpl.o] Error 1
make[4]: Leaving directory `/home/rpmer/rpmbuild/BUILD/mcrouter-0.18.0/mcrouter/lib'

**Comment by jay7x** [comment]
I've just tried with mcrouter-0.19.0 and got same error. Is it mcrouter or folly problem?

**Comment by jmswen** [comment]
Hi @jay7x, unfortunately, the folly v0.57.0 (despite being the latest public tag) is too old to work with mcrouter.  You are seeing this error because `folly::fibers::Baton::TimeoutHandler` was added after folly v0.57.0.  In order to get mcrouter to work with folly, we recommend using the folly hash that is contained in the `mcrouter/FOLLY_COMMIT` file (https://github.com/facebook/mcrouter/blob/release-19-0/mcrouter/FOLLY_COMMIT).  We update the `FOLLY_COMMIT` file to a recent folly hash on every mcrouter release branch.  Please reopen this issue if you have any further trouble.

**Comment by samveen** [comment]
@jay7x Please take a look at the following issues for a solution to your problems:
Issues #98, #102 and #103 .

**Comment by jay7x** [comment]
Thank you @samveen! I've already finished my first quick&dirty packaging. Btw, can you please share your packages for CentOS 7? We will migrate soon so It'd be great to save some time on repackaging mcrouter + deps again.

**Comment by samveen** [comment]
@jay7x samveen/rpm-packaging for your viewing pleasure.
