### ISSUE TITLE
Is setrlimit still necessary? 

### ISSUE THREAD

**Issue by gengmao** [facebook/mcrouter#122]
I hit same issue as described in https://github.com/jamescarr/mcrouter-docker/issues/2. 
```
Warning: failed to setrlimit RLIMIT_NOFILE: Operation not permitted
```
Running  docker container in "--privileged" mode is a workaround. 

But I am curious if the comment at https://github.com/facebook/mcrouter/blob/master/mcrouter/main.cpp#L329 is still true? What's the libevent bug? If the bug is fixed, then we can remove that code block?

**Comment by pavlo-fb** [comment]
I think we can safely kill this. Diff coming.

**Comment by pavlo-fb** [comment]
See https://github.com/facebook/mcrouter/commit/e6125c2ae10073907a0d5167f8d0d9db1cebfe18

**Comment by gengmao** [comment]
Awesome. Thanks for prompt change, @pavlo-fb!
