### ISSUE TITLE
Recent mcrouter Commit Broke stats Compatibility

### ISSUE THREAD

**Issue by amcrn** [facebook/mcrouter#123]
Commit: https://github.com/facebook/mcrouter/commit/c650688a67ec6968e6c9e45df820cc6cbf59738f looks to have broken `stats` compatibility with the spymemcached library.

Prior to Version 0.23.0, if there were no suspect servers, `stats suspect_servers` would return:

```
stats suspect_servers
END
```

However, in 0.23.0 and onward, it's now:

```
stats suspect_servers

END
```

Note the additional `\r\n` before the `END` that didn't exist prior. This causes spymemcached to `ArrayIndexOutOfBoundsException` and close the connection!

See https://github.com/couchbase/spymemcached/blob/0be32615be36794ce664c24324f72b111441796a/src/main/java/net/spy/memcached/protocol/ascii/StatsOperationImpl.java#L56-L66

```
  @Override
  public void handleLine(String line) {
    if (line.equals("END")) {
      cb.receivedStatus(END);
      transitionState(OperationState.COMPLETE);
    } else {
      String[] parts = line.split(" ", 3);
      assert parts.length == 3;
      cb.gotStat(parts[1], parts[2]);
    }
  }
```

`cb.gotStat(parts[1], parts[2]);` causes an ArrayIndexOutOfBoundsException (because splitting on space on an empty string)

Although the memcached ASCII protocol document does *not* (AFAIK) explicitly state that extraneous newlines are prohibited (see https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L490-L500), I'd point to the fact that a `GET` on a key that has no value looks like:

```
get foo
END
```

No extra newline.

So although the error handling in spymemcached could be a little less drastic, I believe this to a regression in mcrouter.

Thoughts? Thanks!

**Comment by pavlo-fb** [comment]
Sure, we will fix it in mcrouter.

**Comment by amcrn** [comment]
really appreciate it it @pavlo-fb !
