### ISSUE TITLE
PrefixSelectorRoute 

### ISSUE THREAD

**Issue by scarletmeow** [facebook/mcrouter#124]
When loading a configuration for a failover to a prefix route, I get the error `Failed to reconfigure: Unknown RouteHandle: PrefixSelectorRoute`. It looks like `McRouteHandleProvider` doesn't support `PrefixSelectorRoute`, only the deprecated version `PrefixPolicyRoute` (pointing to a completely different route handle: https://github.com/facebook/mcrouter/blob/8596a87f16b5bbb164751cd291c240b8c40940fd/mcrouter/routes/McRouteHandleProvider.cpp#L197).

Example config:
```
{  
  "pools":{  
    "A":{  
      "servers":[  
        "memcached:11211"
      ]
    }
  },
  "route":{  
    "type":"FailoverRoute",
    "children":[  
      {  
        "type":"PrefixSelectorRoute",
        "policies":{  
          "a:":{  
            "type":"PoolRoute",
            "pool":"A"
          }
        },
        "wildcard":{  
          "type":"PoolRoute",
          "pool":"A"
        }
      },
      {  
        "type":"PoolRoute",
        "pool":"A"
      }
    ]
  }
}
```

Expected behavior:
Being able to compose PrefixSelectorRoutes with other routes.

**Comment by spalamarchuk** [comment]
@scarletmeow, PrefixSelectorRoute can only be used as a topmost route handle in config.

An example would be:
`{
  "pools":{
    "A":{
      "servers":[
        "memcached:11211"
      ]
    },
    "B":{
      "servers":[
        "memcached2:11211"
      ]
    }
  },
  "route":{
    "type":"PrefixSelectorRoute",
    "policies":{
      "a:":{
        "type":"FailoverRoute",
        "children":[
          "PoolRoute|A",
          "PoolRoute|B"
        ]
      }
    },
    "wildcard":{
      "type":"PoolRoute",
      "pool":"A"
    }
  }
}`

I'll update the wiki.

**Comment by scarletmeow** [comment]
Cool, thanks for the update! I wasn't sure if it was intentional.
