### ISSUE TITLE
Segfault with v25

### ISSUE THREAD

**Issue by nmerdan** [facebook/mcrouter#125]
We are experiencing a periodic segfault (happens a couple times per day) with the following config:
https://gist.github.com/nmerdan/e532c2c336a0526e97aab4fcdb83a69c

I don't think the configuration is the problem though as we've been using the same one on a couple of other projects without issues.

We've taken a coredump and this is what "bt full" and "thread apply all bt full" show:
https://gist.github.com/nmerdan/962e269cb20f018ef7960fd6408b9359

The service runs on Debian Wheezy x86_64, kernel 3.10. The service is used as:
mcrouter --async-dir /var/lib/mcrouter-11211/spool --stats-root /var/lib/mcrouter-11211/stats --debug-fifo-root /var/lib/mcrouter-11211/fifos --log-path /var/log/mcrouter/mcrouter-11211.log --port 11211 --config-file /usr/local/mcrouter/etc/mcrouter-11211.conf --num-proxies 48 --probe-timeout-initial 1000 --probe-timeout-max 30000 -t 5000

Please let me know what other information I can provide to aid debugging this issue.

**Comment by jmswen** [comment]
@nmerdan, from the backtrace, it looks like you may be sending non-ASCII keys to mcrouter.  I see some stuff starting with `Ñer...` around `getTargetsForKey()`.  mcrouter and memcached are only guaranteed to handle 250-character ASCII keys without space or control characters.  (Unless you're using Umbrella or Caret in mcrouter, which you're not.)  In mcrouter code, this assumption is used implicitly in several places.  Can you confirm that non-ASCII keys are indeed being sent to mcrouter?

**Comment by jmswen** [comment]
@nmerdan, Turns out it's an easy fix to support non-ASCII keys in mcrouter.  Fix coming.

**Comment by jmswen** [comment]
Support for non-ASCII keys is added in 8b1689311383d6fee334b1e8e7db20170d3b0966.  You can either build mcrouter from master or wait for release 26 to come out in a week or so.  Please reopen if this does not fix your issue.
