### ISSUE TITLE
excessive "Error getting host/port to write to debug fifo:" when using --unix-domain-sock

### ISSUE THREAD

**Issue by yenif** [facebook/mcrouter#126]
When connecting to mcrouter through a unix domain socket using `--unix-domain-sock` [MessageHeader buildMsgHeader](https://github.com/facebook/mcrouter/blob/2789993794577d39864ff8a4d6bafc7e667641bb/mcrouter/lib/debug/ConnectionFifo.cpp#L111)  doesn't appear to understand unix sockets and thus floods the logs with "[Error getting host/port to write to debug fifo](https://github.com/facebook/mcrouter/blob/2789993794577d39864ff8a4d6bafc7e667641bb/mcrouter/lib/debug/ConnectionFifo.cpp#L130)" at the WARNING log level.

Should either teach `MessageHeader buildMsgHeader` to understand unix sockets and add relevant information to the debug message or not log the warning when using a unix socket. Minimum would be to lower the log level for "Error getting host/port to write to debug fifo" to DEBUG.

**Comment by andreazevedo** [comment]
Hello @yenif,
Thanks for the report. We are working on that and it should be available soon.

**Comment by yenif** [comment]
Awesome, thanks.
