### ISSUE TITLE
Why isn't mcrouter pre-packaged?

### ISSUE THREAD

**Issue by deepub** [facebook/mcrouter#128]
I am new to mcrouter and learning the ropes here. Is there a reason why mcrouter isn't pre-packaged like other open source initiatives? I am struggling to make a build on CentOS and wondering why couldn't it be made simpler by just hosting the rpms too?

**Comment by deepub** [comment]
Closing this out as we've resolved this.

**Comment by jmswen** [comment]
@deepub, FWIW, providing packages is on our wishlist, and I hope to get around to it in the near future, but I won't make any promises publicly.  :)  We would likely start by building rpms for Ubuntu, see how adoption goes, see if we can make the release process manageable, etc. before considering building packages for other distros.

**Comment by deepub** [comment]
Hi @jmswen,
Thanks for sharing the planned roadmap/next steps. I am onboard with that approach. Our primary concern was to figure out if there are any specific kernel level gotchas that prevented you from providing the binaries.
Its clear that the issue is more around the manageability of the binaries and the various distros.

**Comment by meteozond** [comment]
For us as active debian mcrouter users prebuilt package is really crucial. Docker gives significant overhead due to `conntrac` hard linked dependency. Building from source is a challenge, due to sub-dependencies and platform specificities. As result deploying mcrouter takes a lot of time and is not consistent, difficult to support. May be it is early to close this issue?

**Comment by deepub** [comment]
Thanks @meteozond 
Great to hear that others also ran into the same problem. I've re-opened this issue.

**Comment by samveen** [comment]
#102 and #151 are somewhat related to packaging too (or lack thereof)

**Comment by gdubicki** [comment]
I need RPM with mcrouter for Centos 7. I will prepare it anyway but perhaps it has been done already but I haven't found it.

I have seen your repo and tickets @samveen , but it's not yet clear to me what is the current status of it. Can you write us a short status update here?

**Comment by gdubicki** [comment]
Note that I have successfully built mcrouter on Centos 7.3 using https://github.com/gdubicki/mcrouter/blob/master/mcrouter/scripts/install_centos_7.2.sh with only a single hack of forcing installation of `cmake` after I got `file /usr/share/aclocal from install of cmake-3.1.0-1.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64` error. 

(Before that I tried going this path https://github.com/facebook/mcrouter/issues/187 but it resulted in a VERY slow binary, details in that issue.)

**Comment by theonajim** [comment]
@gdubicki I am curious on the reason you get cmake-3.1.0, when I run https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/install_centos_7.2.sh script it installs cmake-2.8.12.2-2.el7 from base repo. See below:

```
 Dependencies Resolved
 
 ================================================================================
  Package                    Arch      Version                  Repository  Size
 ================================================================================
 Installing:
  autoconf                   noarch    2.69-11.el7              base       701 k
  binutils-devel             x86_64    2.25.1-22.base.el7       base       844 k
  bison                      x86_64    2.7-4.el7                base       578 k
  boost-devel                x86_64    1.53.0-26.el7            base       7.0 M
  cmake                      x86_64    2.8.12.2-2.el7           base       7.1 M
  double-conversion-devel    x86_64    2.0.1-3.el7              epel        22 k
  flex                       x86_64    2.5.37-3.el7             base       292 k
  gflags-devel               x86_64    2.1.1-6.el7              epel        29 k
  glog-devel                 x86_64    0.3.3-8.el7              epel        36 k
  jemalloc-devel             x86_64    3.6.0-1.el7              epel        23 k
  libevent-devel             x86_64    2.0.21-4.el7             base        85 k
  libtool                    x86_64    2.4.2-22.el7_3           updates    588 k
  openssl-devel              x86_64    1:1.0.1e-60.el7_3.1      updates    1.2 M
  python-devel               x86_64    2.7.5-48.el7             base       393 k
  ragel                      x86_64    7.0.0.9-2.el7            epel       1.3 M
```


Here is the base repo file:
```
$ cat /etc/yum.repos.d/CentOS-Base.repo 
# CentOS-Base.repo
#
# The mirror system uses the connecting IP address of the client and the
# update status of each mirror to pick mirrors that are updated to and
# geographically close to the client.  You should use this for CentOS updates
# unless you are manually picking other mirrors.
#
# If the mirrorlist= does not work for you, as a fall back you can try the 
# remarked out baseurl= line instead.
#
#

[base]
name=CentOS-$releasever - Base
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
#baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

#released updates 
[updates]
name=CentOS-$releasever - Updates
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra
#baseurl=http://mirror.centos.org/centos/$releasever/updates/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
#baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

#additional packages that extend functionality of existing packages
[centosplus]
name=CentOS-$releasever - Plus
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus&infra=$infra
#baseurl=http://mirror.centos.org/centos/$releasever/centosplus/$basearch/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
```

**Comment by samveen** [comment]
@theonajim Depending on which version of `folly` you're building (if a build of folly is required), the requirement for `CMake` is greater than the dist version of  `2.8.12` (`3.4` to be exact).

@gdubicki Yeah. For us, the performance drop in later versions of `mcrouter` was not worth the new features and bug fixes, so I haven't bothered to update the repo. Please feel free to submit a MR with your updates.

**Comment by gdubicki** [comment]
What performance drop, @samveen ? I haven't found an issue for this.. Can you elaborate please? Perhaps filing it as a ticket would be helpful.

**Comment by samveen** [comment]
@gdubicki I can't really comment (I'm just quoting my team member who actually ran the performance tests: In this case, I was just the `builds guy`).

**Comment by gdubicki** [comment]
Sorry @theonajim , that `cmake-3.1.0` came from our internal yum repo... So no PR from me is necessary, I think.

**Comment by orishu** [comment]
Forked and packaged the latest release for Ubuntu (Xenial amd64), installation instructions [here](https://fburl.com/ujrpfz4b). Let me know if you get a chance to use it, feedback welcome.

**Comment by orishu** [comment]
Mcrouter Ubuntu binary package (amd64) is now available on the main repo https://github.com/facebook/mcrouter

**Comment by ethaniel** [comment]
What about centos6?

**Comment by orishu** [comment]
@ethaniel - unfortunately we don't have plans right now to prepackage in more forms, and also Ubuntu support is based on available personal spare time... sorry
