### ISSUE TITLE
Resource utilization

### ISSUE THREAD

**Issue by galitz** [facebook/mcrouter#133]
Hi.

We're doing some capacity planning prior to a bigger rollout of mcrouter.  My question is:  what is the primary bottleneck?  CPU?  

Is mcrouter a heavy consumer of CPU, RAM or disk?  Let's assume we have 200 nodes running mcrouter with out app co-hosted on those same nodes, connecting to 40 memcache servers with 20G each.

-G

**Comment by pavlo-fb** [comment]
Hi! Well, the bottleneck depends on your hardware and workload. But in general the bottleneck is CPU or network bandwidth. Mcrouter uses disk only to write stats and spool failed deletes - so it shouldn't be a bottleneck. Amount of required RAM highly depends on workload - usually mcrouter uses less than 1GB, but if you have a lot of pending requests (see proxy_reqs_processing and proxy_reqs_waiting [stats](https://github.com/facebook/mcrouter/wiki/Stats-list)) - then it may use a lot of RAM.

All in all, I would suggest to test mcrouter on one node and get precise numbers - should be much simpler than guessing what may happen in your particular case.

**Comment by jmswen** [comment]
Hi @galitz, did @pavlo-fb's response resolve your issue?

**Comment by galitz** [comment]
Yes.. all good.  Thanks.
