### ISSUE TITLE
warmup/migration question

### ISSUE THREAD

**Issue by galitz** [facebook/mcrouter#136]
Hi.

We are planning on migrating an existing memcache cluster to a new one behind mcrouter.  Generally speaking, have folks been doing this kind of migration by replacing their memcache configs on the clients with one pointing to the new mcrouter which has the "prior existing" memcache nodes defined as the cold route?  Or have folks been taking other approaches?

If the former, if the app has a series of memcache servers defined using consistent hashing, is it important that the cold route pool has memcache servers defined in the same order?

Thanks.

**Comment by jmswen** [comment]
> If the former, if the app has a series of memcache servers defined using consistent hashing, is it important that the cold route pool has memcache servers defined in the same order?

In order for this to work, the current consistent hash function must be identical to the one mcrouter uses.  This is unlikely to work.

It sounds like you will need to have the warmup logic in the current application itself: fetch from the cold pool (behind a mcrouter), and on a miss, fetch from the warm pool and subsequently set back to the cold pool.

In the future, once you have a warm pool behind mcrouter, migrations like this can be easily taken care of via a mcrouter config change.

**Comment by jmswen** [comment]
@galitz, closing this issue but please reopen if you have any further questions.
