### ISSUE TITLE
 Failed to reconfigure: json parse error on line 0 near config.json: expected json value

### ISSUE THREAD

**Issue by laamalif** [facebook/mcrouter#137]
version
`27.0.0-master mcrouter`

config.json
`{
  "pools" : {
    "A" : {
      "servers" : [
        "127.0.0.1:11211"
      ]
    }
  },
  "route" : "PoolRoute|A"
}
`
error
I0710 18:25:02.400645  9383 main.cpp:335] ./mcrouter -p 9000 --config /tmp/config.json 
I0710 18:25:02.400756  9383 main.cpp:419] 27.0.0-master mcrouter startup (9383)
I0710 18:25:02.400794  9383 server.cpp:116] Spawning AsyncMcServer
I0710 18:25:02.401696  9383 McrouterInstance.cpp:549] started reconfiguring
FAILURE 1468160702.402063 9383 [libmcrouter.mcrouter.9000] [invalid-config] [mcrouter] McrouterInstance.cpp:564] Failed to reconfigure: json parse error on line 0 near `/tmp/config.json': expected json value`

**Comment by jmswen** [comment]
From `mcrouter --help` regarding the `--config` option:

> Configuration to use. The provided string must be of one of two forms: file:\<path-to-config-file\> OR \<JSON-config-string\>. If provided, this option
>  supersedes the deprecated config-file and config-str options. [default: ""]

`mcrouter -p 9000 --config file:/tmp/config.json` should do the trick.
