### ISSUE TITLE
Prefix routing with keys that have shared components

### ISSUE THREAD

**Issue by srcspider** [facebook/mcrouter#141]
If I were to use the following prefixes `user`, `user_profile`, `user_profile_post` will mcrouter 

- do the right thing and always check keys from longest to shortest
- do I need to be careful how I stick them in the configuration for it to work
- it's undefined behavior; ie. may randomly work or not work

Read https://github.com/facebook/mcrouter/wiki/Prefix-routing-setup but it's unclear, since the examples use distinct prefixes.

**Comment by spalamarchuk** [comment]
@srcspider, mcrouter will always choose the longest prefix match. Thus in your case, if the key was 'user_profile_test', mcrouter would use a config for prefix 'user_profile'.
There's no additional magic required, just follow the wiki that you linked to. Internally we use Trie, so the order in which you list prefixes in config is not important.

I'll update the wiki to mention that mcrouter will choose the longest match.

**Comment by srcspider** [comment]
Thanks.
