### ISSUE TITLE
Thrift installation procedure causes build error

### ISSUE THREAD

**Issue by lukenels** [facebook/mcrouter#147]
Thrift now has [mstch](https://github.com/no1msd/mstch) as a dependency, and the installation script for Thrift fails to install this dependency, which causes a build failure.

I am the author of the commits in Thrift that cause this breakage, and will be responsible for fixing the scripts here to correct the build. I'm opening this issue so that it is known I am aware of the issue and am working on a fix.

**Comment by lukenels** [comment]
Ah it appears this is being fixed by https://github.com/facebook/mcrouter/pull/142.

Thanks @yqzhang !

**Comment by yqzhang** [comment]
You are more than welcome :D
