### ISSUE TITLE
Unexpected result of stats command 

### ISSUE THREAD

**Issue by nguyentranthanh** [facebook/mcrouter#150]
Hello,

We face the problem that PHP7 getStats function (php-memcached 3.0.0b1, libmemcached1.0.18) works failed.

I found the issue that stats command directly to memcached server is work well, but via mcrouter is failed. This issue is caused by mcrouter return it's version and stats information instead of return the information of memcached servers.
## Example:

$ echo "stats all" | nc mcrouter.host 11212
[tnguyen@idlzdstg2alice1.iddc alice]$ echo "stats" | nc localhost 2314
STAT version mcrouter 2.0.0
STAT commandargs -p 2314 /etc/mcrouter/alice/startup.conf
STAT pid 1296
STAT parent_pid 1212
STAT time 1472549998
STAT uptime 667013
STAT num_servers 20
STAT num_servers_new 0
## .........

---

$ echo "stats" | nc cache1.lzd 11314
STAT pid 13679
STAT uptime 12465240
STAT time 1472550039
STAT version 1.4.15
STAT libevent 2.0.21-stable
STAT pointer_size 64
STAT rusage_user 2248.763805
STAT rusage_system 4980.879957
## ........

In libmemcached 1.0.18, it validates the version of memcached, so the string "version mcrouter 2.0.0" is wrong data.

I raise the issue here and have a question.
- How to get statistic of memcached servers by 'stats' command which is called via mcrouter?

This issue familiar with this issue. https://github.com/facebook/mcrouter/issues/143

**Comment by jmswen** [comment]
Hi @nguyentranthanh, mcrouter does not currently provide an easy way of getting statistics from the backing memcached servers.  One possible workaround would be to parse the output of `echo stats servers | nc <mcrouter-host> <mcrouter-port>` and directly send the stats command to those servers.   But, this would take some effort and doesn't provide an easy way of getting stats for, say, a single pool.  Of course, patches are welcome!

Out of curiosity, could you elaborate on what you would like to achieve?  Do you want a client to be able to query stats for all memcached hosts behind mcrouter?  Just a single memcached host?

**Comment by nguyentranthanh** [comment]
Hi @jmswen, Thank you for your answer.

I use `stats` for check the connection and memcached really available for working. It can change to `set` and `get`, but there are 2 calls. Moreover, I use `stats` to get information of memcached for application profilling (limit_maxbytes, bytes,...).

**Comment by jmswen** [comment]
@nguyentranthanh, regarding obtaining information of memcached hosts to do profiling, this seems like something best done outside mcrouter, though in principle we could add a special `stats memcached` subcommand to mcrouter to get the `stats` of all backing memcached servers.  Note that this would probably not work easily with PHP libraries.

Regarding checking connectivity: mcrouter opens connections lazily and closes idle connections, so mcrouter may not be connected to a memcached server under normal operation.  In normal use, if you send a `set` command through mcrouter and if mcrouter is unable to connect to the target destination, you will get a `SERVER_ERROR unavailable` response.  (`get` requests actually just reply `END` by default; if this is undesirable, you may look into turning off the `miss_on_get_error` option.)
