### ISSUE TITLE
Git Tag Does Not Match Release Branch For 0.31.0

### ISSUE THREAD

**Issue by amcrn** [facebook/mcrouter#151]
The commit for `Fix for FailoverWithExptimeRoute Sending TTL on Delete To Gutter` is tagged with 0.31.0: https://github.com/facebook/mcrouter/commit/8fad682e8c15cfbce3d6e2eb90caee584ce5fdbc , but it's not on the `release-31-0` branch: https://github.com/facebook/mcrouter/commits/release-31-0/mcrouter/routes/ModifyExptimeRoute.h

Was this accidental, or are Git Tags for this project not necessarily aligned with the release branches? Thanks!

**Comment by jmswen** [comment]
Hi @amcrn, thank you for reporting this issue.  Indeed, this is not the intended behavior.  We will have this fixed this in the next release.

**Comment by samveen** [comment]
@jmswen If this is fixed , then #102 would be fixed as well.

**Comment by amcrn** [comment]
This was fixed with subsequent releases, so I'm closing the issue.
