### ISSUE TITLE
Install via  ./install_ubuntu_14.04.sh /path/to/dir fails 

### ISSUE THREAD

**Issue by vladzu** [facebook/mcrouter#155]
- autoreconf --install
  configure.ac:25: installing 'build-aux/compile'
  configure.ac:25: installing 'build-aux/config.guess'
  configure.ac:25: installing 'build-aux/config.sub'
  configure.ac:20: installing 'build-aux/install-sh'
  configure.ac:20: installing 'build-aux/missing'
  Makefile.am: installing 'build-aux/depcomp'
  parallel-tests: installing 'build-aux/test-driver'
  - LD_LIBRARY_PATH=/opt/mcrouter/install/lib:
  - LD_RUN_PATH=/opt/mcrouter/install/lib:
  - LDFLAGS='-L/opt/mcrouter/install/lib -ljemalloc '
  - CPPFLAGS='-I/opt/mcrouter/install/include '
  - ./configure --prefix=/opt/mcrouter/install
  - make
    In file included from Compression.cpp:17:0:
    ../../mcrouter/lib/Lz4CompressionCodec.h:41:22: error: ‘LZ4_stream_t’ has not been declared
      void operator()(LZ4_stream_t\* stream) const {
                      ^
    ../../mcrouter/lib/Lz4CompressionCodec.h:48:19: error: ‘LZ4_stream_t’ was not declared in this scope
    std::unique_ptr<LZ4_stream_t, Deleter> lz4Stream_;
                   ^
    ../../mcrouter/lib/Lz4CompressionCodec.h:48:40: error: template argument 1 is invalid
    std::unique_ptr<LZ4_stream_t, Deleter> lz4Stream_;
                                        ^
    ../../mcrouter/lib/Lz4CompressionCodec.h: In member function ‘void facebook::memcache::Lz4CompressionCodec::Deleter::operator()(int_) const’:
    ../../mcrouter/lib/Lz4CompressionCodec.h:42:29: error: ‘LZ4_freeStream’ was not declared in this scope
        LZ4_freeStream(stream);
                             ^
    make[3]: *_\* [libmcrouter_a-Compression.o] Error 1
    make[2]: **\* [all-recursive] Error 1
    make[1]: **\* [all-recursive] Error 1
    make: **\* [all] Error 2
    ---- End output of ./install_ubuntu_14.04.sh /opt/mcrouter ----

Do i need more info to provide? 
latest  Ubuntu 14.04.5 LTS \n \l  with all sec updates

**Comment by vladzu** [comment]
with the latest version installation fails :
./install_ubuntu_14.04.sh /opt/mcrouter -j4


+ make -j4
make  all-recursive
make[1]: Entering directory `/var/opt/mcrouter/mcrouter'
Making all in lib
make[2]: Entering directory `/var/opt/mcrouter/mcrouter/lib'
Making all in .
make[3]: Entering directory `/var/opt/mcrouter/mcrouter/lib'
g++ -DHAVE_CONFIG_H   -I../.. -I/opt/mcrouter/install/include   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -std=gnu++1y -MT libmcrouter_a-Compression.o -MD -MP -MF .deps/libmcrouter_a-Compression.Tpo -c -o libmcrouter_a-Compression.o `test -f 'Compression.cpp' || echo './'`Compression.cpp
g++ -DHAVE_CONFIG_H   -I../.. -I/opt/mcrouter/install/include   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -std=gnu++1y -MT libmcrouter_a-CompressionCodecManager.o -MD -MP -MF .deps/libmcrouter_a-CompressionCodecManager.Tpo -c -o libmcrouter_a-CompressionCodecManager.o `test -f 'CompressionCodecManager.cpp' || echo './'`CompressionCodecManager.cpp
g++ -DHAVE_CONFIG_H   -I../.. -I/opt/mcrouter/install/include   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -std=gnu++1y -MT libmcrouter_a-FailoverErrorsSettings.o -MD -MP -MF .deps/libmcrouter_a-FailoverErrorsSettings.Tpo -c -o libmcrouter_a-FailoverErrorsSettings.o `test -f 'FailoverErrorsSettings.cpp' || echo './'`FailoverErrorsSettings.cpp
g++ -DHAVE_CONFIG_H   -I../.. -I/opt/mcrouter/install/include   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -std=gnu++1y -MT libmcrouter_a-IOBufUtil.o -MD -MP -MF .deps/libmcrouter_a-IOBufUtil.Tpo -c -o libmcrouter_a-IOBufUtil.o `test -f 'IOBufUtil.cpp' || echo './'`IOBufUtil.cpp
In file included from /opt/mcrouter/install/include/folly/FBString.h:55:0,
                 from /opt/mcrouter/install/include/folly/Demangle.h:19,
                 from /opt/mcrouter/install/include/folly/Conv.h:41,
                 from /opt/mcrouter/install/include/folly/Format.h:24,
                 from Compression.cpp:12:
/opt/mcrouter/install/include/folly/Malloc.h:247:29: warning: ‘__returns_nonnull__’ attribute directive ignored [-Wattributes]
     const size_t newCapacity) {
                             ^
In file included from /opt/mcrouter/install/include/folly/FBString.h:55:0,
                 from /opt/mcrouter/install/include/folly/io/IOBuf.h:31,
                 from IOBufUtil.h:15,
                 from IOBufUtil.cpp:10:
/opt/mcrouter/install/include/folly/Malloc.h:247:29: warning: ‘__returns_nonnull__’ attribute directive ignored [-Wattributes]
     const size_t newCapacity) {
                             ^
In file included from /opt/mcrouter/install/include/folly/FBString.h:55:0,
                 from /opt/mcrouter/install/include/folly/Range.h:22,
                 from /opt/mcrouter/install/include/folly/dynamic.h:77,
                 from FailoverErrorsSettings.cpp:14:
/opt/mcrouter/install/include/folly/Malloc.h:247:29: warning: ‘__returns_nonnull__’ attribute directive ignored [-Wattributes]
     const size_t newCapacity) {
                             ^
In file included from /opt/mcrouter/install/include/folly/FBString.h:55:0,
                 from /opt/mcrouter/install/include/folly/Demangle.h:19,
                 from /opt/mcrouter/install/include/folly/Conv.h:41,
                 from /opt/mcrouter/install/include/folly/Exception.h:25,
                 from /opt/mcrouter/install/include/folly/detail/ThreadLocalDetail.h:30,
                 from /opt/mcrouter/install/include/folly/ThreadLocal.h:59,
                 from CompressionCodecManager.h:18,
                 from CompressionCodecManager.cpp:10:
/opt/mcrouter/install/include/folly/Malloc.h:247:29: warning: ‘__returns_nonnull__’ attribute directive ignored [-Wattributes]
     const size_t newCapacity) {
                             ^
In file included from Compression.cpp:17:0:
../../mcrouter/lib/Lz4CompressionCodec.h:41:22: error: ‘LZ4_stream_t’ has not been declared
      void operator()(LZ4_stream_t* stream) const {
                      ^
../../mcrouter/lib/Lz4CompressionCodec.h:48:19: error: ‘LZ4_stream_t’ was not declared in this scope
   std::unique_ptr<LZ4_stream_t, Deleter> lz4Stream_;
                   ^
../../mcrouter/lib/Lz4CompressionCodec.h:48:40: error: template argument 1 is invalid
   std::unique_ptr<LZ4_stream_t, Deleter> lz4Stream_;
                                        ^
../../mcrouter/lib/Lz4CompressionCodec.h: In member function ‘void facebook::memcache::Lz4CompressionCodec::Deleter::operator()(int*) const’:
../../mcrouter/lib/Lz4CompressionCodec.h:42:29: error: ‘LZ4_freeStream’ was not declared in this scope
        LZ4_freeStream(stream);
                             ^
mv -f .deps/libmcrouter_a-IOBufUtil.Tpo .deps/libmcrouter_a-IOBufUtil.Po
g++ -DHAVE_CONFIG_H   -I../.. -I/opt/mcrouter/install/include   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -std=gnu++1y -MT libmcrouter_a-IovecCursor.o -MD -MP -MF .deps/libmcrouter_a-IovecCursor.Tpo -c -o libmcrouter_a-IovecCursor.o `test -f 'IovecCursor.cpp' || echo './'`IovecCursor.cpp
make[3]: *** [libmcrouter_a-Compression.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/libmcrouter_a-IovecCursor.Tpo .deps/libmcrouter_a-IovecCursor.Po
mv -f .deps/libmcrouter_a-FailoverErrorsSettings.Tpo .deps/libmcrouter_a-FailoverErrorsSettings.Po
mv -f .deps/libmcrouter_a-CompressionCodecManager.Tpo .deps/libmcrouter_a-CompressionCodecManager.Po
make[3]: Leaving directory `/var/opt/mcrouter/mcrouter/lib'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/var/opt/mcrouter/mcrouter/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/opt/mcrouter/mcrouter'
make: *** [all] Error 2

**Comment by AaronSchulz** [comment]
I've ran into the same problem using Ubuntu subsystem (folly/wangle all went fine, save for the usual surprise dependencies).

**Comment by jmswen** [comment]
@vladzu, the compilation error indicates you have a version of the `lz4` library that is too old.  The declaration for `LZ4_stream_t` type should be declared here: https://github.com/facebook/mcrouter/blob/master/mcrouter/lib/Lz4CompressionCodec.h#L19.  Which version of `lz4` do you have installed?

FWIW, this issue https://github.com/facebook/mcrouter/issues/149 is related.  The resolution there may help you.
