### ISSUE TITLE
mcrouter fails with error mcrouter: lib/network/McAsciiParser.rl:1107: facebook::memcache::McAsciiParserBase::State facebook::memcache::McServerAsciiParser::consume(folly::IOBuf&): Assertion `state_ != State::ERROR' failed.

### ISSUE THREAD

**Issue by vladzu** [facebook/mcrouter#156]
mcrouter -V
31.0.0-master mcrouter
/usr/local/bin/mcrouter --port 11211 --config-file /etc/mcrouter/mcrouter.json --async-dir /var/spool/mcrouter --log-path /var/log/mcrouter/mcrouter.log --pid-file /var/run/mcrouter/mcrouter.pid --stats-root /var/mcrouter/stats

config : 
{
  "pools": {
    "nodes_workload1_warm": {
      "servers": [
        "10.231.4.118:11211"
      ]
    },
    "nodes_workload1_cold": {
      "servers": [
        "10.231.4.119:11211"
      ]
    },
    "nodes_workload2_warm": {
      "servers": [
        "10.231.4.120:11211"
      ]
    },
    "nodes_workload2_cold": {
      "servers": [
        "10.231.4.121:11211"
      ]
    },
    "nodes_workload3_warm": {
      "servers": [
        "10.231.4.122:11211"
      ]
    },
    "nodes_workload3_cold": {
      "servers": [
        "10.231.4.123:11211"
      ]
    },
    "nodes_workload4_cold": {
      "servers": [
        "10.231.4.125:11211"
      ]
    },
    "nodes_workload4_warm": {
      "servers": [
        "10.231.4.124:11211"
      ]
    }
  },
  "route": {
    "type": "PrefixSelectorRoute",
    "policies": {
      "0": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload1_cold",
        "warm": "PoolRoute|nodes_workload1_warm"
      },
      "1": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload1_cold",
        "warm": "PoolRoute|nodes_workload1_warm"
      },
      "2": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload1_cold",
        "warm": "PoolRoute|nodes_workload1_warm"
      },
      "3": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload1_cold",
        "warm": "PoolRoute|nodes_workload1_warm"
      },
      "4": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload2_cold",
        "warm": "PoolRoute|nodes_workload2_warm"
      },
      "5": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload2_cold",
        "warm": "PoolRoute|nodes_workload2_warm"
      },
      "6": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload2_cold",
        "warm": "PoolRoute|nodes_workload2_warm"
      },
      "7": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload2_cold",
        "warm": "PoolRoute|nodes_workload2_warm"
      },
      "8": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload3_cold",
        "warm": "PoolRoute|nodes_workload3_warm"
      },
      "9": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload3_cold",
        "warm": "PoolRoute|nodes_workload3_warm"
      },
      "a": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload3_cold",
        "warm": "PoolRoute|nodes_workload3_warm"
      },
      "b": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload3_cold",
        "warm": "PoolRoute|nodes_workload3_warm"
      },
      "c": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload4_cold",
        "warm": "PoolRoute|nodes_workload4_warm"
      },
      "d": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload4_cold",
        "warm": "PoolRoute|nodes_workload4_warm"
      },
      "e": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload4_cold",
        "warm": "PoolRoute|nodes_workload4_warm"
      },
      "f": {
        "type": "WarmUpRoute",
        "cold": "PoolRoute|nodes_workload4_cold",
        "warm": "PoolRoute|nodes_workload4_warm"
      }
    }
  }
}

mcrouter: lib/network/McAsciiParser.rl:1107: facebook::memcache::McAsciiParserBase::State facebook::memcache::McServerAsciiParser::consume(folly::IOBuf&): Assertion `state_ != State::ERROR' failed.

**Comment by omar01** [comment]
Me too I am having this with mcrouter version 32.0

**Comment by spalamarchuk** [comment]
@vladzu, @omar01, Thanks for reporting the issue!

I managed to find the bug in our code and have a repro for this. I have a diff in review that will likely get committed and pushed only next week due to holidays.

**Comment by glamtechie** [comment]
Closing this since it is solved.
