### ISSUE TITLE
Install script fails

### ISSUE THREAD

**Issue by jkpindahbc** [facebook/mcrouter#158]
Install script install_ubuntu_14.04.sh fails with error message 

> ./order_ubuntu-14.04/10_folly: line 1: ../recipes/folly.sh: No such file or directory

The folders and files exist so I am not sure why it fails here

**Comment by jmswen** [comment]
Hi @jkpindahbc, I was unable to reproduce this issue when installing on an Ubuntu 14.04 VM.  I got a successful build when running

    rm -rf /home/$USER/mcrouter-install
    cd /tmp && git clone https://github.com/facebook/mcrouter
    ./mcrouter/mcrouter/scripts/install_ubuntu_14.04.sh /home/$USER/mcrouter-install

Could you provide more details on your setup?  Are you on Ubuntu 14.04?  What are the exact commands you ran for the install?
