### ISSUE TITLE
Folly and other dependencies should have their version locked in mcrouter

### ISSUE THREAD

**Issue by srcspider** [facebook/mcrouter#159]
The install scripts for mcrouter (besides tacking ages--because deps need to be compiled too), are also grabbing from what I can tell the master version of all the dependencies. So if say folly suddenly changes and mcrouter is behind or, as was the case for me, you are trying to compile a specific known to work version (ie. that compiles and is also known api), then suddenly it all breaks.

In my case this commit 4f728e1b11f11f982ff9b28c5b810ace0c80381a worked then broke. This is completely undesirable behavior. From what I see 90% of the time compiling mcrouter is actually just compiling all the dependencies, if you checkout a working commit today outside of oddities in the dependencies that commit should grab the same dependency version/commit every time.

Haven't tried to compile but the release zip/tar.gz files also seem to be missing the dependency pinning files from just looking at them... assuming I'm looking in the right place.

Also I understand the fix is to add the random FOLLY_COMMIT files (among others) myself in there, but that doesn't solve the issue that if you say had issues with the latest release (whatever they may be) you can't easily rollback... you have to checkout mcrouter then using trial and error (for hours) figure out based on commit timestamps and whatnot which version of the dependencies that was meant to be using. 

This is just unnecessarily painful.

**Comment by spalamarchuk** [comment]
Hi @srcspider, our release branches already use pinned versions for dependencies. If you want to build from master, you can look at history of travis-ci builds (https://travis-ci.org/facebook/mcrouter/builds) and find necessary commits of folly and wangle in logs (you can look for "No FOLLY_COMMIT file, using folly HEAD=" and "No WANGLE_COMMIT file, using wangle HEAD="). Unfortunately, this data cannot be easily automatically generated for commits in master branch.

Release versions are the once that we tested internally at Facebook for several days in production and we're sure that they don't have issues, thus I would recommend you to use those release versions.

**Comment by srcspider** [comment]
@spalamarchuk thanks
