### ISSUE TITLE
Mcrouter crash when key contains byte like 160, 161, 162...

### ISSUE THREAD

**Issue by panchenji** [facebook/mcrouter#161]
We are using v20 release version and doing some tests on unicode support in the key in mcrouter. We found that when we sent keys contains byte like 160, 161, 162. The mcrouter will crash. We think the problem is due to this commit: https://github.com/facebook/mcrouter/commit/0fdc0b6a36be, since the issue is gone after we reverted this commit. 

By the way, according to https://github.com/facebook/mcrouter/wiki/Key-syntax, "A memcached key is typically a short (mcrouter limit is 250 characters) ASCII string which does not contain any whitespace or control characters." And according to https://en.wikipedia.org/wiki/Control_character, byte like 160 is not a control character.

**Comment by jmswen** [comment]
@panchenji, this issue should be resolved by https://github.com/facebook/mcrouter/commit/8b1689311383d6fee334b1e8e7db20170d3b0966.

**Comment by panchenji** [comment]
@jmswen Thanks for the reply. I did some basic tests and it works.
