### ISSUE TITLE
Error Fiber.cpp:158 Max stack usage: 7760

### ISSUE THREAD

**Issue by vldadsniper** [facebook/mcrouter#163]
Hi! Every second my mcrouter gives the message in error.log:
vld@vldcorp:/var/log$ tail mcrouter.error.log
I1115 18:58:15.633805 26283 Fiber.cpp:158] Max stack usage: 7296
What is this error? How to fix it?

**Comment by jmswen** [comment]
Hi @vldadsniper, this is just a useful piece of debugging information (`INFO`-level logging in glog), not an error.  By default, mcrouter records the `folly::fibers` high-watermark stack size every 100000 fibers used.  This logging is helpful in determining good fiber stack sizes for your program.  The message you see is printed during this periodic recording: https://github.com/facebook/folly/blob/4450b4acfcc29ebce843c89fa7cd5c9c80b7eee1/folly/fibers/Fiber.cpp#L158.  Note that this message is only printed if your verbosity level is at least `-v 3`, so you may wish to reduce verbosity.

**Comment by vldadsniper** [comment]
@jmswen wow!) big thx4help) i love you dude!
