### ISSUE TITLE
doesn't behave very well if one of the memcached hosts are down

### ISSUE THREAD

**Issue by vsacheti** [facebook/mcrouter#164]
Hello, I am newbie to `mcrouter`, so maybe I am missing some configuration param here,

I was trying to play around to check what happens if one of the memcached host is down.

Here is my very simple config
```
cat config.json 
 {
   "pools": {
      "A": {
         "servers": [
           "localhost:11213",
           "localhost:11211"
         ]
      }
   },
   "route":"PoolRoute|A" 
 }

```

I have killed the memcached on one of the above ports deliberately.

now when I do this
```
telnet localhost 5000
Trying ::1...
Connected to localhost.
Escape character is '^]'.
get mykey
END
set mykey 0 60 5
val1
STORED
get mykey
VALUE mykey 0 5
val1
END
set mykey1 0 5
CLIENT_ERROR malformed request
CLIENT_ERROR malformed request
Connection closed by foreign host.
[vsacheti@fivesurvive memcachetestapp]$ 
```
I get this `CLIENT_ERROR` although the set command was correct.

I am running `mcrouter` with following option `-t 30000 --timeouts-until-tko=3`. It behaves the same way with just running with default options.

It complains only with `set`.

I was atleast expecting that it wont close the connection.

Any help will be really appreciated.

**Comment by jmswen** [comment]
Hi @vsacheti, I am not sure what you mean by 
> I was atleast expecting that it wont close the connection.

but it sounds like you were expecting all requests to go to the server that is up when the other is down.  Your configuration defines a single sharded pool with 2 shards (see https://github.com/facebook/mcrouter/wiki/Sharded-pools-setup).  There is no failover in this setup: a given key will always hash to the same server.

If you want to failover to host 2 when host 1 is down, you can do something like this:
```
{
  "pools": {
    "primary": { 
      "servers": [ "localhost:11111" ] 
    },
    "backup": { 
      "servers": [ "localhost:11112" ] 
    }
  },
  "route": {
    "type": "FailoverRoute",
    "children": [ "PoolRoute|primary", "PoolRoute|backup" ]
  } 
}
```

I hope this answers your question.  You can read more about failover here: https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#failoverroute More about mcrouter configuration in general here: https://github.com/facebook/mcrouter/wiki/Config-Files

**Comment by spalamarchuk** [comment]
@vsacheti, note, that the last set request is indeed malformed.
According to [memcached spec](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L129) it should be "set <key> <flags> <exptime> <bytes>\r\n" and in your case you don't have one of the arguments in your last set request (I presume you missed "<exptime>" field).

Connection is closed because mcrouter received the data that doesn't conform with the spec, so the safest way is to close the client connection.

**Comment by vsacheti** [comment]
Thanks for your response. I will checkout the failover route. Thanks.
Yeah I just noticed the the `set` was indeed malformed. On the correct set, it gives
`SERVER_ERROR unavailable`, which I guess is the correct response.

You can close this issue.
