### ISSUE TITLE
Build on Ubuntu fails

### ISSUE THREAD

**Issue by epgrvp** [facebook/mcrouter#165]
Hi,

when using the following `Dockerfile`

`FROM ubuntu:14.04`
`ENV MCROUTER_REPO  https://github.com/facebook/mcrouter.git`
`ENV MCROUTER_DIR   /usr/local/mcrouter`

`# Start by turning on interactive commands`
`# The norm is to pass this when making apt-* calls, but since the mcrouter install script`
`# has apt-* calls I can't modify, we need to set this globally.`
`ENV DEBIAN_FRONTEND noninteractive`

`# Update, install tools, clone repo, install mcrouter, link it up, remove build tools, cleanup`
`RUN echo "-- Updating Ubuntu ------" && apt-get update && apt-get -y dist-upgrade && \`
`    echo "-- Grabbing git ---------" && apt-get -y install git pkgconf && \`
`    echo "-- Making install dir ---" && mkdir -p $MCROUTER_DIR && \`
`    echo "-- Cloning repo ---------" && git clone $MCROUTER_REPO $MCROUTER_DIR/repo && \`
`    echo "-- Installing mcrouter --" && $MCROUTER_DIR/repo/mcrouter/scripts/install_ubuntu_14.04.sh $MCROUTER_DIR && \`
`    echo "-- Installing symlink ---" && ln -s $MCROUTER_DIR/install/bin/mcrouter /usr/local/bin/mcrouter && \`
`    echo "-- Cleanup: script ------" && $MCROUTER_DIR/repo/mcrouter/scripts/clean_ubuntu_14.04.sh $MCROUTER_DIR && \`
`    echo "-- Cleanup: rm ----------" && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*`

`# And now we set the frontend back to the default`
`ENV DEBIAN_FRONTEND newt`

`CMD ["mcrouter", "--help"]`

(from https://hub.docker.com/r/jmck/mcrouter-docker/~/dockerfile/, slightly modified)

I get a linking error:

`/usr/local/mcrouter/install/lib/libfolly.so: undefined reference to 'folly::symbolizer::installFatalSignalHandler()'`
`/usr/local/mcrouter/install/lib/libfolly.so: undefined reference to 'folly::symbolizer::installFatalSignalCallbacks()'`

What am I missing?

**Comment by jmswen** [comment]
Hi @epgrvp, I am sorry about this bad experience.  The error you are seeing is due to commit https://github.com/facebook/folly/commit/efd4e281e629f29cc198c416854031e0eaf6eca2 in folly, which has broken mcrouter's build from master.  Until this is fixed, one workaround is to modify the Dockerfile manually and add a line to check out one of mcrouter's stable branches, e.g.,
```
...
git clone $MCROUTER_REPO $MCROUTER_DIR/repo && \
git -C $MCROUTER_DIR/repo checkout release-34-0 && \
$MCROUTER_DIR/repo/mcrouter/scripts/install_ubuntu_14.04.sh $MCROUTER_DIR && \
...
```

This should work because our release branches are pinned to commits in folly that we have tested the build with, not master.

**Comment by jmswen** [comment]
This issue should now be resolved by https://github.com/facebook/folly/commit/6d58adc5225a4662faf5f6343069dec626fdc84d.  The original Dockerfile should work without modification.

**Comment by epgrvp** [comment]
Yes, works perfectly, thanks!
