### ISSUE TITLE
ProxyDestination.cpp:433

### ISSUE THREAD

**Issue by vldadsniper** [facebook/mcrouter#170]
Hello. Help me pls. what does it mean

Dec 19 21:28:54 f-nod5 mcrouter-34-0[26129]: I1219 21:28:54.210981 26139 ProxyDestination.cpp:433] f-memc1.local:11411 (A) marked soft TKO. Total hard TKOs: 0; soft TKOs: 2. Reply: mc_res_timeout
Dec 19 21:29:05 f-nod5 mcrouter-34-0[26129]: I1219 21:29:05.522377 26137 ProxyDestination.cpp:433] f-memc2.local:11311 (B) unmarked TKO. Total hard TKOs: 0; soft TKOs: 1. Reply: mc_res_ok
Dec 19 21:29:08 f-nod5 mcrouter-34-0[26129]: I1219 21:29:08.631701 26139 ProxyDestination.cpp:433] f-memc1.local:11411 (A) unmarked TKO. Total hard TKOs: 0; soft TKOs: 0. Reply: mc_res_ok
Dec 19 21:29:10 f-nod5 mcrouter-34-0[26129]: I1219 21:29:10.651903 26144 ProxyDestination.cpp:433] f-memc1.local:11411 (A) marked soft TKO. Total hard TKOs: 0; soft TKOs: 1. Reply: mc_res_timeout
Dec 19 21:29:12 f-nod5 mcrouter-34-0[26129]: I1219 21:29:12.687691 26153 ProxyDestination.cpp:433] f-memc2.local:11311 (B) marked soft TKO. Total hard TKOs: 0; soft TKOs: 2. Reply: mc_res_timeout
Dec 19 21:29:22 f-nod5 mcrouter-34-0[26129]: I1219 21:29:22.318977 26144 ProxyDestination.cpp:433] f-memc1.local:11411 (A) unmarked TKO. Total hard TKOs: 0; soft TKOs: 1. Reply: mc_res_ok
Dec 19 21:29:24 f-nod5 mcrouter-34-0[26129]: I1219 21:29:24.638782 26153 ProxyDestination.cpp:433] f-memc2.local:11311 (B) unmarked TKO. Total hard TKOs: 0; soft TKOs: 0. Reply: mc_res_ok
Dec 19 21:29:24 f-nod5 mcrouter-34-0[26129]: I1219 21:29:24.638782 26153 ProxyDestination.cpp:433] f-memc2.local:11311 (B) unmarked TKO. Total hard TKOs: 0; soft TKOs: 0. Reply: mc_res_ok

**Comment by spalamarchuk** [comment]
Hi @vldadsniper, mcrouter monitors healthiness of destinations based on amount of errors that it receives from that destination. Here's more description about that:
https://github.com/facebook/mcrouter/wiki/Features#health-checkauto-failover

These log lines show the migration of host between those states. I.e. normal->soft_tko->normal.

**Comment by spalamarchuk** [comment]
Closing the issue, feel free to reopen if you need more help.
