### ISSUE TITLE
Failing one node in replicated pool makes gets commands not functioning

### ISSUE THREAD

**Issue by vladzu** [facebook/mcrouter#172]
We have put together our configuration as described in 
https://github.com/facebook/mcrouter/wiki/Replicated-pools-setup
and 
https://github.com/facebook/mcrouter/wiki/Prefix-routing-setup

So its hybrid of replication and prefix routing (nothing illegal). Pretty scalable solution as we have all memcached entries in hash format.

mcr1nv:~# cat /etc/mcrouter/mcrouter.json
{
  "pools": {
    "nodes_workload1": {
      "servers": [
        "172.21.76.188:11211",
        "172.21.79.32:11211"
      ]
    },
    "nodes_workload2": {
      "servers": [
        "172.21.77.60:11211",
        "172.21.79.252:11211"
      ]
    },
    "nodes_workload3": {
      "servers": [
        "172.21.77.175:11211",
        "172.21.79.220:11211"
      ]
    },
    "nodes_workload4": {
      "servers": [
        "172.21.77.4:11211",
        "172.21.78.119:11211"
      ]
    }
  },
  "route": {
    "type": "PrefixSelectorRoute",
    "policies": {
      "0": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload1",
          "delete": "AllSyncRoute|Pool|nodes_workload1",
          "get": "LatestRoute|Pool|nodes_workload1",
          "set": "AllSyncRoute|Pool|nodes_workload1"
        }
      },
      "1": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload1",
          "delete": "AllSyncRoute|Pool|nodes_workload1",
          "get": "LatestRoute|Pool|nodes_workload1",
          "set": "AllSyncRoute|Pool|nodes_workload1"
        }
      },
      "2": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload1",
          "delete": "AllSyncRoute|Pool|nodes_workload1",
          "get": "LatestRoute|Pool|nodes_workload1",
          "set": "AllSyncRoute|Pool|nodes_workload1"
        }
      },
      "3": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload1",
          "delete": "AllSyncRoute|Pool|nodes_workload1",
          "get": "LatestRoute|Pool|nodes_workload1",
          "set": "AllSyncRoute|Pool|nodes_workload1"
        }
      },
      "4": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload2",
          "delete": "AllSyncRoute|Pool|nodes_workload2",
          "get": "LatestRoute|Pool|nodes_workload2",
          "set": "AllSyncRoute|Pool|nodes_workload2"
        }
      },
      "5": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload2",
          "delete": "AllSyncRoute|Pool|nodes_workload2",
          "get": "LatestRoute|Pool|nodes_workload2",
          "set": "AllSyncRoute|Pool|nodes_workload2"
        }
      },
      "6": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload2",
          "delete": "AllSyncRoute|Pool|nodes_workload2",
          "get": "LatestRoute|Pool|nodes_workload2",
          "set": "AllSyncRoute|Pool|nodes_workload2"
        }
      },
      "7": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload2",
          "delete": "AllSyncRoute|Pool|nodes_workload2",
          "get": "LatestRoute|Pool|nodes_workload2",
          "set": "AllSyncRoute|Pool|nodes_workload2"
        }
      },
      "8": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload3",
          "delete": "AllSyncRoute|Pool|nodes_workload3",
          "get": "LatestRoute|Pool|nodes_workload3",
          "set": "AllSyncRoute|Pool|nodes_workload3"
        }
      },
      "9": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload3",
          "delete": "AllSyncRoute|Pool|nodes_workload3",
          "get": "LatestRoute|Pool|nodes_workload3",
          "set": "AllSyncRoute|Pool|nodes_workload3"
        }
      },
      "a": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload3",
          "delete": "AllSyncRoute|Pool|nodes_workload3",
          "get": "LatestRoute|Pool|nodes_workload3",
          "set": "AllSyncRoute|Pool|nodes_workload3"
        }
      },
      "b": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload3",
          "delete": "AllSyncRoute|Pool|nodes_workload3",
          "get": "LatestRoute|Pool|nodes_workload3",
          "set": "AllSyncRoute|Pool|nodes_workload3"
        }
      },
      "c": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload4",
          "delete": "AllSyncRoute|Pool|nodes_workload4",
          "get": "LatestRoute|Pool|nodes_workload4",
          "set": "AllSyncRoute|Pool|nodes_workload4"
        }
      },
      "d": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload4",
          "delete": "AllSyncRoute|Pool|nodes_workload4",
          "get": "LatestRoute|Pool|nodes_workload4",
          "set": "AllSyncRoute|Pool|nodes_workload4"
        }
      },
      "e": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload4",
          "delete": "AllSyncRoute|Pool|nodes_workload4",
          "get": "LatestRoute|Pool|nodes_workload4",
          "set": "AllSyncRoute|Pool|nodes_workload4"
        }
      },
      "f": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|nodes_workload4",
          "delete": "AllSyncRoute|Pool|nodes_workload4",
          "get": "LatestRoute|Pool|nodes_workload4",
          "set": "AllSyncRoute|Pool|nodes_workload4"
        }
      }
    }
  }
}

get __mcrouter__.config
VALUE __mcrouter__.config 0 30
ERROR: unknown command: config
END
get __mcrouter__.options
VALUE __mcrouter__.options 0 2106
service_name mcrouter
router_name mcrouter
flavor_name /var/run/mcrouter/mcrouter.pid
asynclog_disable 0
async_spool /var/spool/mcrouter
use_asynclog_version2 0
num_proxies 1
client_queue_size 1024
client_queue_no_notify_rate 0
client_queue_wait_threshold_us 0
big_value_split_threshold 0
big_value_batch_size 10
fibers_max_pool_size 500000
fibers_stack_size 24576
fibers_record_stack_size_every 100000
fibers_use_guard_pages 1
runtime_vars_file
file_observer_poll_period_ms 100
file_observer_sleep_before_update_ms 1000
fibers_pool_resize_period_ms 60000
keepalive_cnt 0
keepalive_interval_s 60
keepalive_idle_s 300
reset_inactive_connection_interval 60000
tcp_rto_min -1
target_max_inflight_requests 0
target_max_pending_requests 100000
target_max_shadow_requests 1000
no_network 0
proxy_max_inflight_requests 0
proxy_max_throttled_requests 0
pem_cert_path
pem_key_path
pem_ca_path
enable_qos 0
default_qos_class 0
default_qos_path 0
ssl_connection_cache 0
enable_compression 0
constantly_reload_configs 0
disable_reload_configs 0
config
config_file /etc/mcrouter/mcrouter.json
config_str
default_route /././
miss_on_get_errors 1
group_remote_errors 0
send_invalid_route_to_default 0
enable_flush_cmd 0
reconfiguration_delay_ms 1000
config_params
disable_tko_tracking 0
probe_delay_initial_ms 10000
probe_delay_max_ms 60000
failures_until_tko 3
maximum_soft_tkos 40
allow_only_gets 0
server_timeout_ms 1000
cross_region_timeout_ms 0
cross_cluster_timeout_ms 0
within_cluster_timeout_ms 0
waiting_request_timeout_ms 0
jemalloc_nodump_buffers 0
stats_root /var/mcrouter/stats
debug_fifo_root
stats_logging_interval 10000
logging_rtt_outlier_threshold_us 0
stats_async_queue_length 50
enable_failure_logging 1
cpu_cycles 0
test_mode 0
enable_logging_route 0
collect_rxmit_stats_every_hz 0
asynclog_port_override 0
log_file /var/log/mcrouter/mcrouter.log
ports 11211
ssl_ports
listen_sock_fd -1
unix_domain_sock
max_conns 0
tcp_listen_backlog 128
max_client_outstanding_reqs 34133
requests_per_read 0
retain_source_ip 0
postprocess_logging_route 0
enable_server_compression 0
client_timeout_ms 1000
END

mcrouter -V
31.0.0-master mcrouter

Service is running via:
/usr/local/bin/mcrouter --port 11211 --config-file /etc/mcrouter/mcrouter.json --async-dir /var/spool/mcrouter --log-path /var/log/mcrouter/mcrouter.log --pid-file /var/run/mcrouter/mcrouter.pid --stats-root /var/mcrouter/stats --num-proxies 1 --fibers-max-pool-size 500000  --debug-fifo-root  --disable-miss-on-get-errors

in case one of memcached is down i see in logs:
I0110 15:48:02.662447 16279 AsyncSocket.cpp:1689] AsyncSocket::handleConnect(this=0x7fe92e5d7480, fd=35 host=172.21.76.188:11211) exception: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
I0110 15:48:02.662518 16279 ProxyDestination.cpp:394] 172.21.76.188:11211 (nodes_workload1) marked hard TKO. Total hard TKOs: 1; soft TKOs: 0. Reply: mc_res_connect_error

So one node is marked as hard TKO and should be ignored (sounds logic) but its not.  mcrouter is then does not functioning and mcrouter-memcached gets unusable.

**Comment by jmswen** [comment]
Hi @vladzu, this log line merely indicates that mcrouter cannot send to the down server and will mark it as hard TKO, and is not indicative any problem with failover in `LatestRoute`.
