### ISSUE TITLE
Nested Routing Options

### ISSUE THREAD

**Issue by atayarani** [facebook/mcrouter#177]
I'm trying to figure out how to create a config that will allow us to use the PrefixSelectorRoute with automatic failover to a secondary pool in case the primary one is down.  Starting from the documented example, we'd like to have something like this, but where workload1 and workload2 a failover pair.

```
{
   "pools": {
     "workload1": { "servers": [ /* list of cache hosts for workload1 */ ] },
     "workload2": { "servers": [ /* list of cache hosts for workload2 */ ] },
     "workload3": { "servers": [ /* list of cache hosts for workload3 */ ] },
     "common_cache": { "servers": [ /* list of cache hosts for common use */ ] }
   },
   "route": {
     "type": "PrefixSelectorRoute",
     "policies": {
       "a": "PoolRoute|workload1",
       "b": "PoolRoute|workload2",
       "ab": "PoolRoute|workload3"
     },
     "wildcard": "PoolRoute|common_cache"
   }
 }
```
I've searched through the documentation, but can't find a starting point for this type of routing. Thanks in advance.

**Comment by jmswen** [comment]
Hi @atayarani, if I understand what you mean by "failover pair", you'd like any failed requests to `workload1` to failover to `workload2`, and vice versa.  The following config achieves that:
```
{
  "macros": {
    "createFailoverPair": {
      "type": "macroDef",
      "params": [ "primary", "secondary" ],
      "result": {
        "type": "FailoverRoute",
        "children": [ "PoolRoute|%primary%", "PoolRoute|%secondary%" ]
      }
    }
  },
  "pools": {
    "workload1": { "servers": [ /* list of cache hosts for workload1 */ ] },
    "workload2": { "servers": [ /* list of cache hosts for workload2 */ ] },
    "workload3": { "servers": [ /* list of cache hosts for workload3 */ ] },
    "common_cache": { "servers": [ /* list of cache hosts for common use */ ] }
  },
  "route": {
    "type": "PrefixSelectorRoute",
    "policies": {
      "a": "@createFailoverPair(workload1, workload2)",
      "b": "@createFailoverPair(workload2, workload1)",
      "ab": "PoolRoute|workload3"
    },
    "wildcard": "PoolRoute|common_cache"
  }
}
```

Hope this helps.

**Comment by atayarani** [comment]
That was very helpful, and I think gets me much closer to the solution.  As an added nice-to-have, is it possible to have replication as well, such that when I failover from `workload1` to `workload2`, I don't have to worry about repopulating the "new" cache?
