### ISSUE TITLE
Is there a release notes?

### ISSUE THREAD

**Issue by tokuhirom** [facebook/mcrouter#178]
I want to read the release notes for each version update.
If there's a release notes like memcached, users can upgrade mcrouter easily.
ref. https://github.com/memcached/memcached/wiki/ReleaseNotes

**Comment by andreazevedo** [comment]
We used to post release notes on our facebook group. We stopped doing that as it wasn't being too useful.
That being said, I think we can resume this practice. We can have a wiki page that we post release notes.
