### ISSUE TITLE
Mcrotuer will no longer be supported on ubuntu 12

### ISSUE THREAD

**Issue by andreazevedo** [facebook/mcrouter#179]
We are planning on stop supporting ubuntu 12.
Before doing that though, we want to know if this is going to be a problem to you.
Please comment here if you still need support for ubuntu 12.

**Comment by bmorton** [comment]
We currently still use mcrouter on 12.04, but have plans to get off in the next couple months.  Currently, new versions of mcrouter aren't building under 12.04 anyway for us.
