### ISSUE TITLE
Retrieve key routing when key has comma

### ISSUE THREAD

**Issue by bmorton** [facebook/mcrouter#181]
We use this command to figure out where a key is going to route:

```
$ echo -e 'get __mcrouter__.route(gets,mykeyname)\r' | nc localhost 11211
```

We recently discovered that some of our keys have commas in them so when we use the command like such, we get an error:
```
$ echo -e 'get __mcrouter__.route(gets,my,key)\r' | nc localhost 11211
VALUE __mcrouter__.route(gets,my,key) 0 29
ERROR: route: 2 args expected
END
```

Are we doing something wrong, is this a bug, or is this something that's not supported?

**Comment by jmswen** [comment]
Fixed by https://github.com/facebook/mcrouter/commit/1d62d8f8230aed040fa454203157a9135c53a6e0.
