### ISSUE TITLE
Behavior for ModifyExptimeRoute on incr, decr, or get-like Commands Unclear

### ISSUE THREAD

**Issue by amcrn** [facebook/mcrouter#183]
**Summary**

See https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#modifyexptimeroute

`ModifyExptimeRoute` when used via `OperationSelectorRoute` for `incr`, `decr`, `get`, `gets`, & `delete` is effectively a no-op. This behavior is not clear from the existing documentation:

> Modifies exptime (TTL) for all requests.
>
> Properties:
> 
> * target: child route handle.
> * exptime (int)
>   New TTL (in seconds) for requests.
> * action (optional, default is set) Valid options: set or min. If action is set, always uses new exptime. If action is min, uses new exptime only if it's lower than one specified in request.

Note the "all requests" line.

A user of mcrouter might assume that `ModifyExptimeRoute` fires an async `touch` command with the desired `exptime` after an `incr`/`decr`/`get`/`gets`, which it does not.

**Options**

Either:

1. Treat the use of `ModifyExptimeRoute` as a configuration error if used for `incr`, `decr`, `get`, `gets`, and/or `delete`.
2. Update the documentation to include this behavior/quirk
3. Enhance mcrouter to send an async `touch` with the desired `exptime` after the `incr`, `decr`, `get`, or `gets` command.
4. Other?

(3) doesn't seem useful, so I'd suggest either (1) or (2). Thoughts?

**Comment by stuclar** [comment]
Updated wiki: https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles
