### ISSUE TITLE
Mcrouter - Folly - Wangle versions (commits)

### ISSUE THREAD

**Issue by Dejfik** [facebook/mcrouter#188]
Hi, 
as someone wrote here https://github.com/facebook/mcrouter/issues/187 I laso have problems selecting the right combinations of mcrouter folly and wangle. (by versions i mean commits -> FOLLY_COMMIT, WANGLE_COMMIT). I tried to use the combination from issue 187. Than i ran into other problem described in issue  https://github.com/facebook/mcrouter/issues/149 . But even as i tried to install llz4 and add it as TiagoTT suggested, I still ended up with error leading me into dead end.

---

_libtool: link: g++ -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -std=gnu++1y -o mock_mc_server test/mock_mc_server-MockMc.o test/mock_mc_server-MockMcServer.o -pthread  -L/usr/local/sbin/mcrouter/install/lib -ljemalloc ../../lib/libmcrouter.a -lwangle /usr/local/sbin/mcrouter/install/lib/libfolly.so -ldouble-conversion -lz -llz4 -lssl -lcrypto -levent -lgflags -lglog -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_filesystem -lboost_program_options -lboost_system -lboost_regex -lboost_thread -lpthread -pthread -Wl,-rpath -Wl,/usr/local/sbin/mcrouter/install/lib -Wl,-rpath -Wl,/usr/local/sbin/mcrouter/install/lib
/usr/local/sbin/mcrouter/install/lib/libwangle.a(SSLUtil.cpp.o): In function `folly::ScopeGuardImpl<wangle::SSLUtil::getSubjectAltName(x509_st const*)::{lambda()#1}>::execute()':
SSLUtil.cpp:(.text+0x519): undefined reference to `folly::ScopeGuardImplBase::warnAboutToCrash()'
collect2: error: ld returned 1 exit status
Makefile:473: recipe for target 'mock_mc_server' failed_

---

I have no idea what should i try next. Can you help me or do you have any suggestions.
I am trying to build it on debian 8.7.
Thanks

**Comment by amcrn** [comment]
Something that might help: The folly and wangle commit hashes work for me on the release branches. For example, I just built from `release-35-0` successfully. As of late, `master` has been broken, but the release branches almost always work.

**Comment by andreazevedo** [comment]
Hey @Dejfik,
I just pushed a [new release branch](https://github.com/facebook/mcrouter/tree/release-36-0) that should work fine with folly and wangle.
In general it's a good practice to always use a release branch when building mcrouter for production.

**Comment by Dejfik** [comment]
Hi,
thank you for your help. I finally get it working, I will describe bellow step by step what worked for me.
Installing release v35 mcrouter on debian 8.7.

1. git clone git@github.com:facebook/mcrouter.git
   git checkout 78a200af3fad43e3fbccb0f6766ae7127d41441a (v35 release)
2. FOLLY_COMMIT < ff77522af770ae066419df2aecefbc1338b8c7ab
    WANGLE_COMMIT < f1704ef198062d9754e4a07857a737381d017140
3. /mcrouter/scripts/install_ubuntu_15.04.sh /path/to/your/folder -j4
4. comment out /mcrouter/scripts/install_ubuntu_15.04.sh all apt-get commands
   comment out /mcrouter/scripts/order-ubuntu-15/20_mcrouter lines 
        #autoreconf --install
        #LD_LIBRARY_PATH="$INSTALL_DIR/lib:$LD_LIBRARY_PATH" \
        #    LD_RUN_PATH="$INSTALL_DIR/lib:$LD_RUN_PATH" \
        #    LDFLAGS="-L$INSTALL_DIR/lib $LDFLAGS" \
        #    CPPFLAGS="-I$INSTALL_DIR/include $CPPFLAGS" \
        #    ./configure --prefix="$INSTALL_DIR"
5. installing liblz4
        apt-get install dpkg-dev debhelper
        echo "deb-src http://ftp.de.debian.org/debian/ stretch main" > /etc/apt/sources.list.d/stretch-source-packages.list
        apt-get update
        apt-get source lz4=0.0~r131-2
        cd lz4-0.0~r131
        dpkg-buildpackage -rfakeroot -uc -b
        cd ..
        dpkg -i liblz4-1_0.0~r131-2_amd64.deb liblz4-dev_0.0~r131-2_amd64.deb
6. run 
    find . -name Makefile | xargs -L1 sed -i "s/-lz -lssl/-lz -llz4 -lssl/"
    in destination folder (i ran it also in source mcrouter folder)
7. repeat step 3
    /mcrouter/scripts/install_ubuntu_15.04.sh /path/to/your/folder -j4

This worked for me, I used knowledge from issues #149 and #187.
Thank you all for your help, I am closing the issue
