### ISSUE TITLE
Is there a way to stop health checking `version` request?

### ISSUE THREAD

**Issue by kols** [facebook/mcrouter#194]
As the memcached service provider we chose doesn't support the `version` request.
And we still would like to try it out if the health checking can be turned off, so we can valuate other aspects of the program, and to see if it's viable for us to later migrate to a self-hosted memcached farm.

**Comment by jmswen** [comment]
Hi @kols, the command line option you are looking for is `--disable-tko-tracking`.

**Comment by kols** [comment]
Thanks, I'll play with that tomorrow. @jmswen
