### ISSUE TITLE
Extra memory allocation using large values split

### ISSUE THREAD

**Issue by wake-up-neo** [facebook/mcrouter#195]
> mcrouter --version
35.0.0-master mcrouter

For a large values using split option mcrouter allocates more resident memory each time I set values bigger than threshold for **the same** key.

`mcrouter --big-value-split-threshold=524288`

This will likely increase memcached RES memory 3 times:

```
 Memcached::set('SAMEKEY' , __LARGE_VALUE_TO_BE_SPLITTED__);
 Memcached::set('SAMEKEY' , __LARGE_VALUE_TO_BE_SPLITTED__);
 Memcached::set('SAMEKEY' , __LARGE_VALUE_TO_BE_SPLITTED__);
```

while running mcrouter without split threshold will not increase memory usage in this case.

Looks like an issue or this is supposed to be a regular behavior?

**Comment by jmswen** [comment]
@wake-up-neo  This is a known limitation.  The saving grace here is that the orphan pieces in memcached will eventually fall off the LRU tail.  But still, if you set the same key many times in a short period of time, orphan piecess will take up extra memory in memcached, as you describe. 

In the next release, if you do 2 big value sets for the same key with the _exact same value_, you won't see 2x memory usage.  See https://github.com/facebook/mcrouter/commit/03664239f8161be63bcf86def50006a1c93af1bb.

Fundamentally, there is not much we can do on the mcrouter side to improve big value support in situations where a single key may be overwritten many times in a short duration without potentially causing other issues (more network roundtrips, racing sets and deletes, etc.).  If your workload requires good support for lots of writes to a single key, I would recommend taking a look at memcached's support for chained allocations.
