### ISSUE TITLE
pool servers using sockets

### ISSUE THREAD

**Issue by port22** [facebook/mcrouter#208]
Hi, how is it possible to connect to pool servers using unix sockets?

I want to use mcrouter as a gathering/distribution system for cache prewarming servers, whereas the mcrouter then fills the local memcached on every node in a cluster, which listens via unix-socket. So I need something like this:

```
"pools": { "foo": { "servers": [  "unix:/var/run/memcached.sock" ] } }
```

**Comment by brianwatling** [comment]
Unfortunately we don't currently support Unix domain sockets in the pool config. AccessPoint (AccessPoint.h) is limited to hostnames, IPv4, and IPv6 addresses at this time. Perhaps you can use a socket listening on localhost as a workaround

**Comment by brianwatling** [comment]
This is now implemented
