### ISSUE TITLE
Consider changing license

### ISSUE THREAD

**Issue by cthayer** [facebook/mcrouter#210]
With the recent community uproar around FaceBook's BSD+Patents licensing and the announcement that other FaceBook OSS projects (most notably React.js) are changing to an MIT license (https://code.facebook.com/posts/300798627056246), I'd like to propose that mcrouter follow suit and change it's license to a more community friendly license.

Definitely appreciate all the hard work and effort of the mcrouter team.  This project is super awesome!

**Comment by Sauraus** [comment]
I would like to point out that neither the wiki nor the `LICENSE` file (https://github.com/facebook/mcrouter/blob/master/LICENSE) contain any references to the `PATENTS` file here: https://github.com/facebook/mcrouter/blob/master/PATENTS which makes the situation rather murky as to what's what.

**Comment by cthayer** [comment]
Perhaps the `PATENTS` file could just be removed?

**Comment by andreazevedo** [comment]
Today we're relicensing mcrouter under the MIT license.
I want to thank everyone for their patience as we worked to arrive at this change.
We hope that mcrouter adopting the MIT license will lead to more companies using and improving mcrouter.

**Comment by apepojken** [comment]
It's still the bsd license in repo: https://github.com/facebook/mcrouter/blob/master/LICENSE
