### ISSUE TITLE
WarmUp and Replication to All nodes.

### ISSUE THREAD

**Issue by agarbato** [facebook/mcrouter#217]
Hi,

Is it possible to use the WarmUpRoute and Replication together?

Basically we have an old box with memcache which in time we would like to decommission.
Using the config below set,add,delete are  replicated to all nodes as expected.
When the cold pool instead receive a miss the key is added only on one node of the cold pool.
Is it possible somehow to add key to all nodes instead like AllSyncRoute behavior? 

{
   "pools": {
     "cold": { 
        "servers": [ "1.1.1.10:11211", "1.1.1.11:11211" ] },
     "warm": { 
        "servers": [ "1.1.1.15:11211" ] }
   },
   "route": {
     "type": "OperationSelectorRoute",
     "operation_policies": {
       "get": {
         "type": "WarmUpRoute",
         "cold": "PoolRoute|cold",
         "warm": "PoolRoute|warm"
       },
       "set": "AllSyncRoute|Pool|cold",
       "add": "AllSyncRoute|Pool|cold",
       "delete": "AllSyncRoute|Pool|cold"
     } 
   }
}

**Comment by andreazevedo** [comment]
Hello @agarbato,

Yes, it is possible! You can do something like:

```js
...
"type": "OperationSelectorRoute",
"operation_policies": {
  "get": {
    "type": "WarmUpRoute",
    "cold": {
      "type": "OperationSelectorRoute",
      "operation_policies": {
        "get": "LatestRoute|Pool|cold",
        "set": "AllSyncRoute|Pool|cold"
      }
      "default_policy": "AllSyncRoute|Pool|cold"
    }
    "warm": "PoolRoute|warm"
  },
...
```

I hope this helps!
Feel free to reopen the issue if you have more questions.

Thank you,
Andre
