### ISSUE TITLE
mcrouter conflicts between HA and AllAsyncRoute 

### ISSUE THREAD

**Issue by ncaustin** [facebook/mcrouter#221]
It seems like the suggested method for HA mcrouter nodes dropping out of a cluster is to use AllAsyncRoute and FailoverRoute for gets. Otherwise any set operation will fail until the machine is removed from the cluster, better than nothing if you can reconfigure quickly.

However AllAsyncRoute doesn't seem to work well with other libraries that use cache services that expect memcache to return a result. I guess Facebook uses the mcrouter directly. Case in point is incr will never return the increment value in this mode and set will return False if you use python-memcached as it fails on NOT STORED vs STORED.

{
   "pools": {
      "frontend": {
        "servers": [ "10.0.0.10:11211","10.0.0.11:11211"  ]
      }
   },
   "route": {
     "type": "OperationSelectorRoute",
      "operation_policies": {
       "add": "AllAsyncRoute|Pool|frontend",
       "delete": "AllAsyncRoute|Pool|frontend",
       "get": "MissFailoverRoute|Pool|frontend",
       "set": "AllAsyncRoute|Pool|frontend",
       "incr": "AllAsyncRoute|Pool|frontend",
       "decr": "AllAsyncRoute|Pool|frontend"
     }
   }
}

**Comment by amcrn** [comment]
@ncaustin I'd recommend trying AllFastestRoute (see https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#allfastestroute) vs. AllAsyncRoute.

**Comment by ncaustin** [comment]
Thanks @amcrn that works far better for incr/decr for failover!
