### ISSUE TITLE
Feature Request: Support GAT & GATS (Get And Touch Commands)

### ISSUE THREAD

**Issue by amcrn** [facebook/mcrouter#222]
Memcached 1.5.3 added the `gat` and `gats` commands to the ASCII protocol.

See:

* https://github.com/memcached/memcached/wiki/ReleaseNotes153
* https://github.com/memcached/memcached/commit/7f4e0246e5c27baa9a7a690e5905f5ee56b80ece

Example:

```
Connected to localhost.
Escape character is '^]'.
set foo 0 0 3
bar
STORED
gat 0 foo
VALUE foo 0 3
bar
END
gats 0 foo
VALUE foo 0 3 1
bar
END
```

It would be great to have support for these commands in mcrouter. As of now, these result in `CLIENT_ERROR malformed request` because they're not implemented.

**Comment by sergmour** [comment]
There is an open pull request for the issue: https://github.com/facebook/mcrouter/pull/270

**Comment by amcrn** [comment]
Merged with: https://github.com/facebook/mcrouter/pull/270/commits
