### ISSUE TITLE
Fix compile for boost 1.61+

### ISSUE THREAD

**Issue by kornrunner** [facebook/mcrouter#225]
Hi,

I've submitted #224 that fixes compilation when boost is 1.61+, and keeps BC.

Any interest in merging it in? Thanks!

**Comment by mandeepsandhu** [comment]
+1 for merging this change.

**Comment by kornrunner** [comment]
Fixed in https://github.com/facebook/mcrouter/commit/7ab227eceb66526479226b67540ca9463ea1a293
