### ISSUE TITLE
Which release is a stable version?

### ISSUE THREAD

**Issue by coooold** [facebook/mcrouter#227]
We're planning to use mcrouter for cross idc replicating? But i found there are hundreds of commit after release 0.36.  Should we take the head commit as the PRODUCTION one? or an elder release?
And which commits of wangle and folly should we take? Thanks very much

**Comment by gaod** [comment]
I just made a ppa for folly/wangle v2017.12.25.00 and mcrouter at head commit. But I did't test the stability yet.

**Comment by lavagetto** [comment]
Can we please get any indication of what is a known stable version to build?

I don't think that's a huge effort to either tag versions that are known to be stable and work at facebook, or at least shed some light on the status of the project. We at the Wikimedia Foundation want to use mcrouter for multi-dc caching, but the absence of any indication on what is a stable release is making it challenging.

**Comment by andreazevedo** [comment]
Even though the master is fairly stable, we do recommend using the latest tagged release.
I just tagged release 37 and we will be releasing a new version (version 38) in a few days.
Thank you, everyone!

**Comment by lavagetto** [comment]
@andreazevedo thanks a lot, this will surely help us.
