### ISSUE TITLE
Statically build all libraries from dependencies

### ISSUE THREAD

**Issue by aesdana** [facebook/mcrouter#23]
Have a need to use mcrouter with ubuntu 12.04, so, is there a way to build all the libraries statically? I'm really lost in all these includes and dependencies and scripts, would be great if somebody can prompt were to put -static  option?

**Comment by alikhtarov** [comment]
@aesdana Note that I could successfully build for 12.04 even with shared libraries, so it shouldn't be required. I'm not sure if it's easy to build all the dependencies statically, but you can try the approach suggested here http://stackoverflow.com/questions/13997415/how-can-an-autotools-user-specify-a-combination-of-static-dynamic-linking
