### ISSUE TITLE
Fedora automake RPM link is out of date in install_centos_7.2.sh

### ISSUE THREAD

**Issue by mjkelly** [facebook/mcrouter#230]
Hi!

While building mcrouter on Centos 7.2 from head via `install_centos_7.2.sh`, I noticed that this line looks out of date:
https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/install_centos_7.2.sh#L35-L36 (that URL 404s)

Based on a message in <http://dl.fedoraproject.org/pub/fedora/linux/releases/23/>, this is the up-to-date link:
<http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/23/Everything/x86_64/os/Packages/a/automake-1.15-4.fc23.noarch.rpm>

Also, since we have `set -e` at the top of the script, the `rpm` command will fail on a second run. We could do something like this instead:

```sh
yum info automake-1.15-4.fc23 || sudo yum install -y "http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/23/Everything/x86_64/os/Packages/a/automake-1.15-4.fc23.noarch.rpm"
```

What do you think?

**Comment by mjkelly** [comment]
I have https://github.com/facebook/mcrouter/pull/234 open to address this (nothing special, just updating the URL).

**Comment by daniel-lucio** [comment]
Use my RPM's if you still need them.
https://inside-out.xyz/technology/memcached-protocol-router-rpm-for-centos-7.html
