### ISSUE TITLE
Stats groups are not workng as expected

### ISSUE THREAD

**Issue by khfayzullaev** [facebook/mcrouter#233]
**What**
According to this [page](https://github.com/facebook/mcrouter/wiki/Stats-commands) I can pass optional 'group' parameter using `stats` to fine out more about mcrouter state, performance and usage information. I do not believe that all `groups` are available though.

Out of these `groups`
- **all** - Returns all the stats.
- **cmd** - Returns number of requests received and sent.
- **cmd-in**  - Returns number of requests received.
- **cmd-out** - Returns number of requests sent.
- **cmd-error** - Returns number of requests failed.
- **servers** - This is a special group, not included in any of above. Returns state of each server from config, together with additional info per each server. Output example:
- **suspect_servers** -  Similar to servers but returns list of servers that replied with an error to last request sent to them.

I was not able to use `cmd`, `cmd-in` and `cmd-out` using `echo "stats [group]" | nc 0 5000` example and I got `CLIENT_ERROR bad stats command` errors.

**Background**
mcrouter was built against https://github.com/facebook/mcrouter/commit/a4b145a5e992fed22ce27ac939a66ee596072c71

**Comment by amcrn** [comment]
@khfayzullaev `cmd-error` exists, but it looks like the other `cmd-*` groups do not.

In looking at `git history`, it looks like they never did!

See https://github.com/facebook/mcrouter/blame/71da56e9d7616b535b16f626488a58877b03bbf5/mcrouter/stats.cpp#L515-L535 (`Open source Mcrouter initial commit" from 4 years ago`).

I'd chalk this up to a documentation bug. Hope that helps. (Note: I'm not a committer to mcrouter, just a user attempting to be helpful).

**Comment by khfayzullaev** [comment]
Closing the issue because it has not had recent activity.
