### ISSUE TITLE
Read from any server in a pool, write too all servers in a pool

### ISSUE THREAD

**Issue by chilumbugeorge** [facebook/mcrouter#235]
I have managed to setup mcrouter, currently testing with two servers. However, when i try to add data to servers listed in a pool, i notice that data is only being stored in one of servers and not the other when i check locally on each server.

Here is my config on both mcrouter servers:

`
{
  "pools": {
    "memcached-events": {
      "servers": [ "10.1.9.100:11211", "10.1.9.101:11211" ]
    },
    "memcached-notifications": {
      "servers": [ "10.1.9.120:11211", "10.1.9.121:11211" ]
    },
    "memcached-sessions": {
      "servers": [ "10.1.9.200:11211", "10.1.9.201:11211" ]
    }
  },
     "route": {
        "type": "PrefixSelectorRoute",
         "policies": {
            "mybox": "PoolRoute|memcached-events",
            "shared": "PoolRoute|memcached-notifications",
            "general": "PoolRoute|memcached-sessions"

        },
         "wildcard": "ErrorRoute|Got key with unexpected prefix"
    }
}
` 

To add data, i am running the following on one of the mcrouters:

`printf "set events_k1 0 0 4\r\n1234\r\n" | nc localhost 11212`

And i can see the data when i run the following command on both mcrouters:

`printf "get events_k1 \r\n" | nc localhost 11212`

But when i try to check if the data exists on both nodes in the "memcached_events" pool, only one shows results, and the other does not show. So not sure why running the "get" command from the mcrouter servers (both routers) produce results when in actuality only one of the nodes in the "events" pool stored the data? What am i missing here?

**Comment by spalamarchuk** [comment]
Hi @chilumbugeorge, PoolRoute always routes to exactly single destination host based on the hash function (default: Ch3).

The primary purpose of PoolRoute is to distribute data between several nodes and make it look like one big node from the user perspective.

The behavior that you describe and expect is more of a replicated pool, see https://github.com/facebook/mcrouter/wiki/Replicated-pools-setup for more details on what it does and how to set it up.

**Comment by chilumbugeorge** [comment]
I am using the PrefixSelectorRoute to control what data goes into what pool, and this is critical for my requirements. At the same time, it is critical that the servers in each pool have exactly the same data, which like you suggested requires that i use the replicated pool. So how can i use both features in my config file to achieve both of my requirements described above i.e., synced servers in each pool, and also appropriately send data to each pool as each pool is used by different teams for different purposes?

**Comment by spalamarchuk** [comment]
@chilumbugeorge, mcrouter configs are composable, so you can put replicated pools into PrefixSelectorRoute. For your config, you could have next one to handle the replication:

```
{
  "pools": {
    "memcached-events": {
      "servers": [ "10.1.9.100:11211", "10.1.9.101:11211" ]
    },
    "memcached-notifications": {
      "servers": [ "10.1.9.120:11211", "10.1.9.121:11211" ]
    },
    "memcached-sessions": {
      "servers": [ "10.1.9.200:11211", "10.1.9.201:11211" ]
    }
  }
  "macros": [
    {
      "type": "macroDef",
      "name": "replicatedPool",
      "params": [ "poolName" ],
      "result": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|%poolName%",
          "set": "AllSyncRoute|Pool|%poolName%",
          "delete": "AllSyncRoute|Pool|%poolName%",
          "get": "LatestRoute|Pool|%poolName%",
        }
      }
    }
  ],
  "route": {
    "type": "PrefixSelectorRoute",
    "policies": {
      "mybox": "@replicatedPool(memcached-events)",
      "shared": "@replicatedPool(memcached-notifications)",
      "general": "@replicatedPoolmemcached-sessions)",
    }
    "wildcard": "ErrorRoute|Got key with unexpected prefix"
  }
}
```

Note, in regards to "synced servers in each pool". This is not entirely true. Some updates may reach only one server due to network errors, so the servers might get inconsistent over time. This in general only matters for invalidations (deletes), mcrouter provides [reliable delete stream](https://github.com/facebook/mcrouter/wiki/Features#reliable-delete-stream).

**Comment by chilumbugeorge** [comment]
Thanks. Will try out the suggested approach above and let you guys know how it works out.

**Comment by chilumbugeorge** [comment]
I tried your suggested code with minor changes to make sure the JSOn format is correct, but mcrouter could not start with the following error message:

`● mcrouter.service - Mcrouter memcached router
   Loaded: loaded (/lib/systemd/system/mcrouter.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-03-15 10:41:57 CST; 1s ago
  Process: 32297 ExecStart=/usr/bin/mcrouter --debug-fifo-root /var/lib/mcrouter/fifos --stats-root /var/lib/mcrouter/stats -L /var/log/mcrouter/mcrouter.log -p $PORT -f $CONFIG_FILE $ADDITIONAL_ARGS $MCROUTER_FLAGS (code=exited, status=2
 Main PID: 32297 (code=exited, status=2)

Mar 15 10:41:57 db-gc-3 systemd[1]: Started Mcrouter memcached router.
Mar 15 10:41:57 db-gc-3 mcrouter[32297]: E0315 10:41:57.981335 32297 mcrouter_config.cpp:39] CRITICAL: Couldn't initialize from standalone flavor file /etc/mcrouter.conf
Mar 15 10:41:57 db-gc-3 mcrouter[32297]: I0315 10:41:57.981416 32297 main.cpp:416] Logging to /var/log/mcrouter/mcrouter.log
Mar 15 10:41:57 db-gc-3 systemd[1]: mcrouter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 15 10:41:57 db-gc-3 systemd[1]: mcrouter.service: Unit entered failed state.
Mar 15 10:41:57 db-gc-3 systemd[1]: mcrouter.service: Failed with result 'exit-code'.`

Below is my mcrouter config file:

`{
  "pools": {
    "memcached-events": {
      "servers": [ "10.1.9.100:11211", "10.1.9.101:11211" ]
    },
    "memcached-notifications": {
      "servers": [ "10.1.9.120:11211", "10.1.9.121:11211" ]
    },
    "memcached-sessions": {
      "servers": [ "10.1.9.200:11211", "10.1.9.201:11211" ]
    }
  },
  "macros": [{
    "type": "macroDef",
    "name": "replicatedPool",
    "params": ["poolName"],
    "result": {
      "type": "OperationSelectorRoute",
      "operation_policies": {
        "add": "AllSyncRoute|Pool|%poolName%",
        "set": "AllSyncRoute|Pool|%poolName%",
        "delete": "AllSyncRoute|Pool|%poolName%",
        "get": "LatestRoute|Pool|%poolName%"
      }
    }
  }],
  "route": {
    "type": "PrefixSelectorRoute",
    "policies": {
      "events": "@replicatedPool(memcached-events)",
      "notifications": "@replicatedPool(memcached-notifications)",
      "sessions": "@replicatedPoolmemcached-sessions)"
    },
    "wildcard": "ErrorRoute|Got key with unexpected prefix"
  }
}`

**Comment by spalamarchuk** [comment]
@chilumbugeorge, my config (without changes) should work just fine, I tested it with mcrouter before posting. If it's still an issue could you paste your config?

OperationSelectorRoute can be used in macros. I believe the problem you're describing can come up if you use a dictionary for macros and not list.

**Comment by chilumbugeorge** [comment]
I tried the code again without reformatting, and i still get this error  with mcrouter failing to start:

```
I0319 16:34:33.393664 16360 main.cpp:467] 36.0.0-master mcrouter startup (16360)
I0319 16:34:33.393690 16360 main.cpp:365] Starting Memcache router
I0319 16:34:33.393723 16360 Server-inl.h:123] Spawning AsyncMcServer
E0319 16:34:33.393944 16360 ConfigApi.cpp:60] Failed to create directory '"/var/mcrouter/config"'. Error code: system:0
FAILURE 1521448473.393972 16360 [libmcrouter.mcrouter.unknown] [other] [mcrouter] ConfigApi.cpp:84] Failed to setup directory for dumping configs. Configs won't be saved to disk.
"mcrouter": /usr/bin/mcrouter --debug-fifo-root /var/lib/mcrouter/fifos --stats-root /var/lib/mcrouter/stats -L /var/log/mcrouter/mcrouter.log -p -f -f /etc/mcrouter.conf -L /var/log/mcrouter/mcrouter.log -p 11212 --send-invalid-route-to$
default --file-observer-poll-period-ms=1000 --file-observer-sleep-before-update-ms=100 /etc/mcrouter.conf
I0319 16:34:33.394013 16360 FunctionScheduler.cpp:324] Starting FunctionScheduler with 0 functions.
FAILURE 1521448473.394686 16360 [libmcrouter.mcrouter.unknown] [invalid-config] [mcrouter] ../mcrouter/CarbonRouterInstance-inl.h:529] Failed to reconfigure: json parse error on line 0 near `"macros": [
    ': expected '}'
```

**Comment by spalamarchuk** [comment]
@chilumbugeorge, actually I'm terribly sorry, I copied the version of the config before I fixed all of the bugs in it. And now I remembered that the issue with `OperationSelectorRoute` was opposite from what I said: you need to use a dictionary instead of a list. Below is a working version:

```
{
  "pools": {
    "memcached-events": {
      "servers": [ "10.1.9.100:11211", "10.1.9.101:11211" ]
    },
    "memcached-notifications": {
      "servers": [ "10.1.9.120:11211", "10.1.9.121:11211" ]
    },
    "memcached-sessions": {
      "servers": [ "10.1.9.200:11211", "10.1.9.201:11211" ]
    }
  },
  "macros": {
    "replicatedPool": {
      "type": "macroDef",
      "params": [ "poolName" ],
      "result": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|%poolName%",
          "set": "AllSyncRoute|Pool|%poolName%",
          "delete": "AllSyncRoute|Pool|%poolName%",
          "get": "LatestRoute|Pool|%poolName%",
        }
      }
    }
  },
  "route": {
    "type": "PrefixSelectorRoute",
    "policies": {
      "mybox": "@replicatedPool(memcached-events)",
      "shared": "@replicatedPool(memcached-notifications)",
      "general": "@replicatedPool(memcached-sessions)",
    },
    "wildcard": "ErrorRoute|Got key with unexpected prefix"
  }
}
```

**Comment by chilumbugeorge** [comment]
@spalamarchuk the new code works like a charm. Exactly what i needed. 

Thanks a million.

**Comment by E-N-G-XOR** [comment]
Hi, 
How do you write and read data from a specific pool? Is there a format to get the data in the correct pool? When I tried to use the config above I got an error....

I sent this to mrcouter (printf "set events_k1 0 0 4\r\n1234\r\n" | nc 10.29.11.189 11211)

and the reply was.... 

SERVER_ERROR Got key with unexpected prefix

what am I doing wrong?

**Comment by andreazevedo** [comment]
@E-N-G-XOR,

For the config above, note that the only valid prefixes are: `mybox`, `shared`, and `general`. Keys with any other prefix will go to `ErrorRoute`, which will return the message you saw: `Got key with unexpected prefix`. This is configured in the following part of the config:
```json
"type": "PrefixSelectorRoute",
"policies": {
  "mybox": "@replicatedPool(memcached-events)",
  "shared": "@replicatedPool(memcached-notifications)",
  "general": "@replicatedPool(memcached-sessions)",
},
"wildcard": "ErrorRoute|Got key with unexpected prefix"
```

If you prefix your key with `mybox` for example, it should work: `printf "set mybox:events_k1 0 0 4\r\n1234\r\n" | nc 10.29.11.189 11211`.

Note: Memcache will receive the full key. In the example above, memcache will receive `mybox:events_k1`.

**Comment by E-N-G-XOR** [comment]
Awesome, thanks !! That is exactly what I needed! I couldn't for the life of me figure out how to write to the different pools.... I kept getting the wildcard error.... :(
