### ISSUE TITLE
Different mcrouter hash function

### ISSUE THREAD

**Issue by chilumbugeorge** [facebook/mcrouter#238]
I came across this [page](https://github.com/facebook/mcrouter/wiki/Pools) discussing different hash functions that mcrouter can use, but could not find an example of how a hash function can be configured if you do not want to use the default ch3. In my case, i would like to use the "wch3" with a  balanced (50/50) weight between two nodes in a pool. How can i manually change the default to configure wch3?

Thanks in advance.

**Comment by spalamarchuk** [comment]
@chilumbugeorge, you can specify hash function via "hash" property of PoolRoute.
It should be either a string name ("Ch3", "WeightedCh3", "Crc32") or an object with next fields in it
`hash_func` - name of hash function ("Ch3", "WeightedCh3", "Crc32")
`weights` (optional) - a list of hash weights in range of [0,1], in your case it's `0.5` for both nodes
`salt` (optional) - salt for the hash, works only for some hash functions

**Comment by chilumbugeorge** [comment]
So i created this config to control hash functions with a balanced 50/50 weight between two nodes in each pool. Below is the config file:

```
{
  "pools": {
    "memcached-session": {
      "servers": [ "10.1.9.100:11211", "10.1.9.101:11211" ]
    },
    "memcached-shared": {
      "servers": [ "10.1.9.200:11211", "10.1.9.201:11211" ]
    }
  },
    "route": {
        "type": "PrefixSelectorRoute",
        "policies": {
            "session": {
                 "type": "HashRoute",
                 "children": "Pool|memcached-session",
                 "hash_func": "WeightedCh3",
                 "weights": [ 0.5, 0.5 ]
             },
            "shared": {
                 "type": "HashRoute",
                 "children": "Pool|memcached-shared",
                 "hash_func": "WeightedCh3",
                 "weights": [ 0.5, 0.5 ]
             }
        },
         "wildcard": "ErrorRoute|Got key with unexpected prefix"
    }
}
```

However, i noticed that the keys are not evenly stored in each memcached servers. For example, when i store 10 keys in memcached_session, one node in this pool would store 8 keys, and the other only 2. So i am not getting the 50/50 like i was expecting. Am i doing anything wrong in my config?

**Comment by spalamarchuk** [comment]
@chilumbugeorge, 10 is not very representative selection (the overall keyspace is split 50/50, but you always can chose 10 keys that would only go to one box). You were simply unlucky in your choice of keys, or your keys have very poor entropy.

For example, using your config (mcrouter runs on port 5000) and the next script:

```
# test.bash
for i in `seq 1 $1`
do
  echo "get __mcrouter__.route(set,session:$i)" | nc ::1 5000 | grep 11211
done
```

I get next results for 10, 100, 1000, 500 keys:

```
# bash ~/test.sh 10 | sort | uniq -c
      6 10.1.9.100:11211
      4 10.1.9.101:11211
# bash ~/test.sh 100 | sort | uniq -c
     50 10.1.9.100:11211
     50 10.1.9.101:11211
# bash ~/test.sh 1000 | sort | uniq -c
    506 10.1.9.100:11211
    494 10.1.9.101:11211
# bash ~/test.sh 500 | sort | uniq -c
    254 10.1.9.100:11211
    246 10.1.9.101:11211
```

as you can see, this always gets close to 50/50 distribution.

P.S. `get __mcrouter__.route(op,key)` prints the destionation server.

**Comment by chilumbugeorge** [comment]
Makes sense. Thanks @spalamarchuk
