### ISSUE TITLE
McRouter terminates with SIGABRT error code

### ISSUE THREAD

**Issue by theonajim** [facebook/mcrouter#239]
We are seeing the following error in one of our testing environments. McRouter terminates with SIGABRT error code. How do we troubleshoot this issue?

mcrouter: lib/network/McAsciiParser.rl:1107: facebook::memcache::McAsciiParserBase::State facebook::memcache::McServerAsciiParser::consume(folly::IOBuf&): Assertion `state_ != State::ERROR' 

$ mcrouter -V
35.0.0 mcrouter

**Comment by andreazevedo** [comment]
Hello @theonajim,

Which protocol are you using to talk to mcrouter? Mcrouter only supports ascii protocol.

**Comment by theonajim** [comment]
Hello @andreazevedo ,
We are only using ascii protocol and memcached is started with -B ascii option. This environment has 4 servers, interestingly we only see this crash on one of the 4 servers.

**Comment by andreazevedo** [comment]
Hello @theonajim,

Are you saying that you have 4 `mcrouter` instances running, and only of one the 4 instances is crashing?
Can you reliably reproduce the crash? What is the payload that makes `mcrouter` crash? What config are you using? Are you running the same mcrouter version on all 4 instances?

Thank you.

**Comment by theonajim** [comment]
@andreazevedo 
Yes one of the 4 crashes. They are all running version 35.0.0 . I am not able to reproduce it yet. I will try tcpdump to see if I capture the events at the time of next crash.  Most requests are for small json strings about 140 characters in length so nothing unusual there. 

Below is the configuration:

mcrouter --port=5000 --config=file:/etc/mcrouter/mcrouter.json --stats-root=/<dir>/var/mcrouter/stats --async-dir=/<dir>/log/var/spool/mcrouter --num-proxies=1 --server-timeout=1000

/etc/mcrouter/mcrouter.json 

`{
  "pools": {
    "cloud-1": {
      "servers": [
        "<ip1>:11211",
        "<ip2>:11211"
      ]
    },
    "cloud-2": {
      "servers": [
        "<ip3>:11211",
        "<ip4>:11211"
      ]
    }
  },
  "route": {
    "type": "OperationSelectorRoute",
    "default_policy": {
      "type": "AllAsyncRoute",
      "children": [
        {
          "type": "HashRoute",
          "children": "Pool|cloud-1",
          "salt": "1"
        },
        {
          "type": "HashRoute",
          "children": "Pool|cloud-2",
          "salt": "2"
        }
      ]
    },
    "operation_policies": {
      "get": {
        "type": "MissFailoverRoute",
        "children": [
          {
            "type": "HashRoute",
            "children": "Pool|cloud-1",
            "salt": "1"
          },
          {
            "type": "HashRoute",
            "children": "Pool|cloud-2",
            "salt": "2"
          }
        ]
      },
      "gets": {
        "type": "MissFailoverRoute",
        "children": [
          {
            "type": "HashRoute",
            "children": "Pool|cloud-1",
            "salt": "1"
          },
          {
            "type": "HashRoute",
            "children": "Pool|cloud-2",
            "salt": "2"
          }
        ]
      }
    }
  }
}`

**Comment by theonajim** [comment]
@andreazevedo 
I was able to capture the events at the time of the most recent crash. I am able to reproduce the crash with mcrouter version 0.35 using a simple program. I tested version 0.36 and 0.37 and they don't crash using the same program. If you are interested, I can send you the program over email. Otherwise, we can consider this issue closed.

**Comment by andreazevedo** [comment]
Hey @theonajim,
I'm interested, can you send me the source code of the program that you used to make mcrouter 0.25 crash?
Thank you!
