### ISSUE TITLE
pool_locality option is no longer used

### ISSUE THREAD

**Issue by sergmour** [facebook/mcrouter#248]
Hi guys,
It looks like pool_locality option (specified in mcrouter.json per-pool configuration) is no longer used in mcrouter code.
--cluster-pools-timeout=<N> and --regional-pools-timeout=<N> command line options aren't used either.
This is all listed here: https://github.com/facebook/mcrouter/wiki/Command-line-options and is confusing as you can't figure it out unless you go to the source code. Please update the docs.

From another perspective, you started using "region" and "cluster" per-pool attributes and I don't see them documented anywhere.

Thanks,
-sergei

**Comment by andreazevedo** [comment]
Thanks for the report! I updated the docs, let me know if that helps!
