### ISSUE TITLE
Ubuntu 16.04 install script not compiling

### ISSUE THREAD

**Issue by sepiroth887** [facebook/mcrouter#251]
Hey, 

I have quite a bit of trouble getting mcrouter build for 16.04. I tried various different folly and wrangle releases to match against mcrouter 0.36.0 but with little success.

Is it possible to add a tiny file along side releases to indicate which dependencies this release was successfully build including wrangle and folly? 

Most recent error i'm getting is: 

WeightedCh3HashFunc.cpp:12:32: fatal error: folly/SpookyHashV2.h: No such file or directory
compilation terminated.
Makefile:1244: recipe for target 'libmcrouter_a-WeightedCh3HashFunc.o' failed
make[3]: *** [libmcrouter_a-WeightedCh3HashFunc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/libmcrouter_a-Lz4CompressionCodec.Tpo .deps/libmcrouter_a-Lz4CompressionCodec.Po
mv -f .deps/libmcrouter_a-Compression.Tpo .deps/libmcrouter_a-Compression.Po
In file included from ../../mcrouter/lib/carbon/CommonSerializationTraits.h:16:0,
                 from ../../mcrouter/lib/network/gen/MemcacheMessages.h:26,
                 from ../../mcrouter/lib/network/gen/Memcache.h:18,
                 from StatsReply.cpp:14:
../../mcrouter/lib/carbon/Keys.h:17:32: fatal error: folly/SpookyHashV2.h: No such file or directory

About the os: 

VERSION="16.04.4 LTS (Xenial Xerus)"
4.13.0-1014-azure 

Vanilla install just relying on install script.

Thanks for any pointers what's going wrong

**Comment by gaod** [comment]
I've packaged a ppa, have a try?

https://launchpad.net/~gaod/+archive/ubuntu/mcrouter

**Comment by sepiroth887** [comment]
I very much appreciate this :) Sadly due to some constraints I cannot download arbitrary unvalidated packages from a PPA so building from source is our only option right now :( 

If you do have more info on what folly/wangle + build dependency versions you used to get those packages into the ppa it would be of immense help.

However I guess you are also in the same boat trying to find the correct combinations each and every time a new mcrouter version is released? If not please tell me your secrets 💯

**Comment by JJ-C** [comment]
I just got the release 37 and a different compiling error using the installation script.  Anyone have any idea on this?  Thanks in advance.

make[3]: Entering directory '/dev/mcrouter-0.37.0/mcrouter/lib'
g++ -std=gnu++14 -DHAVE_CONFIG_H   -I../.. -I/home/vagrant/dev/install/include   -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -MT network/libmcrouter_a-AsyncMcClientImpl.o -MD -MP -MF network/.deps/libmcrouter_a-AsyncMcClientImpl.Tpo -c -o network/libmcrouter_a-AsyncMcClientImpl.o `test -f 'network/AsyncMcClientImpl.cpp' || echo './'`network/AsyncMcClientImpl.cpp
network/AsyncMcClientImpl.cpp: In lambda function:
network/AsyncMcClientImpl.cpp:518:22: error: ‘class folly::AsyncSSLSocket’ has no member named ‘setServiceIdentity’
           sslSocket->setServiceIdentity(serviceId);
                      ^
Makefile:1489: recipe for target 'network/libmcrouter_a-AsyncMcClientImpl.o' failed
make[3]: *** [network/libmcrouter_a-AsyncMcClientImpl.o] Error 1
make[3]: Leaving directory '/jchen65/mcrouter-0.37.0/mcrouter/lib'
Makefile:1848: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/jchen65/mcrouter-0.37.0/mcrouter/lib'
Makefile:1540: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/jchen65/mcrouter-0.37.0/mcrouter'
Makefile:669: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gaod** [comment]
ref: 31d23d85cdb1c7b8a3e2d4dc1d9ca2bf9c224ace

**Comment by gaod** [comment]
Also, you may take a look what folly & wangle version do you have.
https://github.com/facebook/mcrouter/blob/release-37-0/mcrouter/FOLLY_COMMIT
https://github.com/facebook/mcrouter/blob/release-37-0/mcrouter/WANGLE_COMMIT

**Comment by andreazevedo** [comment]
It should be fixed now! Let me know if you have more problems with it.

**Comment by JJ-C** [comment]
It works! thanks!
