### ISSUE TITLE
How to calculate percentiles

### ISSUE THREAD

**Issue by le087** [facebook/mcrouter#256]
Hello.

Thank you for mcrouter. It's a beatifull application. Now I have some distributed cache infrastructure based on mcrouter. It works!

I read a documentation and issues about the mcrouter but I didn't find statistics from mcrouter for calculating of the percentils (25, 50, 75, 85, 90, 95, 97, 99, 99.9, 1). 

I see only an average time of handling requests. I want to get the percentils because my entire infrastructure has metrics with percentils. I can't see the correlation between the response time of the application and the access time in memcached. 

if I can see the time distribution, I can do a more fine-tuning for better performance. Of course, I can write some programm for measuring percentils, but if you already have a ready-made solution, it will simplify my task.

How difficult is it to add such statistics (for calculating percentils) to the mcrouter and how high will the overhead be when implementing such changes? 

Thank you.

**Comment by andreazevedo** [comment]
Hello @le087!

First of all, thank you for using mcrouter, I'm happy it's working well for you.

About percentiles, at Facebook we have a separate internal tool that we use for that. The open source mcrouter doesn't provide percentiles out-of-the-box.

What you can do, is customize mcrouter to log requests duration to some database that allows you to extract the percentiles later on.
If you are ready for some C++, here is where you need to write some code to actually log your request: https://github.com/facebook/mcrouter/blob/master/mcrouter/lib/carbon/NoopAdditionalLogger.h#L27-L31.
To get the duration, you could do something like:
```cpp
template <class Request>
void log(
    const Request& request,
    const typename Request::reply_type& reply,
    const facebook::memcache::mcrouter::RequestLoggerContext& reqLoggerContext) {
  auto durationUs = reqLoggerContext.endTimeUs - reqLoggerContext.startTimeUs;
  // log durationUs somehwere...  
}
```

Hope that helps,
Andre

**Comment by le087** [comment]
@andreazevedo Thank you! This is usefull for me. That's a lot more than I expected to get.  The rays of goodness to you. =)
