### ISSUE TITLE
A doubt ?

### ISSUE THREAD

**Issue by shizhoulong356** [facebook/mcrouter#257]
Hi  i  have a quersion:

if a have 2 pools memcache A and B.  All  get opertions   route policy is MissFailoverRoute, and all updates operations will route to both pool A and B  at the same time.

then if   a key in pool A expired ,   then it will return to client  redirectly ?
 or  it will look the key in the pool B, then return  client ?

if the behind situation,  it will cause a part of performance loss,because  mcrouter must look for the key from pool B  then return to client ?

**Comment by andreazevedo** [comment]
Hello @shizhoulong356,

In case of a miss (i.e. if the key is no present in pool A), `MissFailoverRoute` will route the request to pool B automatically.
There will be a small added latency cost, as we now have to go to another `memcached` host. But that is usually preferred over going to the backend to fetch the data.

Hope that helps,
Andre
