### ISSUE TITLE
SET /*/pool/key causes segfault

### ISSUE THREAD

**Issue by ptrmcrthr** [facebook/mcrouter#27]
I am getting started with mcrouter and trying to find a config that will work for me. While testing I found that some combination of config and set would cause a segfault.

Here is my config: https://gist.github.com/ptrmcrthr/dd9965739ecaaf8cd67a
Here is the gdb output: https://gist.github.com/ptrmcrthr/05d4536af96b900c04fb 

The last command below causes a segfault: 
```
[vagrant@vagrant ~]$ echo -e 'set /dc1/default/mykey 0 60 5\r\nhello\r' | nc 192.168.59.103 5000 
STORED
[vagrant@vagrant ~]$ echo -e 'get /dc1/default/mykey' | nc 192.168.59.103 5000
VALUE /dc1/default/mykey 0 5
hello
END
[vagrant@vagrant ~]$ echo -e 'stats' | nc 192.168.59.103 5000 | grep version 
STAT version mcrouter 1.0
[vagrant@vagrant ~]$ echo -e 'set /*/default/mykey 0 60 5\r\nhello\r' | nc 192.168.59.103 5000 
```

I am trying to create a configuration with two datacenters. I would like to broadcast some write operations   to both datacenters.

**Comment by alikhtarov** [comment]
Thanks for the report! I'm trying to reproduce this locally now.

**Comment by ptrmcrthr** [comment]
Cool — I am using the docker file included in the github repo. I also found that ```set /dc1/def*/mykey``` causes a crash using the above config. ```set /dc1/default/mykey``` and ```set /dc1/*/mykey``` work correctly.

The config I am testing is pretty much copied from the example on https://github.com/facebook/mcrouter/wiki/Routing-Prefix

**Comment by pavlo-fb** [comment]
@ptrmcrthr we found a bug, thanks for the report. It will be fixed in next GitHub push (next week).
For now you can use "set /dc/*/key" and "/dc/cluster1/", "/dc/cluster2/" routing prefixes.

**Comment by ptrmcrthr** [comment]
@pavlo-fb can you advise if i'm doing something wrong trying to broadcast DELETEs and SETs to the same cluster at two datacenters? Does my config make sense for that?

Thanks

**Comment by pavlo-fb** [comment]
@ptrmcrthr your config makes perfect sense. It can be simplified a bit: there is no reason to create PrefixSelectorRoute without _policies_, you can use PoolRoute directly.

Regarding broadcasting to the same cluster in multiple datacenters: it is a totally valid use case. We fixed the bug (see https://github.com/facebook/mcrouter/commit/ae7099758c376f9e9751b3b8d6879d9e0be1a50d ), feel free to use this approach.
Minor note though: mcrouter is optimized for broadcasting to multiple clusters in the same datacenter, i.e. /dc/*/ routing prefixes, not /*/cluster/. I don't think you'll notice a big performance difference, but in general /dc/*/ will work a tap faster.
