### ISSUE TITLE
Using GETS and CAS with replicated setup

### ISSUE THREAD

**Issue by solidfoxrock** [facebook/mcrouter#28]
Hi guys, this is not an issue, I just want to ask if mcrouter replicated setup work with GETS and CAS commands?

**Comment by alikhtarov** [comment]
Assuming both `gets` and corresponding `cas` end up on the same replica, yes. This should be the case most of the time, but very rarely you might get a situation where the first `gets` goes to replica A, and then replica A goes offline temporarily, so that `cas` will go to replica B (assuming you have set up failover that way), and `cas` will fail. As long as your system can tolerate these rare failures, it will work.

**Comment by solidfoxrock** [comment]
Thanks for your answer alikhtarov, but then how do we replicate `cas` to all replicas? (assuming we're using `cas` instead of `set` everywhere). It looks impossible to me, but I'm still not sure.

**Comment by ryanmce** [comment]
`gets` and `cas` are fundamentally point-to-point operations. I don't think that a one-to-many broadcast can achieve the aims of a `cas` operation (which is that a writer can only update the value if no one else has written in the mean time).

I don't think either operation makes sense when broadcast. For example, if you run a `gets` to multiple boxes at the same time, which token does mcrouter return to the client? If you run a `cas` to those same set of boxes, at most one could succeed (whichever's token is sent back in the cas call).

If you take a step back and describe the problem you want to solve, we may be able to suggest ways mcrouter could help.

**Comment by solidfoxrock** [comment]
Hi Ryan, actually I had no problem with this yet. Recently our team was playing with a third party memcached client written in golang, and by default it uses `gets` and `cas`, instead of `get` and `set`, so I just wonder if it can play well with our current mcrouter setup. I didn't dig deep enough to understand the nature of `gets` and `cas`, but now I know that it doesn't make sense to broadcast these operations, thanks to your helpful explanation.

Best,
Kien
