### ISSUE TITLE
unrecognized option '--pid-file'

### ISSUE THREAD

**Issue by pySilver** [facebook/mcrouter#291]
Hello,

I've installed mcrouter using deb package from this repo and it fails to start with `mcrouter --port 5000 --config-file /etc/mcrouter.conf  --log-path /var/log/mcrouter.log --pid-file /var/run/mcrouter.pid --num-proxies 1`

output:

`mcrouter: unrecognized option '--pid-file'
I1230 14:24:04.466610 15452 StandaloneUtils.cpp:398] Logging to /var/log/mcrouter.log`

Is this option is no longer supported? `-P` results in `mcrouter: invalid option -- 'P'`

**Comment by pySilver** [comment]
Moreover `%CPU_CORES%` seems to be not supported also. Looks strange. Is deb package is so outdated?

```
FAILURE 1546381733.396229 1154 [libmcrouter.unknown.unknown] [invalid-option] [mcrouter] StandaloneUtils.cpp:156] Option parse error: num_proxies=%CPU_CORES, couldn't convert value to integer. Exception: Non-digit character found: "%CPU_CORES"
"mcrouter":  --port=5000 --config-file=/etc/mcrouter.conf --num-proxies=%CPU_CORES --log-path=/var/log/mcrouter.log
I0101 22:28:53.396311  1154 StandaloneUtils.cpp:448] 39.0.0-master mcrouter startup (1154)
I0101 22:28:53.396329  1154 StandaloneUtils.cpp:186] Starting Memcache router
I0101 22:28:53.396351  1154 Server-inl.h:172] Spawning AsyncMcServer
I0101 22:28:53.396530  1154 FunctionScheduler.cpp:405] Starting FunctionScheduler with 0 functions.
I0101 22:28:53.396983  1154 CarbonRouterInstance-inl.h:516] creating config builder
I0101 22:28:53.398295  1154 CarbonRouterInstance-inl.h:487] started reconfiguring
I0101 22:28:53.398434  1154 CarbonRouterInstance-inl.h:504] reconfigured 1 proxies with 1 pools, 1 clients d63c13d8aee75d6a2d1c7a6bd2f195d7)
```

**Comment by orishu** [comment]
Hi @pySilver , this option was removed almost four years ago, in this commit: https://github.com/facebook/mcrouter/commit/527be249a1f6d3fadb6f7b15c84b1d8104bd9518

**Comment by pySilver** [comment]
@orishu I guess we need to update wiki then :) https://github.com/facebook/mcrouter/wiki/Command-line-options#process-management

**Comment by orishu** [comment]
Thanks @pySilver, I just removed that line from the wiki.
