### ISSUE TITLE
mcrouter container (plus a REST API)

### ISSUE THREAD

**Issue by jamescarr** [facebook/mcrouter#3]
Don't know where to share this, so I'll open an issue and share it here. :-)

I really love this project, it got released the very DAY I was dealing with memcached clustering issues with our hastily built cache warmer. Anyhow I have released a docker container with it installed and you can grab it [here](https://registry.hub.docker.com/u/jamescarr/mcrouter/). It's pretty straightforward and conveniently already has a mounted volume for /etc/mrouter to pick up configurations. 

The other docker image I pushed out exposes modifying the configuration via a REST API and requires being linked with the previous container. Still some heavy development going into this but I'd definately like some feedback: https://registry.hub.docker.com/u/jamescarr/mcrouter-rest-api/. 

Again, thanks for sharing such a great tool! :+1:

**Comment by int** [comment]
We now have a [Dockerfile](https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/docker/Dockerfile) in our repo now.

Stay tuned for the official docker image on Docker Hub.

**Comment by jamescarr** [comment]
Cool one thing you might want to keep in mind is how to make the image smaller. See mine: 

```
jamescarr/mcrouter                1.0.0               206693e4f5d2        3 months ago        2.086 GB

```
A whopping 2GB! I haven't figured out how to make this smaller but I think it could be accomplished by building a `deb` of mcrouter and then installing it on a debian or busybox base image.

**Comment by int** [comment]
That you could.  Share with the [mcrouter community](https://www.facebook.com/groups/mcrouter/) if you make it. :)

The image built off our [Dockerfile](https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/docker/Dockerfile) results in a size of ~290M.  We have tried to make the image as small as possible:

- use a single `RUN`: to avoid intermediate (fat) layers (virtual size always adds up, not just the final layer per se)
- remove unneeded lib and headers both system-wide and hand-installed (among which `boost` header is hugest like 100M+)
- strip resulting `mcrouter` binary (-90M)
- remove any src/obj we grabbed/generated which we dont need to run mcrouter

There's also this [docker squash](https://github.com/jwilder/docker-squash) tool that you might check out. Cant squeeze much for ours as we've already removed all the fat. Hopefully it could save some space for yours. =)

I'm closing this issue as we have this [Dockerfile](https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/docker/Dockerfile) in our repo now.  We also added links to your Dockers to the [mcrouter installation wiki](https://github.com/facebook/mcrouter/wiki/mcrouter-installation#third-party-dockers).  Thanks.
