### ISSUE TITLE
Identify pool servers as down before reading/writing from/to them

### ISSUE THREAD

**Issue by shahar-fleischman** [facebook/mcrouter#304]
Hi,

I'm starting a mcrouter process with 2 pools(each with 5 mem servers).
All the mem server processes are down, when running "stats servers", All backend servers look ok.
Is mcrouter suppose to check them even if they weren't used before ?
Only after requesting get/set/add/delete from mcrouter it marks the relevant backends as down.

Version 39.0.0-master mcrouter

Example:

Before get:
STAT mem-10005:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10002:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10004:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10001:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10003:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10004:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10003:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10002:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10005:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10001:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16

After get:
STAT mem-10003:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10001:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10005:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10002:11211:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10004:11211:ascii:plain:notcompressed-1000 avg_latency_us:780.000 pending_reqs:0 inflight_reqs:0 hard_tko;  avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:15 down:1; connect_error:1
STAT mem-10002:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10004:11212:ascii:plain:notcompressed-1000 avg_latency_us:734.000 pending_reqs:0 inflight_reqs:0 hard_tko;  avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:15 down:1; connect_error:1
STAT mem-10003:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10005:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16
STAT mem-10001:11212:ascii:plain:notcompressed-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 new:16

Thanks.

**Comment by stuclar** [comment]
The stats servers command will walk through the destinationMap of each proxy thread and update stats for each stored destination. The information stored about each destination is as a result of a request, so if McRouter has yet to send a request to that destination it does not know that it is down.
