### ISSUE TITLE
Deb repo returns 404 

### ISSUE THREAD

**Issue by pySilver** [facebook/mcrouter#309]
https://facebook.github.io/mcrouter/debian - 404

**Comment by orishu** [comment]
The repo has moved but pull request #305 hasn't been merged yet.
You can see the new location of the deb repo in the pull request's README.md file:
https://github.com/facebook/mcrouter/pull/305/commits/3906fb829ca4f0280c232dab42212fca560d9775

**Comment by pySilver** [comment]
wow. thanks for quick reply!

**Comment by orishu** [comment]
#305 has been merged, README.md points to the new place, closing.

**Comment by kevb** [comment]
I get 404 at new URL - https://facebook.github.io/mcrouter/debrepo/bionic - am I missing something?

**Comment by orishu** [comment]
@andreazevedo would you mind taking a look? 😉
