### ISSUE TITLE
Service script for mcrouter on Ubuntu 14.04?

### ISSUE THREAD

**Issue by jeffbyrnes** [facebook/mcrouter#31]
Any chance there's a service script floating around somewhere for mcrouter? Preferably for Ubuntu 14.04, but any Debian-like system would suffice.

I'm in the midst of writing a [Chef cookbook for mcrouter](http://github.com/evertrue/mcrouter-cookbook).

**Comment by andreazevedo** [comment]
Hello @jeffbyrnes,
Do you still need help with it? Did you manage to setup runit?
Thanks

**Comment by jeffbyrnes** [comment]
Would love some help. Writing an upstart script, actually, since I'm using Ubuntu 14.04. I'll post my script once I get to my desk. 



-- 

Jeff Byrnes
thejeffbyrnes.com
@thejeffbyrnes

**Comment by jeffbyrnes** [comment]
@andreazevedo ok, here's what I have right now:

```bash
# mcrouter - memcached protocol router
#
# mcrouter is a memcached protocol router for
# scaling memcached deployments

description "memcached protocol router"

start on runlevel [2345]
stop on runlevel [2345]

expect daemon

setuid mcrouter

env PID_PATH="/var/run/"

script
    PROG_ARGS="--async-dir=/mnt/mcrouter/spool"
    PROG_ARGS="$PROG_ARGS --route-prefix=/dc1/all/"
    PROG_ARGS="$PROG_ARGS --send-invalid-route-to-default"
    PROG_ARGS="$PROG_ARGS --num-proxies=16"
    PROG_ARGS="$PROG_ARGS --stats-root=/mnt/mcrouter/stats"
    PROG_ARGS="$PROG_ARGS --log-path=/mnt/mcrouter/log/mcrouter.log"
    PROG_ARGS="$PROG_ARGS --background"
    PROG_ARGS="$PROG_ARGS --managed-mode"
    PROG_ARGS="$PROG_ARGS --port=11211"
    PROG_ARGS="$PROG_ARGS --config-file=/etc/mcrouter/mcrouter.json"

    exec /usr/local/bin/mcrouter "$PROG_ARGS"
end script
```

which results in:

```
I0224 14:30:31.232331 22647 main.cpp:466] /usr/local/bin/mcrouter --async-dir=/mnt/mcrouter/spool --route-prefix=/dc1/all/ --send-invalid-route-to-default --num-proxies=16 --stats-root=/mnt/mcrouter/stats --log-path=/mnt/mcrouter/log/mcrouter.log --background --managed-mode --port=11211 --config-file=/etc/mcrouter/mcrouter.json 
E0224 14:30:31.232633 22647 mcrouter_config.cpp:52] no configuration source
mcrouter 1.0
usage: /usr/local/bin/mcrouter [options] -p port(s) -f config
```

**Comment by andreazevedo** [comment]
Hello @jeffbyrnes,
Did you try to run this generated command line (i.e. `/usr/local/bin/mcrouter --async-dir=/mnt/mcrouter/spool --route-prefix=/dc1/all/ --send-invalid-route-to-default --num-proxies=16 --stats-root=/mnt/mcrouter/stats --log-path=/mnt/mcrouter/log/mcrouter.log --background --managed-mode --port=11211 --config-file=/etc/mcrouter/mcrouter.json`  yourself? What result do you get?

**Comment by jeffbyrnes** [comment]
@andreazevedo yep, works great. Mcrouter kicks off and runs without issues. Apologies for not mentioning that earlier.

**Comment by jeffbyrnes** [comment]
I'm most confused why it thinks there's “no configuration source”, when I’m clearly specifying one.

**Comment by jeffbyrnes** [comment]
Damned bash… quoting works weirdly in this case. Here's what worked:

```bash
# mcrouter - memcached protocol router
#
# mcrouter is a memcached protocol router for
# scaling memcached deployments

description "memcached protocol router"

start on runlevel [2345]
stop on runlevel [2345]

expect daemon

setuid mcrouter

env PID_PATH="/var/run/"

script
    PROG_ARGS="--async-dir=/mnt/mcrouter/spool"
    PROG_ARGS="$PROG_ARGS --route-prefix=/dc1/all/"
    PROG_ARGS="$PROG_ARGS --send-invalid-route-to-default"
    PROG_ARGS="$PROG_ARGS --num-proxies=16"
    PROG_ARGS="$PROG_ARGS --stats-root=/mnt/mcrouter/stats"
    PROG_ARGS="$PROG_ARGS --log-path=/mnt/mcrouter/log/mcrouter.log"
    PROG_ARGS="$PROG_ARGS --background"
    PROG_ARGS="$PROG_ARGS --managed-mode"
    PROG_ARGS="$PROG_ARGS --port=11211"
    PROG_ARGS="$PROG_ARGS --config-file=/etc/mcrouter/mcrouter.json"

    exec /usr/local/bin/mcrouter $PROG_ARGS
end script
```

**Comment by jeffbyrnes** [comment]
Closed this too soon… starts up properly now, but then Upstart loses track of mcrouter & isn't aware of status or how to stop mcrouter.

**Comment by jeffbyrnes** [comment]
Ok, final version of said script. No longer using the `background` or `managed-mode` flags:

```bash
# mcrouter - memcached protocol router
#
# mcrouter is a memcached protocol router for
# scaling memcached deployments

description "memcached protocol router"

start on runlevel [2345]
stop on runlevel [2345]

respawn

setuid mcrouter

script
    PROG_ARGS="--async-dir=/mnt/mcrouter/spool"
    PROG_ARGS="$PROG_ARGS --route-prefix=/dc1/all/"
    PROG_ARGS="$PROG_ARGS --send-invalid-route-to-default"
    PROG_ARGS="$PROG_ARGS --num-proxies=16"
    PROG_ARGS="$PROG_ARGS --pid-file=/var/run/mcrouter/mcrouter.pid"
    PROG_ARGS="$PROG_ARGS --stats-root=/mnt/mcrouter/stats"
    PROG_ARGS="$PROG_ARGS --log-path=/mnt/mcrouter/log/mcrouter.log"
    PROG_ARGS="$PROG_ARGS --port=11211"
    PROG_ARGS="$PROG_ARGS --config-file=/etc/mcrouter/mcrouter.json"

    exec /usr/local/bin/mcrouter $PROG_ARGS
end script
```

This works solidly, starts & stops properly, and respawns the mcrouter process if it dies.

**Comment by andreazevedo** [comment]
Hello @jeffbyrnes,
Great! One thing that I would suggest is the use of [flavor files](https://github.com/facebook/mcrouter/wiki/Flavors), so that you would be able to change your mcrouter configs without touching your script again! :)
Thanks!

**Comment by jeffbyrnes** [comment]
@andreazevedo oh MAN! That is hugely helpful for writing a Chef cookbook. Being able to render out JSON files is way simpler than building a set of CLI flags. Thanks!
