### ISSUE TITLE
How often is DNS re-resolved?

### ISSUE THREAD

**Issue by MarkRose** [facebook/mcrouter#325]
So I haven't been able to find a quick answer to this. For simplicity in our network setup, we use DNS instead of IPs. However, sometimes we want to replace the memcached instance behind a DNS record with a new machine with a different IP address. Will mcrouter re-resolve a DNS record when a connection to a server fails and has to be reestablished?

**Comment by cambierr** [comment]
I would extend this question by this one: is multi-A dns resolution supported ?

As you can guess, use-case is kubernetes endpoints

**Comment by mszabo-wikia** [comment]
It looks like mcrouter internally uses the folly lib's SocketAddress representation when connecting to a memcached node, which doesn't support multi-A resolution.[1]

---
[1] https://github.com/facebook/folly/blob/master/folly/SocketAddress.h#L171

**Comment by stuclar** [comment]
As mentioned, mcrouter uses folly::SocketAddress which does not support multi-A DNS resolution.

**Comment by glennpratt** [comment]
Interesting, but that doesn't answer the original question?
