### ISSUE TITLE
0.41.0 in ubuntu repo

### ISSUE THREAD

**Issue by davidkarlsen** [facebook/mcrouter#330]
Could you push the latest release to the ubuntu repo: https://github.com/facebook/mcrouter/tree/gh-pages/debrepo/bionic/pool/contrib/m/mcrouter ?

**Comment by davidkarlsen** [comment]
Anyone here? Is the project abandoned?

**Comment by anidev** [comment]
Hi @davidkarlsen, this project is not abandoned. However we don't internally have a standardized way of generating Ubuntu packages, and the method used for previous releases may not be working correctly anymore. I can try to work on improving this process for future releases. In the meantime, @disylh can you look into releasing an ubuntu package for the most recent release?

**Comment by davidkarlsen** [comment]
@disylh Did it work out - anything that can be done to help?

**Comment by disylh** [comment]
Hi @davidkarlsen, sorry I didn't get the bandwidth to work on this recently. I would visit this soon. BTW xenial is likely not supported in v41 due to dependency changes.

**Comment by davidkarlsen** [comment]
Probably better to go with bionic which is LTS.

**Comment by amcrn** [comment]
@disylh Any chance you could get 0.41.0 built and pushed to the Ubuntu Repo? Thanks!

**Comment by davidkarlsen** [comment]
Current 0.40.0 package is broken on focal which is now LTS:
```
2020, 09:23:35The following information may help to resolve the situation:
24/04/2020, 09:23:35The following packages have unmet dependencies:
24/04/2020, 09:23:35mcrouter : Depends: libboost-context1.65.1 (>= 1.65.1) but it is not installable
24/04/2020, 09:23:35Depends: libboost-filesystem1.65.1 (>= 1.65.1) but it is not installable
24/04/2020, 09:23:35Depends: libboost-program-options1.65.1 (>= 1.65.1) but it is not installable Depends: libboost-regex1.65.1 (>= 1.65.1) but it is not installable
24/04/2020, 09:23:35Depends: libboost-system1.65.1 but it is not installable
24/04/2020, 09:23:35Depends: libdouble-conversion1 (>= 2.0.1) but it is not installable
24/04/2020, 09:23:35Depends: libevent-2.1-6 (>= 2.1.8-stable) but it is not installable
24/04/2020, 09:23:35E: Unable to correct problems, you have held broken packages.
24/04/2020, 09:23:36Removing intermediate container 59bbbc850094
```

**Comment by disylh** [comment]
@davidkarlsen it seems 0.40.0 package is not installable in focal. Thanks for notifying.
@amcrn I am still working on 0.41.0 package to support bionic and focal. It's not the top priority but given 0.40.0 is broken in focal I will try my best to make it happen sooner.

**Comment by amcrn** [comment]
For those who need a working Docker Image, these commits fix the Docker build for `master` and `0.41.0` respectively:

`master`: https://github.com/amcrn/mcrouter/commit/a11c32aeb00b01054424730839cfe6115448dbed
`0.41.0`: https://github.com/amcrn/mcrouter/commit/d06ad1165094d6e7e343063b65b3dd32ee5d6518

**Comment by davidkarlsen** [comment]
@disylh ☝️ maybe you can include the fix and provide an updated release for ubuntu?

**Comment by davidkarlsen** [comment]
> @disylh ☝️ maybe you can include the fix and provide an updated release for ubuntu?

@disylh any update?

**Comment by nmoller** [comment]
I've succeded to build some newer images, but so far they are not ready to push into production because they are huge
https://github.com/nmoller/mcrouter-docker
