### ISSUE TITLE
Incr/Decr On Non-Numeric Doesn't Match Memcached Return Value

### ISSUE THREAD

**Issue by amcrn** [facebook/mcrouter#334]
Problem: Incrementing or Decrementing a non-numeric value in Memcached returns a CLIENT_ERROR, whereas in Mcrouter it returns NOT_FOUND.

**Memcached**
```
telnet xxx 11211
Trying xxx...
Connected to xxx.com.
Escape character is '^]'.
set amcrn 0 0 2
hi
STORED
incr amcrn 1
CLIENT_ERROR cannot increment or decrement non-numeric value
quit
```
**Mcrouter**

```
telnet xxx 11211
Trying xxx...
Connected to xxx.com.
Escape character is '^]'.
set amcrn 0 0 2
hi
STORED
incr amcrn 1
NOT_FOUND
```

This was tested on Mcrouter 0.40.0

**Comment by amcrn** [comment]
@stuclar Any chance you could take a peek at this? Thanks.

**Comment by stuclar** [comment]
@amcrn Sure - i'll take a look and get back to you on this.

**Comment by stuclar** [comment]
This should now be addressed with the changes in 3e53b78.

**Comment by stuclar** [comment]
Closing given fix, please comment if you have further issues.

**Comment by amcrn** [comment]
Thank you very much @stuclar !
