### ISSUE TITLE
SSL-Setup with mcrouter 0.40+

### ISSUE THREAD

**Issue by theonajim** [facebook/mcrouter#336]
I am following the [SSL-Setup](https://github.com/facebook/mcrouter/wiki/SSL-Setup) documentation with mcrouter 0.40 and 0.41 . At first mcrouter wouldn't start, but there seems to be new --server-<> options, after switching to  options, mcrouter starts, but when I connect it logs the following empty identity FAILURE. What identity do I need to supply?
I tried the same setup with mcrouter 0.38 and it seems to work as expected.

`FAILURE 1587683179.224994 13435 [SSLCert] [bad-environment] [mcrouter] network/FizzContextProvider.cpp:81] Failed to create self cert from "my_server.crt" and "my_server_private_key.pem".  ex: empty identity
"libmcrouter.mcrouter.0": {"allow_only_gets":"0","async_spool":"/var/spool/mcrouter","asynclog_disable":"0","asynclog_port_override":"0","big_value_batch_size":"10","big_value_split_threshold":"0","client_queue_no_notify_rate":"0","client_queue_size":"1024","client_queue_wait_threshold_us":"0","collect_rxmit_stats_every_hz":"0","config":"file:mcrouter.json","config_dump_root":"/var/mcrouter/config","config_file":"","config_params":"","config_str":"","connect_timeout_retries":"0","constantly_reload_configs":"0","cross_cluster_timeout_ms":"0","cross_region_timeout_ms":"0","debug_fifo_root":"/var/mcrouter/fifos","default_qos_class":"0","default_qos_path":"0","default_route":"/././","disable_reload_configs":"0","disable_tko_tracking":"0","enable_compression":"0","enable_failure_logging":"1","enable_flush_cmd":"0","enable_logging_route":"0","enable_qos":"0","enable_send_to_main_shard_split":"1","enable_ssl_tfo":"0","failures_until_tko":"3","fibers_max_pool_size":"1000","fibers_pool_resize_period_ms":"60000","fibers_record_stack_size_every":"100000","fibers_stack_size":"24576","fibers_use_guard_pages":"1","file_observer_poll_period_ms":"100","file_observer_sleep_before_update_ms":"1000","flavor_name":"unknown","group_remote_errors":"0","jemalloc_nodump_buffers":"0","keepalive_cnt":"0","keepalive_idle_s":"300","keepalive_interval_s":"60","logging_rtt_outlier_threshold_us":"0","max_dumped_config_age":"3600","max_no_flush_event_loops":"5","max_rxmit_reconnect_threshold":"0","max_shadow_token_map_size":"1024","min_rxmit_reconnect_threshold":"0","miss_on_get_errors":"1","num_listening_sockets":"1","num_proxies":"1","pem_ca_path":"","pem_cert_path":"","pem_key_path":"","pool_stats_config_file":"","post_reconfiguration_delay_ms":"0","probe_delay_initial_ms":"10000","probe_delay_max_ms":"60000","proxy_max_inflight_requests":"0","proxy_max_throttled_requests":"0","reconfiguration_delay_ms":"1000","reset_inactive_connection_interval":"60000","router_name":"0","runtime_vars_file":"","rxmit_latency_deviation_us":"0","send_invalid_route_to_default":"0","server_timeout_ms":"1000","service_name":"mcrouter","ssl_connection_cache":"0","ssl_handshake_offload":"0","ssl_service_identity":"","ssl_verify_peers":"0","stats_async_queue_length":"50","stats_logging_interval":"10000","stats_root":"/var/mcrouter/stats","target_max_inflight_requests":"0","target_max_pending_requests":"100000","target_max_shadow_requests":"1000","tcp_rto_min":"-1","test_mode":"0","use_asynclog_version2":"0","use_compact_serialization":"0","version":"40.0.0 mcrouter","waiting_request_timeout_ms":"0","within_cluster_timeout_ms":"0"}
"mcrouter":  --ssl-port 11433 --server-pem-cert-path=my_server.crt --server-pem-key-path=my_server_private_key.pem --server-pem-ca-path=ca.crt --config file:mcrouter.json`

**Comment by disylh** [comment]
@theonajim mcrouter uses Fizz for TLS and it requires cert has [non-empty identity](https://github.com/facebookincubator/fizz/blob/master/fizz/server/CertManager.cpp#L91).  

The SSL-Setup you followed creates a self-signed certificate, which identity for Fizz is [CN](https://github.com/facebookincubator/fizz/blob/master/fizz/protocol/Certificate-inl.h#L59 ). So I guess the self-signed cert you created may not has CN. May try re-create the cert with non-empty CN.

**Comment by theonajim** [comment]
Thanks @disylh , that was helpful. The instructions on https://github.com/facebook/mcrouter/wiki/SSL-Setup end up generating a csr without a commonName. I believe this occurs because my_server_csr_san_config.txt doesn't have commonName_default set and openssl req command is run in batch mode, so there is no prompt to set commonName (CN).

**Comment by disylh** [comment]
Np @theonajim, actually it was inaccurate that I said mcrouter uses fizz for TLS. Mcrouter doesn't default to certain SSL protocol but based on the security mech set in the config for each access point. I don't see your json config and how you made the request, but the log shows you somehow hit the fizz path and throw at missing CN.

I am closing this now unless you see other issue. Thanks!
