### ISSUE TITLE
How to failover Mcrouter(memcached) on Kubernetes

### ISSUE THREAD

**Issue by rjonala** [facebook/mcrouter#339]
Hello,

I am running Mcrouter on Kubernetes(2 Mcrouter Pods and 4 Memcached pods). And, I am using replicated pools. Let's say after a while, first 3 memcached pods got restarted and only Pod-4 has data and clients can still access data from Pod-4(I am using MissFailoverRoute) but every time Mcrouter misses from 3 newly started Pods, it would get from Pod-4 and at the same time I want Mcrouter to do sets on 3 newly started Pods so that in future even if Pod-4 goes down, other 3 pods will be able to serve. Can someone please suggest what could be a better config for this?

Right now, my config is as follows,

> "pools": {
> "A": {
> "servers": [
> {{- $global := . }}
> {{- range $i, $e := until (.Values.memcached.replicaCount | int) }}
> "{{ $global.Release.Name }}-memcached-{{ $i }}.{{ $global.Release.Name }}-memcached.{{ $global.Release.Namespace }}.svc.cluster.local:11211",
> {{- end }}
> ]
> }
> },
> "route": {
> "type": "OperationSelectorRoute",
> "operation_policies": {
> "add": "AllSyncRoute|Pool|A",
> "delete": "AllSyncRoute|Pool|A",
> "get": "MissFailoverRoute|Pool|A",
> "set": "AllSyncRoute|Pool|A"
> }
> }
> }

**Comment by edenzik** [comment]
Your config looks correct to me. Specifically, all stateful operation (`add`, `delete`, `set`) will be sent to all pods using `AllSyncRoute` while on a `get`, you will send a request to each pod until you get a hit (with `MissFailoverRoute`).

Is this working properly? I expect this to exhibit the behavior you're looking for.

**Comment by rjprosper** [comment]
@edenzik Thanks for responding.

This config doesn't work as per my need. So, as part of testing, I've set a key through Mcrouter Telnet session and then killed first 3 pods of Memcached, my gets would still work since Memcached Pod-4 has the value stored but when I killed Pod-4, I lost the data. 

What I need is, after killing first 3 pods and do a get Mcrouter should get value from Pod-4 and as well as set keys in the newly created 3 Pods. In order to achieve this, I think, I would need to tweak my config a little bit(may be a Cold cache warm up setup?). Please suggest.

**Comment by edenzik** [comment]
To do this, you may need newly created pods to be the "cold" branch of a WarmUpRoute. This will mean that gets from the warm (pod-4) host go to the cold hosts for some specific duration.

After a warm up period, you can consider those pods as "up" and add them to the main pool. 

Hope this helps.

**Comment by rjprosper** [comment]
@edenzik, How should I declare a cold pool without knowing which pods will fail?

**Comment by rjonala** [comment]
@edenzik, How should I declare a cold pool without knowing which pods will fail?

**Comment by rjonala** [comment]
So, my config is as follows,

> {
>       "pools": {
>         "cold": { "servers": [ "server1", "server2" ] },
>         "warm": { "servers": [ "server3", "server4" ] }
>       },
>       "route": {
>         "type": "WarmUpRoute",
>         "cold": "PoolRoute|cold",
>         "warm": "PoolRoute|warm"
>       }
>     }

If server1 and server2(Pod1 and Pod2) go down, then it would be warmed up by the warm pool but what if server3 and server4(Pod3 and Pod4) go down? How would the sets act?

**Comment by edenzik** [comment]
There may be a way to do this that I'm not aware of, but as far as I know you'll any host that goes down to initially be in the "cold" pool, and then move it over the main ("warm") pool after the warm up duration by changing the config. 

Mcrouter isn't aware of which host had only recently gone down etc. - you'll need to build that part into your infrastructure. So initially, all your host will be in your "warm" pool. When a host goes down and comes back up, you'll need to detect that and add it to the "cold" pool for a while, and then add it back to the "warm" pool.

**Comment by rjonala** [comment]
@edenzik This makes sense. But, once the cold servers are warmed up, how should they be added to Warm pool again? Should this also be handled at Kubernetes level?

Could you please refer me to any documentation regarding Mcrouter on Kubernetes?

**Comment by edenzik** [comment]
> Should this also be handled at Kubernetes level?

Yea, this should be done at the Kubernetes level as it is a stateful change related to your hosts - rather than a routing change (e.g a host moving between two pools). 

We do not have any docs about running Mcrouter on Kubernetes unfortunately.

**Comment by rjonala** [comment]
@edenzik Is there any other way other than Cold cache warm up? Something like, Replicated pool, and if 2 Pods go down, Mcrouter would still get from other 2 Pods and at the same time set it to newly created Pods. Is that possible just by using Replicated pool setup?
