### ISSUE TITLE
feature: Random MissFailoverRoute ?

### ISSUE THREAD

**Issue by sebest** [facebook/mcrouter#35]
Hello

Is there the equivalent of MissFailoverRoute but with random instead of sequential?

I also tried LatestRoute but the traffic was not load balanced evenly and from the documentation LatestRoute stops as soon as it gets a non error response, i want it to keep trying on "miss" but randomizing the pool.

thanx

**Comment by andreazevedo** [comment]
Hello @sebest,
Currently we don't have this support in mcrouter. Generally, you would want to try to fail-over using some ordering (e.g. lower latency pools first, or some other heuristic that might apply for your scenario).
If you want to share how is your setup (e.g. how you do sets, deletes, etc), we might be able help you further.
Thank you

**Comment by sebest** [comment]
Hello @andreazevedo ,

Thanx for taking the time to answer to me.

I want to achieve something really similar to the replicated pool with the following criteria:
1/ i just need set and get
2/ for the set i want to write on 2 memcache server and only wait for the first successful set
3/ for the get i want the first non-error and try on the second memcache if the first returned a miss
4/ i want to load balance evenly the the number of "get" requests on my two memcache servers

The only criteria that i can't achieve is number 4 as all the "get' go on the first server on the list as he always has the key.

here is my configuration file:
{
  "pools": {
    "A": {
      "servers": ["172.27.132.244:11211","172.27.135.40:11211",]
    }
  },
  "route": {
    "type": "OperationSelectorRoute",
    "operation_policies": {
      "gets": "LatestRoute|Pool|A",
      "set": "AllSyncRoute|Pool|A"
    }
  }
}

thanx

**Comment by alikhtarov** [comment]
Actually you can achieve this by composing RandomRoute and MissFailoverRoute. Under `get` policy (BTW I noticed you have `gets` there - is that intentional? `gets` and `get` are two different operations). 

You probably want to re-write your config as having two different pools. Something like:

```
{
  "pools": {
    "A": { "servers": ["172.27.132.244:11211"] },
    "B": { "servers": ["172.27.135.40:11211"] }
  },
  "route": {
    "type": "OperationSelectorRoute",
    "operation_policies": {
      "get": {
        // Randomize on every request between two children
        "type": "RandomRoute",
        "children": [
          // First option: send to miss failover, which tries A first, then B
          { "type": "MissFailoverRoute", "children": ["PoolRoute|A", "PoolRoute|B"] },
          // Second option: same, but try B first, then A
          { "type": "MissFailoverRoute", "children": ["PoolRoute|B", "PoolRoute|A"] }
        ]
      },
      "set": { "type": "AllSyncRoute", "children": ["PoolRoute|A", "PoolRoute|B"] }
    }
  }
}
```

**Comment by sebest** [comment]
Thanx @alikhtarov , i understand the logic behind your example.

I really need gets as for some reason the golang memcache library is using gets to do get.

Now i just have to figure out how to generate this kind of configuration file using consul-template as if i have a 3rd server, implementing the "shifting" logic in the list of children may not be easy:
a,b,c
b,c,a
c,a,b

**Comment by pavlo-fb** [comment]
@sebest you can just have a map of pools in a separate file (pools.json) and then use the following config:

Your config, config.json:
```JavaScript
{
  "macros": {
    "all-pools": {
      "type": "constDef",
      "result": "@import(pools.json)"
    },

    // list of routes for each pool [ "PoolRoute|A", "PoolRoute|B", ... ]
    "pool-routes": {
      "type": "constDef",
      "result": {
        "type": "foreach",
        "from": "@sort(@keys(%all-pools%))",
        "use": [ "PoolRoute|%item%" ]
      }
    },

    // number of pools for failover: min(number of pools, 3)
    "failover-cnt": {
      "type": "constDef",
      "result": {
        "type": "if",
        "condition": "@less(@size(%pool-routes%), @int(3))",
        "is_true": "@size(%pool-routes%)",
        "is_false": 3
      }
    },

    // at most %failover-cnt% pool routes starting from %shift%
    "shiftedPoolRoutes": {
      "type": "macroDef",
      "params": [ "shift" ],
      "result": {
        "type": "foreach",
        "from": "@range(@int(0), @sub(%failover-cnt%, @int(1)))",
        "use": [
          "@select(%pool-routes%, @mod(@add(%shift%, %item%), @size(%pool-routes%)))"
        ]
      }
    }
  },

  "pools": "%all-pools%",
  "route": {
    "type": "OperationSelectorRoute",
    "operation_policies": {
      "get": {
        // Randomize on every request between children
        "type": "RandomRoute",
        "children": {
          "type": "foreach",
          "from": "@range(@int(0), @sub(@size(%all-pools%), @int(1)))",
          "use": [
            {
              "type": "MissFailoverRoute",
              "children": "@shiftedPoolRoutes(%item%)"
            }
          ]
        }
      },
      "set": { "type": "AllSyncRoute", "children": "%pool-routes%" }
    }
  }
}
```

Corresponding pools.json:
```JavaScript
{
  "A": { "servers": ["172.27.132.244:11211"] },
  "B": { "servers": ["172.27.135.40:11211"] }
}
```

To get config without macros, one can send ```get __mcrouter__.preprocessed_config``` command to mcrouter.
