### ISSUE TITLE
Regression in standalone mode startup following IOThreadPoolExecutor migration

### ISSUE THREAD

**Issue by LINKIWI** [facebook/mcrouter#359]
When launching standalone mcrouter with an invalid config, the previous behavior is that it would throw an exception that causes the process to exit nonzero immediately with an error.

After db4702c5f6855054902ce4e5a0ae35a6e6e5293b "Add IOThreadPoolExecutor support to CarbonRouterInstance init function and migrate ratelim aggregator to use IOThreadPoolExecutor", an invalid config on startup now causes the process to stay up indefinitely without completing creation of AsyncMcServer.

Previous behavior when starting the process with an invalid config:

```
...
E1104 20:09:15.936131     6 CarbonRouterInstance-inl.h:265] Failed to configure proxies
I1104 20:09:15.942517     6 Server-inl.h:533] Shutting down
E1104 20:09:15.942534     6 Server-inl.h:570] mcrouter error (router name '22001', flavor 'unknown', service 'mcrouter'): Failed to configure, initial error 'Failed to reconfigure: AllThresholdRoute: threshold must satisfy 0 < threshold <= children', from backup 'Failed to reconfigure: AllThresholdRoute: threshold must satisfy 0 < threshold <= children'
# Process exits
```

Current behavior:

```
...I1104 20:08:59.310926  7313 CarbonRouterInstance-inl.h:481] started reconfiguring
FAILURE 1604520539.316906 7313 [libmcrouter.mcrouter.22001] [invalid-config] [mcrouter] ../mcrouter/CarbonRouterInstance-inl.h:490] Failed to reconfigure: ...
E1104 20:08:59.316934  7313 CarbonRouterInstance-inl.h:302] Failed to configure proxies
# No additional output, hangs forever without exiting and without a server listening
```

cc @stuclar as original author

**Comment by LINKIWI** [comment]
It seems to be hanging in https://github.com/facebook/mcrouter/blob/e06f88a012b0801a18da690e791da6bacdbcc7d4/mcrouter/CarbonRouterInstance-inl.h#L154, after `createRaw` throws an exception due to the invalid config.

**Comment by stuclar** [comment]
Thanks fir the info. Ill take a look at this and fix it.
