### ISSUE TITLE
Online reconfiguration across multiple MCrouter instances

### ISSUE THREAD

**Issue by SeKwonLee** [facebook/mcrouter#368]
When multiple MCrouter instances are pooling the same set of Memcached server nodes, can I make the instances work on reconfiguration together consistently upon adding (or removing) a new Memcached server node? I could use online reconfiguration easily by the server lists in the local config file when I am using a single MCrouter instance, but I could not find a way of doing it across multiple MCrouter instances consistently. I am expecting there should be a consensus mechanism between multiple MCrouter instances to do it. Is the current implementation of MCrouter supporting it?

**Comment by STOCKZE** [comment]
something akin to raft ?

**Comment by SeKwonLee** [comment]
Yes
