### ISSUE TITLE
php-fpm 5.5.23 doesn't work with mcrouter

### ISSUE THREAD

**Issue by 0xd3adsh3ll** [facebook/mcrouter#38]
Hello, I get a strange problem with mcrouter and php5-fpm. I have servers with php-fpm 5.5.4 they work fine with mcrouter via "session" and "session.save_path", but If I start php5-fpm 5.5.23 my app work very slow, if I replace in 5.5.23 session.save_path = "tcp://mcrouter.local:5000" to session.save_path = "tcp://memcached1.local:11211" php works fine. Do you know why this happinig?
Thanks.

**Comment by 0xd3adsh3ll** [comment]
Hello. For testing I'm install new server with: nginx 1.6, php5-fpm 5.5.23-1 and extensions: php5-curl php5-pgsql php5-memcache php5-mcrypt php5-intl php5-xdebug php5-gd php-gettext.
I have one server with php5-fpm and php application, one server with mcrouter cloning from master and two servers with memcached. My php.ini: http://pastebin.com/LrRqPceR You can see "session.save_path = "tcp://172.18.45.69:5000"" and "session.save_path = "tcp://172.18.45.82:11211"", if php.ini set conection via mcrouter my php application response very slow: HTTP request {"method":"GET","uri":"/index","gen_time":30.933,"db_time":0.049022965301514,"cache_time":0.16343712806702,"params":"[]"} and as you requesting I'm running ngrep on mcrouter port, this is dump: http://pastebin.com/VzWcmhEi
Below I replace connection via mcrouter to direct connection to memcached server and get this, my php.ini: http://pastebin.com/pqZXEPZV and ngrep dump: http://pastebin.com/d4TbHwSz and page loading normally: HTTP request {"method":"GET","uri":"/index","gen_time":0.775,"db_time":0.031301010101318,"cache_time":0.15716958045959,"params":"[]"}
For understandig:
172.18.45.31 - php application
172.18.45.69 - mcrouter
172.18.45.82 - memcached server
My mcrouter config: http://pastebin.com/QbQRH0K0

**Comment by andreazevedo** [comment]
Hello @0xd3adsh3ll,
Sorry for the late reply.

Can you please try to send a request to mcrouter both from your php application server (172.18.45.31) and from mcrouter box itself (172.18.45.69)?
You can use GNU netcat to do that:
1) log to `172.18.45.31` and send: `time echo get testkey | nc 172.18.45.69 5000`
2) log to `172.18.45.69` and send: `time echo get testkey | nc 0 5000`
Please, paste the outputs here.

Thanks

**Comment by 0xd3adsh3ll** [comment]
Hello. @andreazevedo. We don't use mcrouter anymore. You can close this issue.
Thanks.

**Comment by andreazevedo** [comment]
Hi @0xd3adsh3ll,
I'm sorry mcrouter didn't work for you guys.
I hope you can revisit in the future, we're constantly fixing bugs and improving performance.

**Comment by gcavana** [comment]
set ```session.save_handler = memcached``` and everything works fine.
