### ISSUE TITLE
“Stats files” wiki page has some formatting issues

### ISSUE THREAD

**Issue by jeffbyrnes** [facebook/mcrouter#387]
The [“Stats files” wiki page](https://github.com/facebook/mcrouter/wiki/Stats-files) appears to have meant to have some headers, e.g.,

```markdown
###startup_options This file contains command …
```

but there’s a space missing between the `#` characters & the header itself, and an empty line missing after the header value. So the above would probably render more readable as

```markdown
### startup_options

This file contains command …
```

**Comment by Happytreat** [comment]
Thank you for the feedback @jeffbyrnes will make the necessary change :)
