### ISSUE TITLE
Mcrouter adds MC_MSG_FLAG_BIG_VALUE flag but never removes it

### ISSUE THREAD

**Issue by sergmour** [facebook/mcrouter#401]
This issue regarding --big-value-split-threshold option. The option works well splitting big values into smaller chunks and reassembling the chunks when the key is requested.

The problem is that this option adds 0x8000 (MC_MSG_FLAG_BIG_VALUE) flag to the key flags and the flag is not cleaned up when the value is retrieved. We have at least 2 client libraries, xMemcached and spymemcached that fail to decode the value by misinterpreting the 0x8000 flag.

The flag is set [here](https://github.com/facebook/mcrouter/blob/main/mcrouter/routes/BigValueRoute-inl.h#L154) but never removed. It would be good to remove the flag at the end of big-value route processing.

Can you please explain if there is any reason why Mcrouter does not clean up 0x8000 flag after reassembling the value from multiple chunks? This would make the logic clean and reentrant.

**Comment by stuclar** [comment]
The reply flag is used to allow us to track large values in our datasets. I'll make a commit that makes this behaviour configurable so that you can opt out.

**Comment by stuclar** [comment]
https://github.com/facebook/mcrouter/commit/bf8944a15cec6a5acad30934b289978642264018 should address this for you. You can configure your mcrouter instance with big_value_hide_reply_flag set to true and the big value reply flag will be cleared.

**Comment by sergmour** [comment]
@stuclar : Thank you, Stuart! This should work.

We are still using the old Mcrouter-0.41 build on centos-7.9. It looks like it should be easy to port the change in the old build as building the latest on centos is not a straightforward task :).
