### ISSUE TITLE
mcrouter config problem config-file vs config-str

### ISSUE THREAD

**Issue by edux** [facebook/mcrouter#43]
Hi, I am testing mcrouter and the problem I found is that when I use config-file mcrouter.json:
{"pools":{"A":{"servers":["127.0.0.1:11211"]}},"route":"PoolRoute|A"}
mcrouter seems to lose connection to memcached

127.0.0.1:11211 (A) marked soft TKO. Total hard TKOs: 0; soft TKOs: 1. Reply: mc_res_timeout

but when I start mcrouter with config-str using the same line that is in the file, the mcrouter behaves perfect and memcslap loads data correctly.

I also tried to enable --disable-reload-configs thinking that maybe is related to some inotify issue.

I am missing something? I am running it on ubuntu 14.04 from master and installed using the provided script.

**Comment by alikhtarov** [comment]
Hi,
no, there should be no difference between using a config file and passing the config directly as a string. Can you reproduce the problem reliably? Could you include the full set up (memcached and memcslap command line arguments) and the steps to repro? Thanks!

**Comment by alikhtarov** [comment]
Please reopen if you need further help on this!
