### ISSUE TITLE
does mcrouter support udp protocol,

### ISSUE THREAD

**Issue by chandleralpha** [facebook/mcrouter#48]
I am using udp as my server protcol transfering data to memcache, but I want to use mcrouter as proxy for my memcache, but I don't know how to start mcrouter with udp port, can anybody help me out? thx.

**Comment by andreazevedo** [comment]
Hello @chandleralpha,
Mcrouter doesn't currently support UDP.
If you want more details on that, please take a look at [this post](https://www.facebook.com/groups/mcrouter/permalink/739810342804492/?qa_ref=qd) in [mcrouter facebook group](https://www.facebook.com/groups/mcrouter/).

**Comment by andreazevedo** [comment]
Hello @chandleralpha, 
I'm closing this issue, but feel free the re-open it (or file another one) if you still have questions.
Thanks!
