### ISSUE TITLE
Question about ch3/furc hashing algorithm

### ISSUE THREAD

**Issue by gotascii** [facebook/mcrouter#51]
Hi there,

I've noticed that when adding a box to the end of the list of servers in a PoolRoute using ch3 that it behaves as one would expect, in accordance with [this comment in hash.h](https://github.com/facebook/mcrouter/blob/master/mcrouter/lib/fbi/hash.h#L21-L45). However, recently we needed to remove a box about 2/3 of the way up in the list of servers. Coming from a hash ring implementation that was using [ketama](http://www.metabrew.com/article/libketama-consistent-hashing-algo-memcached-clients) we were greeted with quite a surprise when we rolled out the new config that removed the offending host. About 2/3 of the cluster was cold :/ What's the best way to handle removing various failing hosts from the config? Is this just something that shouldn't be happening all that often and TKO tracking + FailOverRoutes should be good enough to hold over while a bad host is reprovisioned? Any chance that Ketama could be added as a hash option?

Thanks!
Justin Marney

**Comment by alikhtarov** [comment]
@gotascii Hi, yeah in general our hash functions rely on the servers in the list never being re-ordered. Here's how we deal with this. There are a few situations when we might want to change the server list:
1) replace a box - in this case we simply replace the host at some index in the list with the new value, without reordering other hosts.
2) grow the size of the pool - for this, we take care to only add new boxes at the end of the list
3) shrink the pool - similarly, we only remove boxes from the end of the list.
Generally these are the only operations we do on the server lists in the config. Note that none of these should happen too often. For any transient failures, we rely on failover + TKO logic to temporarily disable the box without changing the pool's server list.

If the above doesn't work for you, please consider implementing the additional hash support yourself. It shouldn't be too difficult, you need to add an alternative to HashRoute that would hold a list of DestinationRoutes and use the destination keys to do the hash lookup.

**Comment by gotascii** [comment]
Sounds good, thanks for the clarification! If we end up taking a crack at adding ketama we'll send along a PR.

**Comment by andreazevedo** [comment]
Thanks @gotascii!
Let us know if you need anything else!
