### ISSUE TITLE
Reg:time taken for setting the keys

### ISSUE THREAD

**Issue by priya23** [facebook/mcrouter#54]
I have setup a mcrouter which is redirecting the request to 3 memcached servers.I am using telnet to connect to mcrouter and when i am setting the values in memcached through set command its taking lot of time but get is pretty fast.Can you please help out in this.

**Comment by andreazevedo** [comment]
Hello @priya23,
Yes, sure! Thanks for opening an issue.
Can you please share your config file?
Also, please share the output of the following commands: `get __mcrouter__.options` and `stats servers`. 
You can send the commands to your mcrouter using netcat: `echo get <command> | nc <host> <port>`.
Thank you!

**Comment by priya23** [comment]
Hi @andreazevedo 
following is my config file
{
   "pools": {
      "A": {
         "servers": [
           "IP1:11211",
           "IP2:11211",
	   "IP3:11211"
         ]
      }
   },
   "route": "PoolRoute|A"
 }


output for get __mcrouter__.options:

VALUE __mcrouter__.options 0 1610
new_ascii_parser 1
service_name mcrouter
router_name 5000
flavor_name unknown
standalone 1
asynclog_disable 0
async_spool /var/spool/mcrouter
use_asynclog_version2 0
asynclog_route_name 0
num_proxies 1
use_priorities 1
realtime_disabled 0
big_value_split_threshold 0
fibers_max_pool_size 1000
fibers_stack_size 24576
fibers_record_stack_size_every 100000
runtime_vars_file 
file_observer_poll_period_ms 100
file_observer_sleep_before_update_ms 1000
keepalive_cnt 0
keepalive_interval_s 60
keepalive_idle_s 300
reset_inactive_connection_interval 0
tcp_rto_min -1
target_max_inflight_requests 0
target_max_pending_requests 100000
target_max_shadow_requests 1000
no_network 0
proxy_max_inflight_requests 0
proxy_max_throttled_requests 0
pem_cert_path 
pem_key_path 
pem_ca_path 
destination_rate_limiting 0
enable_qos 0
default_qos_class 0
default_qos_path 0
constantly_reload_configs 0
disable_reload_configs 0
config_file /home/priyankas/mcrouter.json
config_str 
default_route /././
miss_on_get_errors 1
group_remote_errors 0
send_invalid_route_to_default 0
enable_flush_cmd 0
reconfiguration_delay_ms 1000
disable_tko_tracking 0
probe_delay_initial_ms 10000
probe_delay_max_ms 60000
failures_until_tko 3
maximum_soft_tkos 40
latency_window_size 16
server_timeout_ms 1000
cluster_pools_timeout_ms 0
regional_pools_timeout_ms 0
cross_region_timeout_ms 0
cross_cluster_timeout_ms 0
within_cluster_timeout_ms 0
same_connection_any_timeout 0
stats_root /var/mcrouter/stats
stats_logging_interval 10000
logging_rtt_outlier_threshold_us 0
stats_async_queue_length 50
enable_failure_logging 1
cpu_cycles 0
test_mode 0
END


output for stats servers:

stats servers
STAT 10.185.228.187:11211:TCP:ascii-1000 avg_latency_us:130603.000 pending_reqs:0 inflight_reqs:0 up:1; stored:1
STAT 10.216.194.210:11211:TCP:ascii-1000 avg_latency_us:742.777 pending_reqs:0 inflight_reqs:0 up:1; stored:3
STAT 10.7.153.194:11211:TCP:ascii-1000 avg_latency_us:130341.000 pending_reqs:0 inflight_reqs:0 up:1; stored:1
END


i tried the commands with your method but i am not getting any output
FDLMC039:~ priyankasharma$ echo get _mcrouter_.options | nc host port
END
,so i telnet into the machine and issued the commands.

Thanks.

**Comment by priya23** [comment]
Hi @andreazevedo ,

one more strange thing i observed now the commands started working the way you have asked them to run.

Regards,
Priyanka

**Comment by andreazevedo** [comment]
Hello @priya23,

Can you confirm if your "set" are still taking long time after you observed the commands started working? If so, how long is it taking?
Also, I notices that two of your servers are showing an unusual high latency (130ms). Are them in a different region/datacenter?

Thanks,
Andre

**Comment by priya23** [comment]
Hi @andreazevedo ,

yes they are still taking around 20-35 seconds to set the values.all these servers are running over EC2 classic instances in amazon but they are in same region.

Regards,
Priyanka

**Comment by priya23** [comment]
Hi @andreazevedo ,

i replicated the same thing inside a VPC in amazon and then i tried to set the values from the mcrouter server itself still its taking the same time following is the output for stats servers
stats servers
STAT 10.10.0.44:11211:TCP:ascii-1000 avg_latency_us:2496.142 pending_reqs:0 inflight_reqs:0 up:1; notfound:2 stored:5

Regards,
Priyanka
