### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by byxorna** [facebook/mcrouter#55]
For downstream packaging, it would really help if this project adopted semantic versioning and used git annotated tags to generate release tarballs. Any possibility of getting this tagged with some version? I am packaging this up, and really want to avoid assigning my own version to this project :)

Thanks!

**Comment by andreazevedo** [comment]
Hello @byxorna,

Thank you for opening this diff! 
We are currently working on that and you should start seeing it in the next few releases.

Thanks!

**Comment by andreazevedo** [comment]
Hello @byxorna,
We now have VERSION file. We will bump the version every time mcrouter is pushed.
I'm closing this task, but feel free to reopen it if you need anything else. Thanks!
