### ISSUE TITLE
Reg:dalli connection with mcrouter

### ISSUE THREAD

**Issue by priya23** [facebook/mcrouter#56]
Hi,
when i am using Dalli to connect with mcrouter its breaking,its not able to identify the server.Can you please help out in this.

Regards,
Priyanka Sharma

**Comment by andreazevedo** [comment]
Hello @priya23,

I'm not familiar with Dalli, but it looks like they use the memcached binary protocol by default.
Mcrouter does not currently support memcached binary protocol.

Thanks and let me know if you need anything else!
Andre

**Comment by priya23** [comment]
thanks for the reply. @andreazevedo 
i cannot switch to binary protocol.thanks
