### ISSUE TITLE
API for dynamic updates?

### ISSUE THREAD

**Issue by didip** [facebook/mcrouter#63]
Is there an API to update config json without restarting mcrouter?

In general, does mcrouter provides API endpoints for updating things? Can I do `set` for every `get` I see here? https://github.com/facebook/mcrouter/wiki/Admin-requests

This project is great! Thanks for releasing it.

**Comment by alikhtarov** [comment]
@didip Hi, it's easy to update config json without restarting - mcrouter automatically monitors the file for any changes and will reload it at runtime if you change it. If you want to point it to another file at runtime, one easy way to do it is to create a symlink that will point to the real config file and start mcrouter with that symlink - mcrouter will also monitor the changes to the symlink itself.

For the second part of the question, no, at the moment __mcrouter__ queries are read-only in general, and it's hard to change some of these options at runtime. We do plan to make most of the options more flexible (and put them into a separate .json config).

**Comment by didip** [comment]
@alikhtarov Thanks for the explanation!

The reason why I asked is because I am trying to figure out `mcrouter` deployment strategy on docker. It's preferable if I don't have to modify currently running container.

But if we put `mcrouter` inside the same container of the application, it should be fine, I think.

**Comment by alikhtarov** [comment]
Cool, I think I answered the questions you had, but feel free to re-open if you have anything else in mind.

**Comment by kinpa0a** [comment]
Hi.

Is there any improvement or change on updating configs?
If then, please let me know. Thanks. :-)!
