### ISSUE TITLE
Is there a route type that backfill all the misses on MissFailoverRoute?

### ISSUE THREAD

**Issue by didip** [facebook/mcrouter#65]
This is the use case I am thinking of:
* There are 2 replicas (Replica1 and Replica2), Replica1 goes down completely.
* `MissFailoverRoute` does the right thing for GET operation.
* Replica1 is fixed and back online.
* Is there a Route strategy that can back fill Replica1?

**Comment by andreazevedo** [comment]
Hello @didip,
There are some ways of warming up a clod cache box with mcrouter. The right choice will depend on your specific scenario (e.g. if your data changes often or is more static, etc). I will present you some ways of doing that and you can reply if you still have questions.
 - The most naive way is to use a AllSyncRoute for you `SET` operations. That way, whenever you do a `SET`, it will go to both replicas, so, given enough time, Replica1 will eventually get warm.
 - Another way is to use the `WarmUpRoute`. Take a look at this page for more information: https://github.com/facebook/mcrouter/wiki/Cold-cache-warm-up-setup. You can, for example, setup this route when Replica1 is back online and remove it once it's warmed up. (Remember that mcrouter can automatically detect new configs and reconfigure on-the-fly).
 - We are about to add another route handle called `SlowWarmUpRoute`. The idea is to simply not send `GET` requests to a box if it is cold (i.e. low hit rate). That way, mcrouter will failover automatically without even bother sending `GET` to the cold box (up to the point the box is warm again). That might be an option if used together with `MissFailoverRoute` for `GET` and `AllSyncRoute` for `SET`/`DELETE`.

Let me know if you still have questions.

**Comment by didip** [comment]
`SlowWarmUpRoute` seems nice! I'll definitely use it when it comes out.

Now, can I diverge a bit and ask question about `AllSyncRoute`?

Assuming that there are a lot of memcache backends and they can go down/up whenever, is using `AllSyncRoute` appropriate for `add, set, delete`? `AllSyncRoute` will almost always return error, no?

We are currently using `AllFastestRoute` because we don't want to care if one replica is down. Are we using it correctly?

I also have another question regarding combining both `PrefixSelectorRoute` and `OperationSelectorRoute`, do you guys prefer me using this ticket or open another ticket?

**Comment by andreazevedo** [comment]
Hello @didip,

Yes, if you just care about the `SET` being successful in one memcached rather then all of them (which seems to be what you want), then `AllFastestRoute` is the right choice for you.

You can use this issue or open a new one, whatever works better for you. :)

**Comment by didip** [comment]
Ok, i'll just use this ticket for simplicity.

We are currently providing a generic pool with 2 replicas, as what you already aware.

But at some point, a separate application would want to have its own pool for various reasons. e.g. cgroup protection, etc.

So this is roughly what I have in mind, this config doesn't work but hopefully helps to illustrate the point.
```
{
  "pools": {
    "App1Replica1": {
      "servers": [
        "mc-app-1:11211",
        "mc-app-3:11211",
      ]
    },
    "App1Replica2": {
      "servers": [
        "mc-app-2:11211",
        "mc-app-4:11211",
      ]
    },
    "Replica1": {
      "servers": [
        "mc-1:11211",
        "mc-3:11211",
      ]
    },
    "Replica2": {
      "servers": [
        "mc-2:11211",
        "mc-4:11211",
      ]
    }
  },
  "route": [
    {
      "aliases": [ "/app1/" ],
      "route": {
        "type": "OperationSelectorRoute",
        "default_policy": "PoolRoute|App1Replica1",
        "operation_policies": {
          "add": {
            "type": "AllFastestRoute",
            "children": [ "PoolRoute|App1Replica1", "PoolRoute|App1Replica2" ]
          },
          "set": {
            "type": "AllFastestRoute",
            "children": [ "PoolRoute|App1Replica1", "PoolRoute|App1Replica2" ]
          },
          "delete": {
            "type": "AllFastestRoute",
            "children": [ "PoolRoute|App1Replica1", "PoolRoute|App1Replica2" ]
          },
          "get": {
            "type": "MissFailoverRoute",
            "children": [ "PoolRoute|App1Replica1", "PoolRoute|App1Replica2" ]
          }
        }
      }
    },
    {
      "aliases": [ NotStartWith("/app1/") ],
      "route": {
        "type": "OperationSelectorRoute",
        "default_policy": "PoolRoute|Replica1",
        "operation_policies": {
          "add": {
            "type": "AllFastestRoute",
            "children": [ "PoolRoute|Replica1", "PoolRoute|Replica2" ]
          },
          "set": {
            "type": "AllFastestRoute",
            "children": [ "PoolRoute|Replica1", "PoolRoute|Replica2" ]
          },
          "delete": {
            "type": "AllFastestRoute",
            "children": [ "PoolRoute|Replica1", "PoolRoute|Replica2" ]
          },
          "get": {
            "type": "MissFailoverRoute",
            "children": [ "PoolRoute|Replica1", "PoolRoute|Replica2" ]
          }
        }
      }
    }
  ]
}
```
For everything with `/app1/` prefix, I'd like mcrouter to route to `[App1Replica1, App1Replica2]` pool,
and for everything else, traffic go to `[Replica1, Replica2]`.

Looking at it, I cannot help but to think this is the job of `PrefixSelectorRoute` but I am not seeing how it can be done, yet.

**Comment by didip** [comment]
Looks like that config works, just as expected!

I am starting to get the hang of the JSON DSL. Thanks a bunch guys!
