### ISSUE TITLE
--big-value-split-threshold doesn't delete chunks/parts

### ISSUE THREAD

**Issue by marko-jovicic** [facebook/mcrouter#66]
> The random suffix is needed for consistency - you can simply remove the original key and the chunks will be 'deleted' - there's no way to access them without knowing the random suffix. It also takes care of simultaneous sets, since only one key will win the race, and only its random suffix will be valid.

I have few questions about big value split threshold option:

1. When key is deleted, I find it out that other related parts/chunks are not deleted. Is this expected behaviour or not? 
2. In case of simultaneous sets, last key that is set has references to its other parts/chunks which is ok. However, chunks that are related to previous sets are not deleted, but they should be?

mcrouter is 1.0 version (built using [Dockerfile](https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/docker/Dockerfile)). Memcached version is 1.4.13.
mcrouter is started with this command:

```sh
# 5 bytes just in test purposes
mcrouter --big-value-split-threshold=5  --config-str='{"pools":{"A":{"servers":["127.0.0.1:5001"]}},"route":"PoolRoute|A"}' -p 5000 
```

**Comment by alikhtarov** [comment]
Hi,
1. Yes - we just "throw away the key", this way we don't have to worry about all chunks being deleted reliably
2. Same as in 1, only the last successful set will contain the valid random suffix for all the chunks. The previously set chunks are inaccessible (even though they still exist in memcached). Here we rely on random suffixes having very low collision rate in practice.

**Comment by marko-jovicic** [comment]
Hi, thank you for your answer.
I expected that deleting a key would delete all its parts.
I ran some tests using [memtier_benchmark](https://github.com/RedisLabs/memtier_benchmark) which multiple times set the same key during the test, which populated memcached memory very fast. (when --big-value-split-threshold is used). Although set operations shouldn't be that frequent I think that parts should be deleted anyway. Maybe to provide an async way of deleting such items?

**Comment by alikhtarov** [comment]
@marko-jovicic That option could be easily added to BigValueRoute logic, but I'm wondering what's your use case that requires the parts to be deleted? If you don't have any way to access them, they're as good as deleted - the only downside is they will affect stats reported by memcached (it will count them towards the number of items stored, and they will be evicted eventually, increasing eviction counter).

**Comment by marko-jovicic** [comment]
I need to store big values for 30 minutes. Rarely it happens that they are updated few times in that period of time. Using --big-value-split-threshold option we are left with some parts that we don't want to occupy the memory. Yes, those parts will expiry eventually. But in case when memcache is full, and you need to store new key in the same slab, I think that some other keys will be evicted also. You could avoid this by freeing memory by actually deleting "lost" parts, right? Generally speaking one might say that delete operation would undo set operation entirely, which is not true when big value option is used.
