### ISSUE TITLE
Does McRouter support all Memcache commands?

### ISSUE THREAD

**Issue by didip** [facebook/mcrouter#67]
I am thinking of `incr/decr` in particular.

**Comment by alikhtarov** [comment]
Hi, incr/decr are definitely supported and we in fact use them in production at Facebook. We don't use some commands like replace/append/prepend, and as a result they might not be as well tested.

**Comment by didip** [comment]
Thanks! It would be nice if mcrouter states which commands it supports on the README or wiki.
