### ISSUE TITLE
Data timeouts

### ISSUE THREAD

**Issue by solidfoxrock** [facebook/mcrouter#68]
Hi,

I want to move our memcached instances running locally on our servers to a shared cluster of 3 replicas using mcrouter. When I switch the setup, one of our servers (which has slightly more load than others) got errors when trying to connect to mcrouter. Then I found that all our memcached replicas got marked as soft TKO by mcrouter because of data timeouts.

```
I0706 16:03:57.282755 30919 ProxyDestination.cpp:298] cache2:11211 marked soft TKO. Total hard TKOs: 0; soft TKOs: 1. Reply: mc_res_timeout
I0706 16:03:58.247937 30919 ProxyDestination.cpp:298] cache1:11211 marked soft TKO. Total hard TKOs: 0; soft TKOs: 2. Reply: mc_res_timeout
I0706 16:03:58.248004 30919 ProxyDestination.cpp:298] cache3:11211 marked soft TKO. Total hard TKOs: 0; soft TKOs: 3. Reply: mc_res_timeout
I0706 16:04:09.410272 30919 ProxyDestination.cpp:298] cache1:11211 unmarked TKO. Total hard TKOs: 0; soft TKOs: 2. Reply: mc_res_ok
I0706 16:04:11.532776 30919 ProxyDestination.cpp:298] cache2:11211 unmarked TKO. Total hard TKOs: 0; soft TKOs: 1. Reply: mc_res_ok
I0706 16:04:12.243163 30919 ProxyDestination.cpp:298] cache3:11211 unmarked TKO. Total hard TKOs: 0; soft TKOs: 0. Reply: mc_res_ok
I0706 16:04:13.411573 30919 ProxyDestination.cpp:298] cache1:11211 marked soft TKO. Total hard TKOs: 0; soft TKOs: 1. Reply: mc_res_timeout
I0706 16:04:13.481298 30919 ProxyDestination.cpp:298] cache2:11211 marked soft TKO. Total hard TKOs: 0; soft TKOs: 2. Reply: mc_res_timeout
I0706 16:04:14.006347 30919 ProxyDestination.cpp:298] cache3:11211 marked soft TKO. Total hard TKOs: 0; soft TKOs: 3. Reply: mc_res_timeout
I0706 16:04:24.467892 30919 ProxyDestination.cpp:298] cache1:11211 unmarked TKO. Total hard TKOs: 0; soft TKOs: 2. Reply: mc_res_ok
I0706 16:04:27.244431 30919 ProxyDestination.cpp:298] cache3:11211 unmarked TKO. Total hard TKOs: 0; soft TKOs: 1. Reply: mc_res_ok
I0706 16:04:27.749204 30919 ProxyDestination.cpp:298] cache2:11211 unmarked TKO. Total hard TKOs: 0; soft TKOs: 0. Reply: mc_res_ok
```

On each server we have mcrouter running locally, but only this server has these timeouts. I have reviewed OS settings of this server and found nothing significantly different to other servers. When the timeouts happen I see a lot of TIME_WAIT TCP connections on this server, around 5000, not sure if it's just a consequence or not. Below is output of `stats servers` when the timeouts happen.

```
$ echo stats servers | nc localhost 1234
STAT cache1:11211:TCP:ascii-1000 avg_latency_us:278164.139 pending_reqs:0 inflight_reqs:0 up:1; deleted:108 found:241757 notfound:260681 stored:710487 timeout:85 remote_error:2
STAT cache2:11211:TCP:ascii-1000 avg_latency_us:546233.410 pending_reqs:0 inflight_reqs:0 up:1; deleted:108 found:239319 notfound:260687 stored:710344 timeout:41 connect_timeout:1
STAT cache3:11211:TCP:ascii-1000 avg_latency_us:322028.343 pending_reqs:0 inflight_reqs:0 up:1; deleted:102 found:239297 notfound:260839 stored:710408 timeout:32
END
```

I think our load to this problematic mcrouter instance is not high at all, it is less than 1000 requests / sec. The memcached replicas are also not the problem because other mcrouter running on other servers do not have timeouts. I have tried raising mcrouter timeout settings (`--server-timeout`, `--cluster-pools-timeout`, `--within-cluster-timeout-ms`), but it didn't help. I have also tried raising `--timeouts-until-tko` and reducing `--probe-timeout-initial` to a few seconds, but still I have timeouts every time.

Could you please help to enlighten me about these timeouts? As I've checked these are data timeouts and not connection timeouts, so I guess it has something related to either object size or workload, is it true?

Kien

**Comment by alikhtarov** [comment]
@solidfoxrock Hi, thanks for the report - could you also include command line options you run mcrouter with, the config file if possible and the github commit from which you built mcrouter?

**Comment by solidfoxrock** [comment]
@alikhtarov Hi, I just use simple command line options like this `mcrouter -p <port> --use-asynclog-version2 -f <config-file.conf>`. Below is my config file:

```
{
  "pools": {
    "mypool": {
      "servers": [
        "cache1:11211",
        "cache2:11211",
        "cache3:11211"
      ]
    }
  },
  "route": {
    "type": "OperationSelectorRoute",
    "operation_policies": {
      "delete": "AllFastestRoute|Pool|mypool",
      "set": "AllFastestRoute|Pool|mypool",
      "add": "AllFastestRoute|Pool|mypool",
      "incr": "AllFastestRoute|Pool|mypool",
      "decr": "AllFastestRoute|Pool|mypool",
      "get": {
        "type": "FailoverRoute",
        "children": [
          "RandomRoute|Pool|mypool",
          "LatestRoute|Pool|mypool"
        ]
      }
    }
  }
}
```

I use a rather old version of mcrouter, the commit is `fb5eea8`.

**Comment by alikhtarov** [comment]
I would urge you to try the newest version and see if the problem still reproduces - we had a number of bugfixes around TKO logic specifically that might have helped with that. We will continue to investigate if that doesn't help in your case.

**Comment by solidfoxrock** [comment]
Thanks @alikhtarov, I will upgrade our mcrouter and test this again

**Comment by alikhtarov** [comment]
@solidfoxrock any update on this issue?

**Comment by solidfoxrock** [comment]
@alikhtarov Hi, it's much better with the latest mcrouter version. I still see one or two timeouts once in a while, but it's totally acceptable for me. May I ask for some information about your TKO bugfixes?

**Comment by andreazevedo** [comment]
Hello @solidfoxrock,
We had some fixes in TKO itself (e.g. 0e1b975) and also some other bug-fixes that might have helped with your problem as well.
I'll close this issue, but fell free to re-open if you see that problem again.
