### ISSUE TITLE
Percentage of used RSS memory across all cluster?

### ISSUE THREAD

**Issue by didip** [facebook/mcrouter#73]
Among all the stats, I can't find %used RSS memory across all cluster. That number is useful to know for future provisioning.

Is this something that McRouter can offer in the future?

In the meantime, how do you guys (Facebook) know when mcrouter cluster is about to run out of capacity? Any handy scripts?

**Comment by andreazevedo** [comment]
Hello @didip,
Mcrouter `stats` command, report stats about mcrouter itself, not about memcached. So, our `ps_rss` stat, tells you how much memory mcrouter is consuming.
I'm assuming you are talking about rss of memcached, am I right?
Thank you

**Comment by didip** [comment]
@andreazevedo Thanks for the quick reply as usual.

Does mcrouter know total available RAM in all cluster? So i can do `ps_rss / X * 100` where X is total available RAM.

**Comment by andreazevedo** [comment]
Hello @didip,

Mcrouter does not know about nor reports the total RAM available in the server.

About these stats:
 - `ps_vsize` is Process' Virtual Memory Size.
 - `ps_rss` is Process' Resident Set Size.

This [thread](http://stackoverflow.com/questions/7880784/what-is-rss-and-vsz-in-linux-memory-management) gives a good overview of what is each one of these.

Your ultimate goal is to know when it is time to add more servers to a memcached cluster?

**Comment by didip** [comment]
Ah, I misread your earlier comments. I don't need to know mcrouter ps information.

Yes, I want to know when it is time to add more servers to a memcached cluster?

**Comment by andreazevedo** [comment]
Hello @didip,
Sorry about the long delay, for some reason I didn't see your reply before. :\

There is a set of things that you will want to monitor to make that decision. Here is a couple of things that might help you get started:
 - **Hit rate** and **evictions**: An increase in evictions and a drop in hit rate is _usually_ a good indicator that it is time to expand the pool. Also, take a look the age of the items being evicted (i.e. if items are being evicted too soon).
 - **Server stats**: Keep and eye on server stats, including `cpu idle` and `transmitted bytes`. They also indicate it's time to expand the pool, specially if they are consistent across the pool. If just one server is overloaded, it might be another problem though (like hot keys).

Let me know if that helps or if you need anything else. And again, sorry about the delay.

**Comment by didip** [comment]
This is great info, thanks! I'll close the ticket for now.
