### ISSUE TITLE
Document how to make mcrouter highly available

### ISSUE THREAD

**Issue by sontek** [facebook/mcrouter#78]
I see all kinds of documentation on how to get mcrouter to pool connections and mark servers and failed but I can't find information on how to keep mcrouter highly available.  Can you have a cluster of mcrouter nodes?   Or do you just setup multiple nodes and have the client libraries detect if mcrouter is down?

**Comment by pavlo-fb** [comment]
We usually either run mcrouter on the same host as client or use it as a library inside the client binary.

**Comment by sontek** [comment]
That is a pretty interesting idea =)

**Comment by pavlo-fb** [comment]
Feel free to reopen if there is something else I can help.
