### ISSUE TITLE
Docs for Multi-level caches

### ISSUE THREAD

**Issue by mckelvin** [facebook/mcrouter#79]
[Multi-level caches](https://github.com/facebook/mcrouter#features) listed in README is missing in [the Wiki page](https://github.com/facebook/mcrouter/wiki#features).

Would please detail that?

Tx.

**Comment by pavlo-fb** [comment]
@mckelvin here you go: [Two level caching](https://github.com/facebook/mcrouter/wiki/Two-level-caching)

**Comment by mckelvin** [comment]
@pavlo-fb Thanks a lot!
