### ISSUE TITLE
Omit index_range during traffic shadowing.

### ISSUE THREAD

**Issue by hrjaco** [facebook/mcrouter#80]
I am trying to do traffic shadowing. The current index_range would require us to remember to modify in case the pool size changes. Most of the time, we would probably just use [0, pool_size] as the index_range. Does McRouter currently support omitting index_range to default to [0, pool_size]?

An alternative is to define a macro to get the pool size, it seems we already size support https://github.com/facebook/mcrouter/wiki/JSONM#size. But I am not sure how to access the pools inside a macro. Any suggestions? Thanks!

**Comment by alikhtarov** [comment]
@hrjaco Hi, I belive you can achieve that by simply using [0, 1000000] (or a similar large value). We simply check that the destination host index is within range, the range itself doesn't have to be valid. Please try it and let me know if it worked.

**Comment by hrjaco** [comment]
that works, thanks @alikhtarov !
