### ISSUE TITLE
log rotation

### ISSUE THREAD

**Issue by marcinkuzmicki** [facebook/mcrouter#84]
How do you guys deal with log rotation ? 
Is there a way to notify mcrouter to reopen the log file ?

**Comment by alikhtarov** [comment]
@marcinkuzmicki Hi, we use the standard logrotate utility, it should work out of the box.

**Comment by marcinkuzmicki** [comment]
Thanks for your response.
Would you mind posting your logrotate config. Specifically I wonder if you use copytruncate directive ? 
I've  seen my mcrouter still writing to mcrouter.log.1 after was log rotated.

Regards
m

**Comment by alikhtarov** [comment]
We do use copytruncate. The config looks something like:

```
weekly
rotate 4
create
dateext

daily
rotate 14
maxage 14
compresscmd /usr/bin/pigz
copytruncate
compress
notifempty
missingok

/var/<logdir_location>/* {
  olddir /var/<logdir_location>/archive
}
```
