### ISSUE TITLE
Yet another long avg_latency_us issue

### ISSUE THREAD

**Issue by didip** [facebook/mcrouter#87]
Hi guys, I am seeing intermittent long avg_latency_us even though the box is not overloaded at all.

Even when mcrouter and memcache sits on the same box, `avg_latency_us` is still high.

But the high latency is not everywhere across all memcache backends.

Here's an example of high latency.
```
# The command is ran on chi-prod-docker-1 host.
$ echo stats servers | nc localhost 5000
STAT chi-prod-docker-1.nr-ops.net:29998:TCP:ascii-1000 avg_latency_us:5159.562 pending_reqs:0 inflight_reqs:0 closed:1; found:2 notfound:4 stored:3 connect_error:1
```

### uptime on chi-prod-docker-1
```
14:02:56 up 191 days, 19:42,  2 users,  load average: 3.27, 3.15, 3.00
```

What tools do I have to debug this?

**Comment by alikhtarov** [comment]
Thanks for the report, could you also include the command line you use to start mcrouter with (or alternatively the output of `echo get __mcrouter__.options | nc 0 5000`)

**Comment by didip** [comment]
### echo get __mcrouter__.options | nc localhost 5000
```
echo get __mcrouter__.options | nc localhost 5000
VALUE __mcrouter__.options 0 1682
new_ascii_parser 1
service_name mcrouter
router_name 5000
flavor_name unknown
asynclog_disable 0
async_spool /var/spool/mcrouter
use_asynclog_version2 0
num_proxies 1
client_queue_size 1024
client_queue_no_notify_rate 0
client_queue_wait_threshold_us 0
big_value_split_threshold 0
big_value_batch_size 10
fibers_max_pool_size 1000
fibers_stack_size 24576
fibers_record_stack_size_every 100000
runtime_vars_file 
file_observer_poll_period_ms 100
file_observer_sleep_before_update_ms 1000
keepalive_cnt 0
keepalive_interval_s 60
keepalive_idle_s 300
reset_inactive_connection_interval 60000
tcp_rto_min -1
target_max_inflight_requests 0
target_max_pending_requests 100000
target_max_shadow_requests 1000
no_network 0
proxy_max_inflight_requests 0
proxy_max_throttled_requests 0
pem_cert_path 
pem_key_path 
pem_ca_path 
destination_rate_limiting 0
enable_qos 0
default_qos_class 0
default_qos_path 0
constantly_reload_configs 0
disable_reload_configs 0
config_file /opt/mcrouter-config/mcrouter.json
config_str 
default_route /././
miss_on_get_errors 1
group_remote_errors 0
send_invalid_route_to_default 0
enable_flush_cmd 0
reconfiguration_delay_ms 1000
disable_tko_tracking 0
probe_delay_initial_ms 10000
probe_delay_max_ms 60000
failures_until_tko 3
maximum_soft_tkos 40
latency_window_size 16
server_timeout_ms 1000
cluster_pools_timeout_ms 0
regional_pools_timeout_ms 0
cross_region_timeout_ms 0
cross_cluster_timeout_ms 0
within_cluster_timeout_ms 0
same_connection_any_timeout 0
stats_root /var/mcrouter/stats
stats_logging_interval 10000
logging_rtt_outlier_threshold_us 0
stats_async_queue_length 50
enable_failure_logging 1
cpu_cycles 0
test_mode 0
asynclog_port_override 0
END
```

**Comment by didip** [comment]
I noticed one thing, all the long latency memcached are being used using `PrefixSelectorRoute` route type.

**Comment by didip** [comment]
Another information that might helped,

Hard restart of mcrouter (stop and start again) completely solve my problem, the average latency went down to 0.
```
STAT chi-prod-docker-1.nr-ops.net:29999:TCP:ascii-1000 avg_latency_us:0.000 pending_reqs:0 inflight_reqs:0 new:1
```

**Comment by alikhtarov** [comment]
@didip Also, do you have the commit from which you built mcrouter?

**Comment by alikhtarov** [comment]
@didip Looks like after the restart you haven't sent any requests to that server yet, (new:1 means we never tried to talk to that server), so you see latency 0.000. Can you try sending a few requests after the restart and confirm that latency is reasonable?

avg_latency_us is exponentially decaying average. If a new request comes in with round trip x, we update it as `avg = x * 1/16 + avg * 15/16`. So if you have a spike of slow requests, followed by no requests the latency will be stuck at the high level - it will only recover to normal levels after you send a few more requests over that connection.

**Comment by alikhtarov** [comment]
In fact in your case I see very few requests (closed:1; found:2 notfound:4 stored:3 connect_error:1) so that stat is very noisy. A single timeout would set avg to a very high value, and looking at the formula above you just didn't have enough requests to move the avg back to a normal value. The stat might be a bit misleading, but it works well with a constant stream of requests (as long as you have a few dozen requests per second).

**Comment by didip** [comment]
@alikhtarov I see, that makes a lot of sense. We are currently running mcrouter 1.0 and it looks like it's 7.0 version now. Should we upgrade?

**Comment by alikhtarov** [comment]
@didip Upgrading is a good idea regardless, we only sync to github after testing in production internally, and you might be missing some bugfixes. I don't think it will change what you see for this stat though as discussed.

Btw, can you share how you guys are using mcrouter? We're very interested to learn about the current use cases. Thanks!

**Comment by didip** [comment]
Sure! I need to dig out what git revision number we are on.

Tomorrow morning, i'll do a write up on our basic architecture. Hopefully that will shed some lights. Besides, we'd like to learn and see if what we are doing make sense.

**Comment by andreazevedo** [comment]
Closing due to the lack of activity.
Feel free to reopen if are still having similar issues.
