### ISSUE TITLE
About Adding New Instance

### ISSUE THREAD

**Issue by Bnaik** [facebook/mcrouter#89]
I have a question i have started mcrouter with 2 memcached instances {instance-A and Instance-B} with replicated pool.

Now if instance-B goes down i'll start a new instance-C but how it get replicated with instance-A?

**Comment by andreazevedo** [comment]
Hello @Bnaik,

Sorry for the delay in answering your question. For that, we have a variety of options, here are a few that are documented in our wiki:
 - https://github.com/facebook/mcrouter/wiki/Replicated-pools-setup
 - https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#warmuproute

Feel free to re-open this issue if you have further questions.
