### ISSUE TITLE
FailoverRoute issue

### ISSUE THREAD

**Issue by 0xd3adsh3ll** [facebook/mcrouter#9]
Hello again.
Currently I have config like this http://pastebin.com/Wfn08B5F
I have 1 server with mcrouter and 2 servers with memcached
For 'delete' - type AllAsyncRoute
For 'get' - type FailoverRoute
For 'set' - type AllAsyncRoute

From docs I read this:
"FailoverRoute

Sends the request to the first child in the list and waits for the reply. If the reply is a non-error, returns it immediately. Otherwise, sends the request to the second child, and so on. If all children respond with errors, returns the last error reply."

When I'm start my java app and run 1000 request on !set! to mcrouter server and test "AllAsyncRoute" (disconnect memcached1 or memcached2 via iptables rule) - it's OK, i can set all 1000 requests to both memcached servers, but when I start java app and run 1000 request on !get! from mcrouter then I get only keys from 1 of 2 servers and nothing all keys. I don't see failover mode.
Sorry for my stupid question, can you help me please?
Thanks.

**Comment by liyufu** [comment]
@0xd3adsh3ll 
http://pastebin.com/Wfn08B5F

your config file can't opened anywhere , i have some problem as you writed,now my config is not run the AllAsyncRoute ,please help me for you config, thanks!.


addtion:there is my issue,
https://github.com/facebook/mcrouter/issues/33

**Comment by 0xd3adsh3ll** [comment]
@liyufu
my config: http://pastebin.com/E1tVfAH0
This config works fine on production about 1 month.

**Comment by liyufu** [comment]
@0xd3adsh3ll 
Thanks , you almost never used the FailoverRoute  ?

if memcached1 is downed?the mcrouter can get data from memcached2?

after memcached1  is resolved and started, how to solve the memcached2 is empty problem?

thanks

**Comment by 0xd3adsh3ll** [comment]
Hello @liyufu,
I'm use:
for delete - AllSyncRoute - works fine with my app, AllAsyncRoute works fine too, but it's two different methods.
for set - MissFailoverRoute, if memcached1 marked as TKO (down, unreachable, etc) then request send to memcached2, if memcached2 can't response mcrouter return error.
for get - AllFastestRoute, get from fastest node (memcached1 or memcached2)

I'm don't use FailoverRoute because: "If the first server was available and didn't return an error reply, FailoverRoute will not send the request to second server."
If you have more questions please see facebook group https://www.facebook.com/groups/mcrouter/ or create new issue.

**Comment by liyufu** [comment]
Thanks.
