### ISSUE TITLE
mcrouter fail to test using memslap

### ISSUE THREAD

**Issue by AirJay** [facebook/mcrouter#91]
Hi, guys

I'm using memslap to test mcrouter, but "CLIENT_ERROR malformed request" error happened.
I could see memslap generates special key like "\020\020\020\020\020\020\020\020". Does mcrouter have a bug for parsing special characters ?

Thanks.

##### The config file for mcrouter:
```
{
   "pools": {
     "A": {
       "servers": [
         // your destination memcached boxes here, e.g.:
         "10.154.156.57:11111",
         "10.154.156.59:11111",
         "10.154.156.60:11111"
       ]
     }
   },
   "route": "PoolRoute|A"
}
```
##### The "CLIENT_ERROR malformed request" error:
```
[root@compute01 memslap]# memslap -s 127.0.0.1:11211 -t 1s -T 1 -c 1 -X 15      
servers : 127.0.0.1:11211
threads count: 1
concurrency: 1
run time: 1s
windows size: 10k
set proportion: set_prop=0.10
get proportion: get_prop=0.90
<6 CLIENT_ERROR malformed request
cmd_get: 0
cmd_set: 2
get_misses: 0
written_bytes: 92
read_bytes: 32
object_bytes: 62

Run time: 1.0s Ops: 2 TPS: 2 Net_rate: 0.0M/s
```

**Comment by james-r-carr** [comment]
IIRC it doesn't support the binary protocol.... maybe that's the problem?

**Comment by pavlo-fb** [comment]
It's kind of a known problem. `memslap` generates keys that contain control/whitespace characters. Mcrouter validates the keys according to [protocol](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L48-L49).

On the other hand opensource memcached supports keys with control characters :)

In any case, there are 3 options:
- the simplest one: use [twemperf](https://github.com/twitter/twemperf)
- patch `memslap` (it shouldn't be too hard, at least we managed to do this with mem**a**slap)
- remove the checks in mcrouter and fix relevant parts in parser code. The code lives in
https://github.com/facebook/mcrouter/blob/master/mcrouter/lib/mc/msg.c#L565
https://github.com/facebook/mcrouter/blob/master/mcrouter/lib/mc/ascii_client.rl#L232-L240
https://github.com/facebook/mcrouter/blob/master/mcrouter/lib/network/McAsciiParser.rl#L103

**Comment by Happytreat** [comment]
@pavlo-fb I'm currently using memaslap to stress test mcrouter. However the same <5435 CLIENT_ERROR malformed request is occurring

 Wondering if you can point to me where the patch for memaslap should be ?
