### ISSUE TITLE
Is there a way to increase the socket listen queue for mcrouter?

### ISSUE THREAD

**Issue by jkchin** [facebook/mcrouter#93]
Is there a way to increase the socket listen queue for mcrouter?

It looks like it's defaulting to 128 on my ubuntu box.

I know it's governed by 'SOMAXCONN' in the follow code
https://github.com/facebook/mcrouter/blob/70f5b228afa98588ee4bb48be2a0507106961597/mcrouter/lib/network/AsyncMcServer.cpp#L273.

Is that a dynamic value?

**Comment by jmswen** [comment]
Hi @jkchin!  `SOMAXCONN` is a constant defined in <sys/socket.h> on POSIX-compliant systems, and mcrouter respects this maximum value.  If you're using a recent Linux kernel, this value is defined to be 128.  However, on recent Linux kernels, you can adjust this value (system-wide!) with the command `sudo sysctl -w net.core.somaxconn=256` (or whatever value you'd like to try).  If you'd like this value to persist after reboot, you can run `echo "net.core.somaxconn=256" | sudo tee --append /etc/sysctl.conf`.

**Comment by jkchin** [comment]
@jmswen I'm using ubuntu 14.04, and have already set somaxconn=256 value in /etc/sysctl.conf, as well as confirmed it that it's using those values via `sysctl net.core.somaxconn` command.

I recompiled and restarted mcrouter after setting the somaxconn settings, but I still see that the listen queue length is 128 (via `ss -l`)

**Comment by alikhtarov** [comment]
@jkchin What's the reason you would want a larger listen queue? Mcrouter will accept connections as soon as possible, and if your connections are queuing up beyond the default queue size, you might be at the point where a longer queue will not help. Typically we open persistent connections from clients to mcrouter - we never optimized the use case of opening a lot of transient connections.

**Comment by jkchin** [comment]
It's to handle large number of long living connections at mcrouter bootup.

During memcached load tests with mcrouter with mutilate tool, I'm checking if mcrouter can handle large number of concurrent connections (1000s). At the start of the tests, there'll be alot of connections connecting to mcrouter at once, and the small queue size of 128 will cause load testing connections to be dropped as indicated by 'connection reset by peer' errors. Upping the queue size causes no issues.

**Comment by alikhtarov** [comment]
Ah interesting. It should be easy to add an option for the size of the queue (just see how other command line options are passed to the server code - a pull request is welcome! Another option is to try and throttle the rate at which the connections are opened in your loadtester, if that's easy to change.

**Comment by jkchin** [comment]
Thanks, I'll get a PR in when I get a chance
