### ISSUE TITLE
0.14.0 release fails to build against latest folly release

### ISSUE THREAD

**Issue by samveen** [facebook/mcrouter#98]
The latest release of mcrouter as of today (0.14.0) doesn't build correctly against the latest release of folly as of today (0.57.0). 

It would be great if 
* Mcrouter releases are issued against latest folly releases.
* OR Both releases are issued in tandem.

**Comment by alikhtarov** [comment]
@samveen Hi, starting from the latest release we're now including the file FOLLY_COMMIT which references the expected Folly github commit we want to build against (see the mcrouter release commit https://github.com/facebook/mcrouter/commit/e22c7c063d6240d3f7a8fd7f9bfba456b0e076fd)

Our build scripts use this file automatically. If you don't use the build scripts, make sure to parse the FOLLY_COMMIT file. In the future we will list other third-party repo hashes as well.

**Comment by kevinquinnyo** [comment]
@alikhtarov That's great.  So the v0.15 release should have been at bbc2a529cd5f2a5796e4d2fadecf4db86a9ac7be ?

I'm wondering because If I can always build the latest release against the correct folly, then I can 100% automate my .deb package building from here on out, as a nightly cron theoretically.

**Comment by alikhtarov** [comment]
@kevinquinnyo : yes, every new release branch will have an update to FOLLY_COMMIT file, so you can automate against that commit.

**Comment by samveen** [comment]
@alikhtarov Please close this issue, as I think the base issue looks resolved (or leave it open, till this info is well known?)
